akuity/kargo

docs/docs/10-concepts.md
@morey-tech and @nikita-akuity I would value your feedback on this doc.
Note that I don't intend for this page to explore every conceivable option in the Kargo resource types, nor every nuance of the controller. So if you see anything teased that isn't _fully_ explained, just know that there's a reference section also coming soon and those details will all be there.
=> add concepts doc

cmd/cli/main.go, cmd/cli/root.go, cmd/controlplane/api.go, cmd/controlplane/api_proxy.go, cmd/controlplane/controller.go, cmd/controlplane/main.go, cmd/controlplane/root.go, cmd/controlplane/version.go
Follow up patch for https://github.com/akuity/kargo/pull/344#pullrequestreview-1409358733
=> refactor: move commands to cmd package

.github/workflows/ci.yaml
This isn't needed every since Bookkeeper went public.
=> remove unnecessary bits from CI workflow

docs/docs/20-quickstart.mdx, docs/docs/30-how-to-guides/10-installing-kargo.md
Latest RC has an important bug fix, so this PR updates docs to install latest RC.
Reminder: We won't need to do this anymore once we finally cut a release that isn't semantically considered a pre-release.
=> update docs with latest version info

internal/config/config.go
=> Change default API port to 8080

go.mod, go.sum
https://github.com/akuity/gogoproto/commit/22fba0aeb992eaded03f87febc691c3821cb4710
=> Use the latest version of gogoproto

internal/controller/promotions/webhook.go
Signed-off-by: karthickbharathi1<karthicbharathi15@gmail.com>
=> fixed error message

docs/docs/30-how-to-guides/20-managing-credentials.md
Fixes #350 
Do not merge until after the `v0.10.0-rc.10` release since there are statements in this doc that are currently true only if Kargo was built from source.
=> document credential management

docs/docs/15-concepts.md
=> fix incorrect urls in concepts doc

charts/kargo-kit/Chart.yaml, charts/kargo-kit/templates/cluster-role-bindings.yaml, charts/kargo-kit/templates/cluster-roles.yaml, charts/kargo-kit/templates/service-account.yaml, charts/kargo-kit/values.yaml, charts/kargo/templates/controller/cluster-role.yaml
=> update kargo-kit chart to directly manage service accounts

internal/controller/promotions/webhook.go, internal/controller/promotions/webhooks_test.go
=> improve error message when admission webhook denies request

cmd/controlplane/controller.go, go.mod, internal/controller/applications/applications.go, internal/controller/environments/argocd.go, internal/controller/environments/environments.go, internal/controller/environments/environments_test.go, internal/controller/promotions/argocd.go, internal/controller/promotions/argocd_test.go, internal/controller/promotions/promotions.go, internal/controller/promotions/promotions_test.go, internal/credentials/credentials.go, internal/credentials/credentials_test.go
It could, for instance, be running as a native process. And Kargo CRs and Argo CD CRs also may not live in the same cluster either.
Fixes #418
=> support the possibility that the Kargo controller isn't co-located with its own data or with Argo CD

cmd/controlplane/controller.go, internal/credentials/credentials.go, internal/credentials/credentials_test.go
This PR rewrites the credentials DB to not rely on indexing k8s Secrets in-memory. Doing so requires permission to list/watch secrets across all namespaces and we're working on not requiring such broad permissions in the future.
This change represents a very meager performance hit. We can no longer use the bygone index to speed retrieval, so we have to list all secrets in a given namespace and iterate over them to see if they meet the selection criteria. That sounds worse than it is. Since we're only ever listing the secrets in a single namespace (Kargo Project), the list to iterate over isn't usually very big. Even if credential-borrowing (from Argo CD) is enabled, the number of secrets to iterate over in the Argo CD namespace shouldn't often be large either.
I took advantage of this …
=> rewrite credentials DB to not index k8s secrets

charts/kargo/values.yaml, internal/controller/applications/applications.go, internal/controller/applications/applications_test.go, internal/controller/common.go, internal/controller/labels.go, internal/controller/labels_test.go, internal/controller/promotions/promotions.go, internal/controller/stages/stages.go
Before this PR: Default controller operated on all resources.
After this PR: Default controller operates exclusively on unlabeled resources.
=> make default controller work exclusively on unlabeled resources

.github/governance.yml
This label seems to overlap with kind/enhancement.
=> remote kind/feat label from governance bot

Dockerfile, go.mod, go.sum
=> upgrade to latest bookkeeper

internal/cli/login/login.go
This adds an option to the `login` command that finds the bearer token used with the current kubectl context.
=> cli: add --kubeconfig option to login cmd 

ui/package.json, ui/pnpm-lock.yaml, ui/src/app.tsx, ui/src/config/paths.ts, ui/src/features/auth/oidc-login.tsx, ui/src/pages/login.tsx
=> Add OIDC login to UI

ui/src/config/transport.ts, ui/src/pages/login/login.tsx
Fixed hardcoded API url endpoint and added no-login state
=> fix(ui): Login view does not work

Dockerfile, Makefile, Tiltfile, internal/api/server.go, internal/http/http.go
1. API server will now serve UI assets. To see this in action:
https://kargo.demo.akuity.io/
2. Improved `make hack-build` to be able to push a multi-arch image for end-to-end testing.
3. Fix an envconfig bug
=> feat: serve kargo UI and bundle assets into image

ui/src/config/transport.ts
=> feat(ui): Add global API requests error handling

charts/kargo/templates/dex-server/secret.yaml
=> chart: fix dex config

api/service/v1alpha1/service.proto, cmd/cli/root.go, cmd/controlplane/api.go, internal/api/handler/watch_stage_v1alpha1.go, internal/api/server.go, pkg/api/service/v1alpha1/service.pb.go, pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go, ui/src/gen/service/v1alpha1/service_pb.ts
Part of https://github.com/akuity/kargo/issues/569
=> Add WatchStage handler

charts/kargo/templates/api/deployment.yaml, charts/kargo/templates/api/secret.yaml, internal/api/config/config.go, internal/api/handler/admin_login_v1alpha1.go
... as discussed this morning.
=> bcrypt admin password

ui/src/config/transport.ts, ui/src/features/auth/context/auth-context-provider.tsx
https://github.com/akuity/kargo/assets/7262558/060f811d-9b0a-468f-a735-07068cf9cf1e
=> feat(ui): Add auth token to request header

api/v1alpha1/stage_types.go, charts/kargo-kit/crds/kargo.akuity.io_stages.yaml, charts/kargo/crds/kargo.akuity.io_stages.yaml, internal/controller/stages/images.go, internal/controller/stages/images_test.go, internal/controller/stages/stages.go, ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
... as discussed this morning.
=> add optional field to image subscriptions to link it back to a source CODE (not config) repo 

charts/kargo/templates/api/deployment.yaml, charts/kargo/values.yaml, internal/api/config/config.go, internal/api/handler/admin_login_v1alpha1.go
=> make admin token ttl configurable

Tiltfile, charts/kargo/templates/api/configmap.yaml, charts/kargo/templates/api/deployment.yaml, charts/kargo/templates/api/secret.yaml, charts/kargo/templates/controller/configmap.yaml, charts/kargo/templates/controller/deployment.yaml, charts/kargo/templates/dex-server/deployment.yaml, charts/kargo/templates/garbage-collector/configmap.yaml, charts/kargo/templates/garbage-collector/cron-job.yaml, charts/kargo/templates/webhooks-server/configmap.yaml, charts/kargo/templates/webhooks-server/deployment.yaml
=> chart: simplify secret --> env var pattern

ui/src/features/project/project-details/project-details.tsx, ui/src/features/stage/create-stage-modal.tsx, ui/src/features/stage/stage-details.tsx
=> feat(ui): Add refresh Stage button

ui/src/features/common/code-editor/yaml-editor-lazy.tsx, ui/src/features/common/health-status/health-status-icon.tsx, ui/src/features/common/health-status/utils.ts, ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/stage-item.tsx, ui/src/features/project/project-details/utils/health.ts, ui/src/features/stage/available-freight.tsx, ui/src/features/stage/edit-stage-modal.tsx, ui/src/features/stage/manifest-preview.tsx, ui/src/features/stage/stage-actions.tsx, ui/src/features/stage/stage-details.tsx, ui/src/features/stage/utils/edit-stage-utils.ts
https://github.com/akuity/kargo/assets/7262558/84788edd-8a8c-41e5-9e87-5826e95123b3
=> feat(ui): Edit Stage / Manifest Preview

ui/src/features/stage/promotions.tsx
https://github.com/akuity/kargo/assets/426437/43362afb-d01a-4f8b-9b8a-c23f9f2ab83f
=> feat: implement promotions live update

ui/src/features/project/project-details/project-details.tsx, ui/src/features/stage/stage-details.tsx, ui/src/pages/project.tsx
https://github.com/akuity/kargo/assets/426437/0d10b9ba-cfbb-4980-8bbe-7b227dcf99d2
=> fix: stage details page should leverage stage watch API

.github/workflows/release.yaml
Fixes error on the release process. https://github.com/akuity/kargo/actions/runs/6124765936
=> chore: fix workflow permissions

docs/docs/20-quickstart.mdx, docs/docs/30-how-to-guides/10-installing-kargo.md
cc @morey-tech 
rc.21 is rolling out as we speak.
You may want to verify the steps that were broken before are unbroken by this change.
=> update quickstart to reference latest pre-release

ui/src/features/freightline/palette.tsx, ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/stage-node.tsx, ui/src/utils/stages.ts
=> feat: add button to promote subscribers from DAG

internal/controller/stages/argocd.go, internal/controller/stages/argocd_test.go, internal/controller/stages/stages.go, internal/controller/stages/stages_test.go
Fixes #692
I decided to tackle this separately from #570 after I saw how simple this was.
The test refactoring here is mostly mere cleanup for test cases that were impacted by the change anyway.
=> check stage health even when there is no current freight

ui/src/features/common/health-status/health-status-icon.tsx, ui/src/features/freightline/freightline.tsx, ui/src/features/project/project-details/stage-node.tsx
=> feat: improve freightline display for 4+ stages

ui/src/features/stage/edit-stage-modal.tsx, ui/src/features/stage/stage-actions.tsx
An error occurred after Project details page changes. The editor on Edit Stage modal didn't show the current value.
=> fix(ui): Edit Stage doesn't show current value

docs/docs/30-how-to-guides/10-installing-kargo.md
=> updated Argo CD and Cert manager versions

ui/src/features/project/project-details/images.tsx, ui/src/features/project/project-details/project-details.tsx
=> feat(ui): Images - sort stages by depth from root, sort images by ver

ui/src/features/project/project-details/project-details.tsx
Closes https://github.com/akuity/kargo/issues/712
=> fix: edges should come out from PromoteSubscribers button

ui/src/features/project/project-details/project-details.tsx
Closes https://github.com/akuity/kargo/issues/712
=> fix: subscription edges should into from promote button

ui/src/features/freightline/freightline.tsx
=> fix(ui): Number of freight uid characters is inconsistent

ui/src/features/common/code-editor/yaml-editor-lazy.tsx
=> feat(ui): Add a note about the suggestions feature below the yaml editor

ui/src/app.less, ui/src/features/common/code-editor/yaml-editor-lazy.tsx, ui/src/features/stage/manifest-preview.tsx, ui/src/features/stage/stage-details.tsx
https://github.com/akuity/kargo/assets/7262558/81e31ae3-939e-40f3-9262-04cf4e69c0e2
=> feat(ui): Adjust the height of Live Manifest to fit the screen size

charts/kargo/templates/garbage-collector/cluster-roles.yaml
=> fix garbage collector permissions

ui/src/features/freightline/freightline.tsx
=> feat(ui): Show rough timestamp for each freight

ui/src/features/project/project-details/nodes/stage-node.tsx, ui/src/features/project/project-details/project-details.tsx
=> fix(ui): Don't show promote subscribers button for DAG nodes with no subscribers

ui/src/features/project/project-details/nodes/stage-node.module.less, ui/src/features/project/project-details/nodes/stage-node.tsx
=> fix(ui): Stage name is collapsed

ui/src/features/project/project-details/project-details.tsx
Resolves https://github.com/akuity/kargo/issues/784
=> fix: rename 'Stage Graph' to 'Pipeline'

docs/docs/10-overview.md, docs/docs/15-concepts.md, docs/docs/20-quickstart.mdx, docs/docs/30-how-to-guides/10-installing-kargo.md, docs/docs/30-how-to-guides/20-managing-credentials.md, docs/docs/40-contributor-guide/10-hacking-on-kargo.md, docs/docs/40-contributor-guide/20-signing-commits.md, docs/docs/40-contributor-guide/index.md
Also, add monotype text for some resource names.
=> fix(docs): use titlecase for headings

docs/docs/20-quickstart.mdx, hack/quickstart/k3d.sh, hack/quickstart/kind.sh
This PR removes unimportant details from the quickstart setup by moving them into scripts. This should help users get to playing with Kargo more quickly and make the quickstart, overall, shorter and less intimidating.
=> script some of the quickstart to make it... quicker

internal/images/images.go
=> fix allowTags in image subscriptions

docs/docs/10-overview.md
=> Rephrased the caution text

.github/dependabot.yml
I added Dependabot to manage the dependencies and ensure we stay current.
=> chore: Added Dependabot

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement_proposal.md, .github/ISSUE_TEMPLATE/security_logs.md
This will add some issue templates to make it easier when submitting issues
=> chore: Added github issue templates

.github/governance.yml
Updated governance.yml to include kind/feature-request
=> Update governance.yml to include kind/feature-request

.github/ISSUE_TEMPLATE/config.yml
Update config.yml to include link to discussions
=> Update config.yml to include link to discussions

ui/src/features/freightline/freightline.tsx
=> feat: show stage colors in freightline in promotion mode

.github/dependabot.yml
Update Dependabot to run weekly on Sunday
=> Update dependabot to run weekly

Makefile
@krancour , created a fresh branch and the update to the docs and the make file
=> add support for alternative container runtimes to Makefile

charts/kargo/values.yaml
Fixes #976 
Hope this is ok.
Scott
=> fix:(helm charts): add notes about pkce in values.yaml #976

charts/kargo/templates/controller/cluster-roles.yaml
=> fix controller permissions to allow patching stages

internal/controller/warehouses/images.go, internal/credentials/credentials.go, internal/git/git.go
to be less dependant on argocd, this was done
related to #990
=> feat: copy argocd func

netlify.toml
May fix #925
[Explanation of the fix](https://github.com/akuity/kargo/issues/925#issuecomment-1771839000)
=> fix netlify pr doc previews

docs/docs/20-quickstart.mdx
=> update quickstart with notes about helm version

.github/workflows/release.yaml
This was modified earlier for testing purposes. Putting it back to the way we actually wanted it.
cc @34fathombelow
=> fix nightly build cron expression

internal/api/types/v1alpha1/types.go
=> fix resource <--> proto logic for Freight

internal/cli/delete/delete.go, internal/cli/delete/warehouse.go, internal/cli/get/get.go, internal/cli/get/warehouse.go
=> cli: add get + delete warehouse commands

.github/workflows/release.yaml
This step failed when cutting yesterday's RC.
Figured I'd fix it before the next RC or v0.2.0.
=> fix fig step in release process

internal/kargo-render/render.go
Fixes #1107 
@christianh814 is verifying this fixes the issue.
=> refactor kargo-render cmd invocation

charts/kargo/templates/controller/cluster-roles.yaml
@christianh814 this fixes the issue you just brought up.
cc @jessesuen
=> chart: give controller permission to patch warehouses

internal/controller/stages/stages.go, internal/kubeclient/indexer.go
Fixes #1111
Mistake was introduced earlier today in #1103
=> fix auto-promotions

.github/workflows/ci.yaml
Cherry-picked this from `main`
=> update ci triggers

ui/src/features/stage/subscriptions.tsx
Before:
After:
I also removed legacy code that generated typing errors in the console.
=> fix(ui): Warehouse subscription is not displayed in Stage details

ui/src/config/transport.ts
Fixes #877
In this PR, I added a handler to check the token expiration before requests.
=> fix(ui): Checking token expiration before requests

ui/src/features/common/freight-label.tsx
=> feat(ui): add freight ID tooltip to freight alias

charts/kargo/templates/api/cluster-role.yaml, ui/src/features/common/freight-label.tsx, ui/src/features/freightline/confirm-promotion-dialogue.tsx, ui/src/features/freightline/freight-contents.tsx, ui/src/features/freightline/freight-item.tsx, ui/src/features/freightline/freightline.module.less, ui/src/features/freightline/freightline.tsx, ui/src/features/freightline/promoting-stage-banner.tsx, ui/src/features/freightline/stage-indicators.tsx, ui/src/features/project/project-details/nodes/stage-node.tsx, ui/src/features/project/project-details/project-details.module.less, ui/src/features/project/project-details/project-details.tsx
=> feat(ui): Manually approve freight from UI

docs/docs/20-quickstart.mdx
=> make quickstart use appset

ui/src/features/project/project-details/project-details.tsx
=> fix: refetch freight upon warehouse refresh

ui/package.json, ui/pnpm-lock.yaml, ui/src/features/project/project-details/nodes/repo-node.module.less, ui/src/features/project/project-details/nodes/repo-node.tsx, ui/src/utils/url.test.ts, ui/src/utils/url.ts, ui/tests/api/apimachinery.spec.ts
=> fix: correct image links for popular image registries

charts/kargo/templates/webhooks-server/cluster-role.yaml
Fixes a bug introduced by #1162
=> fix(charts): permissions issue with webhooks server

api/v1alpha1/stage_types.go, api/v1alpha1/warehouse_types.go, charts/kargo/crds/kargo.akuity.io_stages.yaml, charts/kargo/crds/kargo.akuity.io_warehouses.yaml, ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json, ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
This PR needed because Helm repo regex currently isn't allowing `-` in repoURL
=> fix: helm repo regex to allow -

internal/cli/cmd/stage/promote.go, internal/cli/cmd/stage/promote_subscribers.go, internal/cli/cmd/stage/set_auto_promotion.go
=> feat(cli)!: update stage subcommands to make project a flagged arg instead of positional arg

ui/src/features/freightline/promoting-stage-banner.tsx
=> feat: ability to dismiss promotions info banner

ui/src/features/project/project-details/nodes/repo-node.module.less, ui/src/features/project/project-details/nodes/repo-node.tsx, ui/src/features/project/project-details/nodes/stage-node.tsx, ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/types.ts
Fixes #1275 
With subscription nodes expanded:
With subscription nodes collapsed:
=> feat: display warehouse and its subscription as separate nodes in the UI

go.mod, go.sum
This is the subset of #1297 that does not break the build.
=> chore(dependencies): go module dependency updates

api/v1alpha1/annotations.go, cmd/controlplane/api.go, internal/api/kubernetes/client.go, internal/api/kubernetes/client_test.go, internal/api/option/auth.go, internal/api/option/auth_test.go, internal/api/user/user.go, internal/api/user/user_test.go, internal/kubeclient/indexer.go
=> feat(api): treat sub and email fields of oidc tokens as distinct things; enable SA mappings by either

cmd/cli/main.go, internal/cli/client/client.go, internal/cli/cmd/config/set.go, internal/cli/cmd/config/unset.go, internal/cli/cmd/create/project.go, internal/cli/cmd/delete/project.go, internal/cli/cmd/delete/stage.go, internal/cli/cmd/delete/warehouse.go, internal/cli/cmd/get/freight.go, internal/cli/cmd/get/projects.go, internal/cli/cmd/get/promotions.go, internal/cli/cmd/get/stages.go, internal/cli/cmd/get/warehouse.go, internal/cli/cmd/update/freight-alias.go, internal/cli/config/config.go, internal/cli/config/errors.go
This cherry-picks #1345 into the `release-0.3` branch.
=> fix(cli): handle CLI config file not found error (#1345)

docs/docs/30-how-to-guides/15-working-with-freight.md
=> docs: document freight-related features from v0.3.0

charts/kargo/README.md, charts/kargo/templates/controller/configmap.yaml, charts/kargo/templates/controller/deployment.yaml, charts/kargo/values.yaml, cmd/controlplane/controller.go
Fixes #1359
Fixes #1363
cc @jessesuen @gdsoumya this should solve some problems for you both.
=> feat(controller): use optional third kubeconfig for rollouts kube client

cmd/cli/root.go, internal/cli/cmd/logout/logout.go
=> feat(cli): add logout command

ui/src/app.tsx, ui/src/features/auth/protected-route.tsx, ui/src/features/common/freight-label.tsx, ui/src/features/common/modal/modal-context.tsx, ui/src/features/common/portal.tsx, ui/src/features/project/project-details/nodes/stage-node.tsx, ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/update-freight-alias-modal.tsx, ui/src/features/stage/stage-actions.tsx
Fixes #1371
Fixes #1329 
Also improved the Freight Label tooltip:
=> feat(ui): ability to rename freight from UI

api/v1alpha1/labels.go, charts/kargo/templates/controller/cluster-roles.yaml, charts/kargo/templates/webhooks/webhooks.yaml, internal/api/delete_stage_v1alpha1.go, internal/controller/stages/stages.go, internal/controller/stages/stages_test.go, internal/webhook/stage/webhook.go, internal/webhook/stage/webhook_test.go
=> feat: use finalizer to ensure proper cleanup after stage deletion

internal/controller/stages/health.go, internal/controller/stages/health_test.go
Fixes #1411
cc @dhpup thanks for finding.
Due to the seriousness of the bug, I also intend to PR this to the `release-3.0` branch and release a v0.3.2.
=> fix(controller): fix assessment of how app sync state impacts stage health

internal/controller/promotion/argocd.go, internal/controller/promotion/git.go, internal/controller/stages/health.go, internal/controller/stages/health_test.go
Same as #1420 but headed for the v0.3.2 release.
=> fix(controller): always normalize git urls before comparison -- release-0.3 edition

internal/controller/promotion/argocd.go, internal/controller/promotion/git.go, internal/controller/stages/health.go, internal/controller/stages/health_test.go
Fixes #838 which was a secondary factor in the bug @dhpup reported in #1411
=> fix(controller): always normalize git urls before comparison

ui/src/features/project/project-details/project-details.tsx
This cherry-picks #1378 into the `release-0.3` branch.
cc @rbreeze
=> fix(ui): refetch freight after warehouse refresh -- release-0.3 edition

api/v1alpha1/warehouse_types.go, charts/kargo/crds/kargo.akuity.io_warehouses.yaml, docs/docs/15-concepts.md, docs/docs/20-quickstart.mdx, ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Closes #1342 
I've added an info panel to two places in the docs and update the CRD comment (and generated the crd docs again).
=> chore(docs): Add reference to semver constraint.

internal/controller/labels.go, internal/controller/stages/stages.go, internal/controller/stages/stages_test.go, internal/controller/stages/watches.go
This PR fixes the handling of sharded stage events emitted by dependant resources like argocd apps, analysis runs etc.
=> fix: handle sharded stage events

internal/controller/promotion/kustomize.go, internal/controller/promotion/kustomize_test.go, internal/kustomize/kustomize.go, internal/kustomize/kustomize_test.go
=> fix(controller): simplify exec of kargo edit set image command

Tiltfile
This change should have been included in #1483
=> fix: Tiltfile

ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/types.ts
=> fix(ui): allow DAG to display warehouses with multiple subscribers correctly

ui/src/features/freightline/freight-contents.tsx
=> fix(ui): long freight tags made promotion impossible 

docs/docs/15-concepts.md, docs/docs/20-quickstart.mdx, docs/docs/30-how-to-guides/15-working-with-freight.md, docs/docs/30-how-to-guides/20-managing-credentials.md, docs/docs/50-roadmap.md
Cherry picking some doc improvements from `release-0.4` to `main`.
=> chore(docs): port doc improvements from 0.4 release branch

docs/docs/20-quickstart.mdx, docs/docs/30-how-to-guides/20-managing-credentials.md, internal/credentials/credentials.go, internal/credentials/credentials_test.go
Fixes #1546 
@jessesuen I promised I'd look specifically for your buy-in, but I think none of what's in this PR should be a surprise based on our offline conversation earlier today.
Best way to review the new strategy -- which diverges from Argo CD's only in small, but meaningful ways -- might be to look at the [doc preview](https://deploy-preview-1552.kargo.akuity.io/how-to-guides/managing-credentials).
@hiddeco I'd value your feedback as well.
@wanghong230 fyi... I saw you found dealing with credential secrets a little clunky the other day. The old strategy was copied from Argo CD, but @jessesuen and I agreed there was no reason we _had_ to copy it, so hopefully these changes address some of the frustrations you experienced.
=> refactor(controller)!: improved cred storage

internal/api/promote_stage_v1alpha1.go, ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/update-freight-alias-modal.tsx
This PR follows up on some changes that were missing in #1561
=> fix(api,ui): bugs resulting from recent service def changes

internal/controller/stages/verification.go, internal/controller/stages/verification_test.go
Fixes #1573
The main cause appears to have been a mix-up in order of parameters.
=> fix(verification): inherit AnalysisTemplate args

api/v1alpha1/stage_types.go, charts/kargo/templates/api/cert.yaml, charts/kargo/templates/api/configmap.yaml, charts/kargo/templates/api/ingress-cert.yaml, charts/kargo/templates/api/ingress.yaml, charts/kargo/templates/argocd/role-binding.yaml, charts/kargo/templates/argocd/role.yaml, charts/kargo/templates/controller/configmap.yaml, charts/kargo/templates/dex-server/secret.yaml, charts/kargo/templates/garbage-collector/configmap.yaml, charts/kargo/templates/management-controller/configmap.yaml, charts/kargo/templates/webhooks-server/configmap.yaml, cmd/controlplane/controller.go, internal/api/config/config.go, internal/api/get_config_v1alpha1.go, internal/api/get_config_v1alpha1_test.go, internal/argocd/namespace.go, internal/controller/promotion/argocd.go, internal/controller/stages/health.go, internal/kubeclient/indexer.go
This cherry-picks #1598 into the `release-0.4` branch.
=> chore(chart): be more careful about undefined values -- 0.4.x edition

charts/kargo/templates/webhooks/webhooks.yaml
=> fix: make stage defaulting webhook run on update

internal/controller/stages/watches.go
#1615 overlooked this particular use of the ownership ref on Freight to the Warehouse that created.
Since #1615, that information is in a field instead.
=> fix: fix freight created event handler

internal/controller/stages/stages.go
This addresses an edge case issue where an existing `VerificationInfo` (from before we started tracking history) could hypothetically disappear.
Follow up on #1638 #1645
=> fix(verify): add existing verification info

cmd/cli/root.go, internal/cli/cmd/config/config.go, internal/cli/cmd/config/get_project.go, internal/cli/cmd/config/view.go, internal/cli/config/config.go, internal/cli/config/config_test.go
=> feat(cli): add more commands to display config

docs/docs/15-concepts.md, docs/docs/30-how-to-guides/15-working-with-freight.md
Addresses part of: #1656
Depends on: #1477
=> chore(docs): document Git subscription filtering

hack/adopt-chart-crds.sh
Follow up on #1671 as suggested in https://github.com/akuity/kargo/pull/1671#issuecomment-2015162352, but a bit smarter.
=> chore(chart): provide CRD adoption script

internal/controller/warehouses/git_test.go
Observed this while reviewing and amending #1477
=> chore(warehouses): use `*testing.T` in sub tests

cmd/controlplane/api.go, internal/api/config/config.go, internal/api/get_analysisrun_v1alpha1.go, internal/api/get_analysisrun_v1alpha1_test.go, internal/api/server.go, internal/api/server_test.go, internal/cli/cmd/server/server.go
Follow up on https://github.com/akuity/kargo/pull/1682#discussion_r1540008282
=> refactor(api): move rollouts setting to server cfg

internal/helm/helm.go, internal/helm/helm_test.go
fixes https://github.com/akuity/kargo/issues/1684.
=> fix: helm chart subscriptions ignore tags that are not semver

ui/src/features/project/project-details/project-details.tsx
=> fix: two race conditions causing DAG bugs

ui/src/features/stage/stage-actions.tsx
=> fix: add indicator to Argo CD deep links

ui/src/features/project/project-details/project-details.tsx, ui/src/pages/project.tsx
=> feat(ui): Move the Create Stage/Warehouse button

docs/docs/50-roadmap.md
Very high-level -- articulate what was achieved in v0.5.0 and what we intend to do in v0.6.0 and beyond.
cc @jessesuen
=> chore(docs): roadmap updates

ui/src/features/common/freight-label.tsx, ui/src/features/common/utils.ts, ui/src/features/freightline/freight-item.tsx, ui/src/features/project/project-details/nodes/repo-node.module.less, ui/src/features/project/project-details/nodes/repo-node.tsx, ui/src/features/project/project-details/nodes/stage-node.module.less, ui/src/features/project/project-details/nodes/stage-node.tsx, ui/src/features/project/project-details/project-details.tsx, ui/src/features/project/project-details/types.ts, ui/src/features/project/project-details/update-freight-alias-modal.tsx
Fixes #1448
Errors UI:
A couple of other small enhancements:
=> feat: surface warehouse reconciliation errors in DAG

docs/docs/20-quickstart.mdx
This cherry-picks #1743 into the `release-0.5` branch.
=> fix(docs): minor fixes to the quickstart -- release-0.5 edition

ui/src/features/project/project-details/images.tsx
=> fix(ui): broken colors in image view

ui/src/features/project/project-details/project-details.tsx
=> fix(ui): could not click dropdown without also opening freight view

ui/src/features/stage/analysis-run-modal.tsx, ui/src/features/stage/verifications.tsx
This PR allows users to preview the live object of the AnalysisRun.
=> feat(ui): AnalysisRun Preview

internal/cli/cmd/get/credentials.go, internal/cli/cmd/get/freight.go, internal/cli/cmd/get/projects.go, internal/cli/cmd/get/promotions.go, internal/cli/cmd/get/stages.go, internal/cli/cmd/get/warehouse.go
Follow-up to #1777 
My apologies that I didn't notice this was missing.
cc @webstradev
=> feat(cli): add --no-header option to applicable cli usage text

ui/src/features/project/analysis-templates/analysis-templates-list.tsx, ui/src/features/project/analysis-templates/preview-analysis-template-modal.tsx
This PR allows users to preview the live object of the Analysis Template.
=> feat(ui): AnalysisTemplate Preview

ui/hack/generate-proto-extensions.mjs, ui/src/features/project/analysis-templates/analysis-templates-list.tsx, ui/src/features/project/analysis-templates/preview-analysis-template-modal.tsx, ui/src/features/stage/analysis-run-modal.tsx, ui/src/features/stage/verifications.tsx, ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts
🍒 cherry-picks:
* #1780
* #1781
* #1784
=> feat: backport analysistemplate and analysisrun views to release-0.5

ui/src/features/project/pipelines/nodes/repo-node.module.less, ui/src/features/project/pipelines/nodes/repo-node.tsx
=> fix: long warehouse urls overflowed

ui/src/features/project/pipelines/nodes/repo-node.tsx
=> fix: long warehouse error messages overflow tooltip 

ui/src/features/common/layout/main-layout.module.less, ui/src/features/common/layout/main-layout.tsx, ui/src/vite-env.d.ts, ui/tests/api/apimachinery.spec.ts, ui/vite.config.ts
=> feat: display version in UI

charts/kargo/templates/users/cluster-roles.yaml, ui/src/features/common/freight-label.tsx, ui/src/features/common/layout/main-layout.module.less, ui/src/features/common/layout/main-layout.tsx, ui/src/features/project/pipelines/nodes/repo-node.module.less, ui/src/features/project/pipelines/nodes/repo-node.tsx, ui/src/vite-env.d.ts, ui/tests/api/apimachinery.spec.ts, ui/vite.config.ts
🍒 This PR cherry picks:
* #1795
* #1797
* #1798
* #1796
* #1799
=> chore: backport recent prs to release-0.5

internal/controller/stages/stages.go, internal/controller/stages/stages_test.go
This PR fixes controller to not record freight verification event during every reconciliation loop by adding flag to check if the verification is performed in current reconciliation loop.
=> fix(controller): record event only when freight verification is performed

internal/controller/promotions/promotions.go
Fixes #1826
@hiddeco I tapped into your re-verification process to trigger re-verification after a successful re-promotion.
=> refactor(controller): do not short-circuit re-promotion to current freight

internal/api/promote_to_stage_subscribers_v1alpha1.go, internal/api/promote_to_stage_subscribers_v1alpha1_test.go, internal/webhook/promotion/webhook.go, internal/webhook/promotion/webhook_test.go
=> feat: ensure Promotion's Stage has promo mechanism

internal/argocd/health.go, internal/controller/promotion/argocd.go, internal/controller/promotion/git.go, internal/controller/warehouses/images.go, internal/credentials/credentials.go, internal/git/git.go, internal/git/git_test.go, internal/webhook/warehouse/webhook.go, internal/webhook/warehouse/webhook_test.go
Fixes #1852
@jessesuen do you think I should PR this to Argo CD also?
Note to self: Backport this to `release-0.5` after it is merged to `main`.
=> fix: rewrite and test git url normalization logic

internal/controller/promotion/argocd.go, internal/controller/promotion/git.go, internal/controller/stages/health.go, internal/controller/warehouses/images.go, internal/credentials/credentials.go, internal/git/git.go, internal/git/git_test.go, internal/webhook/warehouse/webhook.go, internal/webhook/warehouse/webhook_test.go, ui/package.json
=> fix: backport #1854 git url normalization logic to release-0.5

ui/src/features/stage/analysis-run-modal.tsx
=> fix(ui): use YAML response option for AnalysisRun

internal/controller/warehouses/git_test.go
Fixes https://github.com/akuity/kargo/issues/1862
=> chore(controller): extend unit tests for path filtering of Warehouse Git subscription

go.mod, go.sum
Selection of the bit of #1881 that is not related to Kubernetes dependencies.
=> chore(deps): github.com/xanzy/go-gitlab to 0.103.0

internal/cli/cmd/promote/promote.go
=> feat(cli): add `--wait` for `kargo promote`

charts/kargo/templates/users/cluster-roles.yaml
=> fix(chart): add Event permissions for users

internal/controller/management/projects/projects.go, internal/webhook/project/webhook.go
Another follow-up on #1906 and #1909
=> refactor: logging and comments follow up on role mgmt feature

internal/controller/management/projects/projects_test.go, internal/webhook/project/webhook_test.go
=> refactor: test follow-ups on role mgmt feature

api/service/v1alpha1/service.proto
Follow-up to #1906.
I _do_ want these changes merged, however, I have also noted that they have no effect on codegen. In fact, looking at existing generated code, I see that `[json_name = "..."]` on protobuf message fields has _never_ had any effect.
I will open a separate issue for that.
=> refactor: update protobuf defs to avoid snake case

docs/docs/30-how-to-guides/30-managing-user-permissions.md
=> docs: document role management cli commands

ui/src/features/project/settings/components/delete-project-modal.tsx, ui/src/features/project/settings/components/edit-project-modal.tsx, ui/src/features/project/settings/project-settings.tsx, ui/src/pages/project.tsx
=> feat(ui): Project Settings

internal/controller/argocd/api/v1alpha1/audit_events.go, internal/controller/promotion/argocd.go, internal/controller/promotion/argocd_test.go
=> fix(promotions): log event for Argo CD Application

internal/controller/promotion/argocd.go, internal/controller/promotion/argocd_test.go
=> fix(promotions): only check revision match sync result if found

ui/src/features/project/pipelines/pipelines.tsx
=> fix(ui): Manual Approval mode became activated after promotions

charts/kargo/templates/api/cluster-role.yaml, charts/kargo/templates/users/cluster-roles.yaml
There were some missing permissions. I also cleaned things up a bit and documented them better with comments.
=> fix(chart): update and clean up global admin and viewer roles

internal/controller/stages/verification.go
=> feat(stage): carry over message from AnalysisRun

ui/src/features/stage/verifications.tsx
=> feat(ui): surface verification messages

ui/src/features/freightline/freightline-header.tsx, ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/pipelines.tsx
=> feat(ui): Various improvements to Promote Subscribers UX

ui/src/features/project/pipelines/types.ts
=> fix(ui): address infinite refresh issue warehouse

ui/src/features/project/pipelines/types.ts
=> fix(ui): backport infinite warehouse refresh fix from `main` to `release-0.6`

ui/src/features/common/description-expandable.tsx, ui/src/features/common/description.tsx, ui/src/features/common/utils.ts, ui/src/features/freight/freight-details.tsx, ui/src/features/project/analysis-templates/analysis-templates-list.tsx, ui/src/features/project/credentials/credentials-list.tsx, ui/src/features/project/roles/create-role.tsx, ui/src/features/project/roles/roles.tsx, ui/src/features/project/roles/rules-modal.tsx, ui/src/features/project/roles/rules-table.tsx, ui/src/features/stage/stage-details.tsx, ui/src/pages/project.tsx
=> feat(ui): display descriptions for kargo objects (and allow edit/update on certain resources)

ui/src/features/stage/stage-actions.tsx, ui/src/features/stage/stage-details.tsx, ui/src/features/stage/verification-icon.tsx, ui/src/features/stage/verifications.tsx
=> feat(ui): ability to retry verifications from UI 

internal/controller/promotion/git.go, internal/controller/promotion/git_test.go, internal/controller/promotion/helm.go, internal/controller/promotion/helm_test.go, internal/controller/promotion/kustomize.go, internal/controller/promotion/kustomize_test.go, internal/controller/promotion/render.go, internal/controller/promotion/render_test.go, internal/credentials/credentials.go, internal/helm/helm.go
=> fix(promotion): prepare credentials for Helm chart dependency update

.gitignore, go.mod, go.sum, internal/api/server.go, internal/cli/cmd/login/assets/splash.css, ui/package.json, ui/pnpm-lock.yaml, ui/src/app.less, ui/src/features/common/freight-label.tsx, ui/src/features/common/layout/error-boundary.tsx, ui/src/features/common/layout/main-layout.module.less, ui/src/features/common/layout/main-layout.tsx, ui/src/features/common/suspense-spin.tsx, ui/src/features/freight/freight-details.tsx, ui/src/features/freightline/freight-item.tsx, ui/src/features/freightline/freightline-wrapper.tsx, ui/src/features/freightline/freightline.module.less, ui/src/features/freightline/freightline.tsx, ui/src/features/project/pipelines/create-stage-modal.tsx, ui/src/features/project/pipelines/create-warehouse-modal.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/warehouse/warehouse-details.tsx, ui/src/features/stage/stage-details.tsx, ui/vite.config.ts
fixes #1891 
- Add "infinite loader" to Freightline
- Add Gzip compression to UI Dev server
- Add Gzip compression to API server
- Lazy load appropriate components on Pipelines page
- Several smaller enhancements
Before:
After:
=> chore(ui): Improve performance of UI

ui/src/features/freightline/freightline-header.tsx, ui/src/pages/project.tsx
=> chore(ui): vertically compress pipeline page layout (slightly)

ui/package.json, ui/pnpm-lock.yaml, ui/src/features/freightline/freightline-header.tsx, ui/src/features/project/pipelines/pipelines.tsx
=> feat(ui): Filter freightline by warehouse

ui/src/features/project/pipelines/pipelines.tsx
=> fix(ui): refresh freight after manual approval

cmd/controlplane/controller.go
=> fix: graceful failure when rollouts crds are missing

charts/kargo/templates/api/cluster-role.yaml, ui/src/config/paths.ts, ui/src/features/create-freight/artifact-menu-group.tsx, ui/src/features/create-freight/artifact-menu-item.tsx, ui/src/features/create-freight/chart-table.tsx, ui/src/features/create-freight/commit-table.tsx, ui/src/features/create-freight/create-freight.tsx, ui/src/features/create-freight/image-table.tsx, ui/src/features/create-freight/truncated-copyable.tsx, ui/src/features/create-freight/types.ts, ui/src/features/freightline/freightline-header.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx, ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
=> feat(ui): Freight assembly

Tiltfile
This just tidies up the Tilt dashboard a little bit.
=> chore: categorize uncategorized resourced in Tiltfile

internal/controller/management/projects/projects.go, internal/controller/management/projects/projects_test.go, internal/webhook/project/webhook.go, internal/webhook/project/webhook_test.go
Fixes #1654
Supersedes #1667
Special thanks to @isugimpy for doing a lot of the leg work here.
This revises the approach from #1667 slightly by _not_ introducing a new label or annotation to indicate that a Project may adopt an existing namespace. Instead, Projects are permitted to adopt an existing namespace with a name matching their own (as owner _or_ co-owner) as long as the existing `kargo.akuity.io/project` is already set to `true`. This is a simplification as compared even to the existing logic.
The rationale behind _not_ introducing a new label or annotation is that a namespace with label `kargo.akuity.io/project` already set to `true`, no matter how it was created (e.g. by some site-specific controller), has _already_ made clear its intention to be associated with a Project …
=> feat: allow multiple owners of a project namespace

internal/api/refresh_stage_v1alpha1.go
=> fix: refresh promotions using api server's own internal client

ui/src/features/common/promotion-status/promotion-status-icon.tsx, ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/stage/promotions.tsx
=> feat(ui): surface promotion status in DAG nodes

ui/src/features/freightline/freightline.tsx, ui/src/features/project/pipelines/delete-freight-modal.tsx, ui/src/features/project/pipelines/freight-action-menu.tsx
=> feat(ui): ability to delete freight

.github/workflows/release.yaml, cmd/cli/root.go, go.mod, go.sum
We never fully got this to work and now Fig is going away 😢 
This will at least remove a failing job from the release process.
=> chore: remove fig integration

charts/kargo/templates/users/service-accounts.yaml
=> fix(chart): quote subs and groups mapped to service accounts

docs/docs/50-roadmap.md
Adjusted based on current understanding of priorities.
Preview: https://deploy-preview-2122.kargo.akuity.io/roadmap
=> docs: roadmap adjustments

charts/kargo/templates/webhooks-server/cluster-role.yaml
=> fix(chart): add warehouse perms to webhook-server

ui/src/features/stage/promotions.tsx
=> fix(ui): "approved by" -> "created by" for promotions

ui/src/features/common/code-editor/yaml-editor-lazy.tsx, ui/src/features/project/pipelines/warehouse/edit-warehouse.tsx, ui/src/features/project/pipelines/warehouse/warehouse-actions.tsx, ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
=> feat(ui): live manifest viewer from warehouse details

ui/src/features/project/pipelines/nodes/stage-node.tsx
=> fix(ui): incorrect label on hide subscription button tooltip

hack/quickstart/k3d.sh
=> fix: quickstart k3d argo script

ui/src/features/freight/freight-details.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/update-freight-alias-modal.tsx
=> feat(ui): ability to edit freight alias from freight details

ui/src/features/project/pipelines/utils/warehouse-yaml-example.ts
The stage example was updated in https://github.com/akuity/kargo/pull/2188. This updates the Warehouse example
Fixes #1966
=> fix(ui): use ECR nginx image for warehouse example

ui/src/features/common/freight-label.tsx, ui/src/features/freightline/freight-contents.tsx, ui/src/features/project/pipelines/nodes/stage-node.tsx
=> feat(ui): add freight contents to stage node tooltip

internal/argocd/health.go, internal/argocd/health_test.go
=> fix(argocd): mark suspended App as progressing

ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/utils/graph.ts, ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
=> fix(ui): edges for multi-pipelines should not be kinked

ui/src/features/common/utils.ts, ui/src/features/project/list/project-item/project-item.tsx, ui/src/features/project/list/project-item/stage-popover.tsx, ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/utils/use-pipeline-graph.ts, ui/src/features/project/pipelines/utils/useImages.ts, ui/src/features/stage/stage-actions.tsx, ui/src/features/stage/stage-details.tsx
=> fix(ui): deprecation of stage.status.currentFreight

ui/src/features/project/pipelines/pipelines.tsx
=> fix(ui): don't show promote subs button for downstream w/ mult. edges

internal/credentials/kubernetes/ecr/access_key.go, internal/credentials/kubernetes/ecr/access_key_test.go, internal/credentials/kubernetes/ecr/common.go, internal/credentials/kubernetes/ecr/pod_identity.go, internal/credentials/kubernetes/ecr/pod_identity_test.go
ECR also supports OCI Helm repositories.
=> fix(controller): allow oci helm repos to be used with aws creds

ui/src/features/auth/token-renew.tsx
=> fix(ui): redirect to login with expired token

docs/docs/15-concepts.md, docs/docs/20-quickstart.md, docs/docs/50-roadmap.md
This PR brings edge docs up to date for v0.8.0
=> docs: doc updates

ui/src/features/stage/pr-links.tsx, ui/src/features/stage/promotions.tsx, ui/src/features/stage/stage-details.tsx
=> feat(ui): display links in promo table for pr-based promos

ui/src/features/project/pipelines/nodes/stage-node.tsx
=> feat(ui): indicate PR based promotion in Stage nodes

ui/src/features/project/list/project-item/stage-popover.tsx
=> fix(ui): crash in stage details popover

ui/src/features/project/pipelines/pipelines.tsx
=> feat(ui): ability to zoom pipelines dag

README.md, docs/docs/10-overview.md
Updated Youtube video in Readme.md
=> docs: Update README.md

ui/src/features/project/pipelines/utils/graph.ts
=> fix(ui): incorrect DAG rendering for singular forward connection to node with multiple backward connections

ui/src/features/project/pipelines/nodes/stage-node.tsx
=> fix(ui): hide promotion button for control flow stages

ui/src/features/freight-timeline/freight-item.tsx, ui/src/features/freight-timeline/freight-timeline-header.tsx, ui/src/features/freight-timeline/freight-timeline.module.less, ui/src/features/freight-timeline/freight-timeline.tsx, ui/src/features/project/pipelines/freight-action-menu.tsx, ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/types.ts, ui/src/features/project/pipelines/utils/state.ts
=> feat(ui): ability to promote freight via dropdown in timeline

ui/src/features/project/pipelines/images.tsx
=> fix(ui): stop relying on deprecated field in images table

charts/kargo/values.yaml
As discussed in #2338 I added the Azure connector sample for Dex to the `values.yaml` file.
=> docs: Add sample Dex Azure connector.

ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/pages/project.tsx
=> feat(ui): indicate stages with auto promotion enabled in DAG

ui/src/features/common/promotion-status/promotion-status-icon.tsx, ui/src/features/project/pipelines/message-tooltip.tsx, ui/src/features/project/pipelines/nodes/repo-node.tsx
=> fix(ui): scroll promotion status messages (matches warehouse behavior)

internal/controller/promotion/argocd.go, internal/controller/promotion/argocd_test.go
This ensures that even if no specific update is configured for an ArgoCD Application, it will still be "hard refreshed" as long as a promotion mechanism is defined.
=> fix(promotion): always hard refresh ArgoCD App

ui/src/features/project/pipelines/nodes/stage-node.tsx
=> feat(ui): store current freight position in localstorage

internal/controller/promotion/argocd.go, internal/controller/promotion/argocd_test.go
Continuation of #2390, which historically actually had much to do with how #1922 was addressed.
The previous assumptions about there not being a desired source ended up being a red herring. As without updates, this will equal the current source in the Application's spec — resulting in a no-op because this branch _likely_ still equals the source from the previous Promotion-triggered sync result.
The actual working solution, is to always sync the Application when no specific updates are provided, at the cost of idempotency due to Kargo only being aware of the e.g. Git reference (and not the commit SHA) it expects the Application to be synced to.
=> fix(promotion): sync ArgoCD Application without updates

Dockerfile
Noticed a linter complaining about this in another PR.
=> chore: address linter issue `Dockerfile`

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile, Dockerfile.dev, go.mod
=> chore(deps): bump golang from 1.22.5 to 1.22.6

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile, netlify.toml
=> chore(deps): bump Node from 22.5.1 to 22.6.0

.github/workflows/release.yaml
Resolves https://github.com/akuity/kargo/issues/2478
See hash from: https://github.com/actions/setup-go/releases/tag/v5.0.2
=> chore: fix broken nightly release action

ui/src/features/freight-timeline/freight-timeline-header.tsx, ui/src/features/freight-timeline/freight-timeline-wrapper.tsx, ui/src/features/freight-timeline/utils.ts
Fixes #2385
https://github.com/user-attachments/assets/57ede993-0ad7-42a3-8c04-fdfb4824b91e
=> feat(ui): ability to scroll freight timeline with buttons

internal/kubeclient/patch.go
=> fix(kubeclient): retry patch on conflict

Makefile, docs/package.json
@fykaa let me know if these are the sort of things that would have saved you some trouble up front and whether you think you could documents these targets as part of #2491.
=> feat: add convenience targets for working on docs

ui/src/features/freight-timeline/freight-timeline-header.tsx
Came across this issue while exploring UI with Quickstart. Sorry I didn't create the issue first as I think this is a quick fix.
https://github.com/user-attachments/assets/f0b94ea6-8878-4eb9-b7a5-1b88b973db9c
This is a quick and cheap fix but have to check the whole UI layout to find out the scroll leak.
=> fix(ui): jitter scrollbar on hover assemble freight button

internal/directives/git_pr_waiter.go
=> fix(controller): make git-pr-waiter get pr number using correct key

ui/src/features/project/pipelines/pipelines.tsx
fixes https://github.com/akuity/kargo/issues/2603
=> fix(ui): display 0 instead of null when condition is falsy

internal/directives/helm_chart_updater.go, internal/directives/helm_chart_updater_test.go
=> fix(directives): restore Chart.lock on no changes

api/v1alpha1/generated.proto, api/v1alpha1/stage_types.go, charts/kargo/resources/crds/kargo.akuity.io_stages.yaml, ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json, ui/src/gen/v1alpha1/generated_pb.ts
Without this, there can not be any "control flow" Stages.
=> fix(api): loosen Stage validation

internal/api/promote_downstream_v1alpha1.go, ui/src/features/project/pipelines/nodes/stage-node.tsx
Honouring definition of control flow with new promotion template spec
=> fix(ui): downstream promotion

docs/docs/15-concepts.md, docs/docs/20-quickstart.md, docs/docs/35-references/10-promotion-steps.md, docs/docs/35-references/_category_.json
Very much a WIP. Please don't bother reviewing yet. The doc isn't even in the right place in the doctree yet.
@christianh814 @fykaa @nitishfy @dhpup @blakepettersson @jessesuen I thought you might find partially completed, in-very-rough-shape docs more helpful sooner than polished docs later... so have a peek at the preview if you need to learn the built-in promotion steps better.
=> docs: document built-in promotion steps

internal/controller/warehouses/git.go
I noticed while troubleshooting other things that that the Warehouse reconciler, at some point, stopped cleaning up after itself. This PR puts it right.
=> fix: make warehouse cleanup git repos

Makefile
IMAGE_PLATFORMS was being set unconditionally to the empty string.
=> fix: ensure makefile honors IMAGE_PLATFORMS env var

internal/cli/cmd/login/login.go
=> fix(cli): fix auth via --kubeconfig option

Makefile, docs/docs/35-references/10-promotion-steps.md, internal/directives/kustomize_builder.go, internal/directives/kustomize_builder_test.go, internal/directives/schemas/kustomize-build-config.json, internal/directives/zz_config_types.go, kargo-base.apko.yaml, ui/src/gen/directives/kustomize-build-config.json
=> feat(directives): enable Helm plugin for `kustomize-build`

internal/directives/helm_chart_updater.go
=> fix(directives): permit `helm-update-chart` access to Kargo client

internal/controller/warehouses/warehouses.go, internal/controller/warehouses/warehouses_test.go
=> fix(controller): use calculated warehouse requeue interval

internal/controller/promotions/promotions.go, internal/controller/stages/stages.go, internal/kargo/kargo.go, internal/kargo/kargo_test.go
=> fix(promotion): add predicate for abort annotation

internal/controller/promotions/promotions.go
See: https://github.com/akuity/kargo/pull/2760#issuecomment-2418424799
=> chore(promotion): enrich termination msg w/ actor

ui/src/features/common/promotion-directive-step-status/utils.test.ts, ui/src/features/common/promotion-directive-step-status/utils.ts
fixes https://github.com/akuity/kargo/issues/2771
I have refactored the code and added test cases
=> fix(ui): make accurate promotion step status

ui/package.json, ui/pnpm-lock.yaml, ui/src/features/project/pipelines/images.tsx, ui/src/features/project/pipelines/pipelines.tsx
fixes sorting - https://github.com/akuity/kargo/issues/2767
=> fix(ui): sort images by semver

ui/src/features/stage/promotions.tsx, ui/src/features/stage/utils/promotion.test.ts, ui/src/features/stage/utils/promotion.ts
fixes https://github.com/akuity/kargo/issues/2773
=> fix(ui): promotion sorting

internal/controller/stages/stages.go, internal/indexer/indexer.go
This fixes a bug where verification is skipped after a successful promotion if there are other pending promotions waiting to be handled.
=> fix(controller): fix skipped verifications

internal/controller/stages/stages.go
Fixes #2795
A lot of effort went into making sure that pending Promotions did not proceed _before_ any pending verification was complete...
The _implicit_ verification of simply waiting for a healthy state that occurs when verification procedures are not explicitly defined does not leave behind the verification info that we use as a signal that it's safe to proceed with the next Promotion.
=> fix: don't let stages without verifications get stuck

Makefile, docs/docs/40-contributor-guide/10-hacking-on-kargo.md
To avoid conflicts on macOS machines, which may already have an Apple service (AirPlay Receiver) running on port 5000.
=> chore: change local registry port to `:5001`

docs/docusaurus.config.js
addresses: https://github.com/akuity/kargo/issues/2812
cc: @krancour
=> docs: kargo.io in docs site header

README.md, docs/docs/10-overview.md
fixes: https://github.com/akuity/kargo/issues/2823
=> docs: remove GA reference

docs/docs/50-roadmap.md
cc @jessesuen @christianh814 @hiddeco @kencochrane
=> docs: roadmap updates

charts/kargo/Chart.yaml
Since this has been a source of confusion more than once...
=> chore(chart): add version placeholder comments to Chart.yaml

ui/src/app.tsx, ui/src/config/paths.ts, ui/src/features/auth/context/auth-context-provider.tsx, ui/src/features/auth/context/auth-context.tsx, ui/src/features/auth/utils.ts, ui/src/features/common/layout/main-layout.tsx, ui/src/pages/user.tsx
fixes https://github.com/akuity/kargo/issues/2764
=> feat(ui): user info page

internal/api/common.go, internal/api/create_credentials_v1alpha1.go, internal/api/create_or_update_resource_v1alpha1.go, internal/api/create_resource_v1alpha1.go, internal/api/delete_credentials_v1alpha1.go, internal/api/delete_resource_v1alpha1.go, internal/api/get_credentials_v1alpha1.go, internal/api/list_credentials_v1alpha1.go, internal/api/update_credentials_v1alpha1.go
cc @Marvin9 thanks for finding.
=> fix(api): be more thorough with checking if secret management is enabled

docs/docs/30-how-to-guides/20-managing-credentials.md
=> docs: fix typo ecr to gar

docs/docs/35-references/10-promotion-steps.md, docs/docs/35-references/20-expression-language.md
Thanks for spotting this @34fathombelow.
=> docs: fix two small doc mistakes

internal/directives/argocd_updater.go
xref: https://github.com/argoproj/argo-cd/blob/522d07a8d8d50ae68cce4878fd5bc50fe547c611/pkg/apis/application/v1alpha1/types.go#L1102-L1103
=> fix(directives): don't mark App sync as automated

docs/docs/30-how-to-guides/20-managing-credentials.md, internal/credentials/kubernetes/github/app.go
Fixes: https://github.com/akuity/kargo/issues/3055
=> fix(creds): don't require base64 PK for GitHub Apps

docs/docs/35-references/10-promotion-steps.md
=> docs: update retry docs

docs/docs/40-contributor-guide/15-release-procedures.md
closes https://github.com/akuity/kargo/issues/3064
=> fix: broken link

docs/docs/35-references/10-promotion-steps.md, go.mod, go.sum, internal/directives/json_updater.go, internal/directives/json_updater_test.go, internal/directives/schemas/json-update-config.json, internal/directives/zz_config_types.go, ui/src/features/promotion-directives/registry/use-discover-registries.ts, ui/src/gen/directives/json-update-config.json
closes: https://github.com/akuity/kargo/issues/2961
This PR adds json-update promotion step that allows one to automate JSON updates within the Kargo promotion workflows
=> feat: json update promotion step

internal/expressions/json_templates.go, internal/expressions/json_templates_test.go
=> fix(controller): fix tricky expr evaluation cases dealing with quotes and newlines

ui/src/features/freight-timeline/freight-content-item.tsx, ui/src/features/freight-timeline/freight-contents.tsx, ui/src/features/freight/freight-details.tsx
fixes https://github.com/akuity/kargo/issues/2368
=> fix(ui): avoid truncate artifact details unnecessarily

docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md, docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md, docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md, docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/json-update.md
=> docs: tiny nits in promotion step references

docs/docs/60-new-docs/40-operator-guide/40-security/index.md, docs/docs/60-new-docs/40-operator-guide/index.md, docs/docs/60-new-docs/50-user-guide/20-how-to-guides/30-managing-user-permissions.md, docs/docs/60-new-docs/50-user-guide/20-how-to-guides/_category_.json, docs/docs/60-new-docs/50-user-guide/50-security/10-openid-connect.md, docs/docs/60-new-docs/50-user-guide/50-security/index.md, docs/docs/60-new-docs/50-user-guide/index.md, docs/docs/60-new-docs/60-contributor-guide/index.md
This PR adds brief intros to some of the larger sections that have many sub-sections of their own.
=> docs: add intros to some of the larger sections

docs/docs/60-new-docs/50-user-guide/20-how-to-guides/16-working-with-warehouses.md, docs/docs/60-new-docs/50-user-guide/30-patterns/index.md
supersedes https://github.com/akuity/kargo/pull/2963
=> docs: working with warehouses

ui/src/features/project/pipelines/nodes/repo-node.tsx, ui/src/features/project/pipelines/warehouse/warehouse-details.tsx, ui/src/features/project/pipelines/warehouse/warehouse-error.ts
fixes https://github.com/akuity/kargo/issues/2582
removed tooltip and moved the error in details page.
=> fix(ui): warehouse error in details page instead of tooltip

docs/docs/60-new-docs/50-user-guide/20-how-to-guides/16-verification.md, docs/docs/60-new-docs/50-user-guide/60-reference-docs/40-expressions.md
=> docs: expr-lang support for verification args

docs/docs/50-user-guide/60-reference-docs/15-promotion-templates.md, docs/docs/50-user-guide/60-reference-docs/20-promotion-tasks.md
=> fix(docs): indentation and broken href

ui/src/features/stage/stage-details.tsx, ui/src/features/stage/verifications.tsx
fixes https://github.com/akuity/kargo/issues/3483
=> fix(ui): empty freight value in column

ui/src/features/stage/utils/verification-phase.ts, ui/src/features/stage/verifications.tsx
fixes https://github.com/akuity/kargo/issues/3564
=> fix(ui): invalid verification duration

ui/src/features/project/pipelines/graph.tsx, ui/src/features/project/pipelines/nodes/custom-node.tsx
and hide reactflow attributions
=> fix(ui): graph edge glitch

ui/src/features/project/pipelines/context/pipeline-context.ts, ui/src/features/project/pipelines/graph.tsx, ui/src/features/project/pipelines/nodes/custom-node.tsx, ui/src/features/project/pipelines/nodes/freight-label.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
=> feat(ui): hide subscription and fix stage node overflow

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile, Dockerfile.dev
complements https://github.com/akuity/kargo/pull/3629
=> chore(deps): bump golang from 1.24.0-bookworm to 1.24.1-bookworm

ui/src/features/common/truncate-middle.tsx, ui/src/features/freight-timeline/freight-content-item.tsx
introduced in https://github.com/akuity/kargo/pull/3715
=> fix(ui): freight artifact name overflow issue

api/v1alpha1/freight_helpers.go, api/v1alpha1/stage_helpers.go, api/v1alpha1/stage_helpers_test.go, api/v1alpha1/warehouse_helpers.go, api/v1alpha1/warehouse_helpers_test.go
=> chore(backport release-1.3): fix: always honor availability strategy (#3740)

internal/server/get_analysisrun_logs_v1alpha1.go
=> chore: return error if trying to access analysis run logs and not configured

ui/src/pages/downloads.tsx
fixes https://github.com/akuity/kargo/issues/3607
=> fix(ui): windows cli link

ui/src/features/auth/oidc-utils.ts
=> fix(ui): always allow oidc auth code flow over http

docs/docs/50-user-guide/60-reference-docs/50-analysis-templates.md
I think here in order for the verification to pass, you will also need a count.
=> docs: Update 50-analysis-templates.md

ui/package.json, ui/pnpm-lock.yaml, ui/src/extensions/extensions-context.ts, ui/src/extensions/types.ts, ui/src/features/stage/stage-details.tsx
Implementation of UI extensions with one hook in Stage details.
=> feat(ui): Extensions

ui/src/app.tsx, ui/src/config/paths.ts, ui/src/features/settings/analysis-templates/analysis-templates.tsx, ui/src/features/settings/cluster-promotion-tasks/cluster-promotion-tasks.tsx, ui/src/features/settings/cluster-promotion-tasks/create-cluster-promotion-task.tsx, ui/src/pages/settings.tsx
=> feat(ui): Settings redesign

internal/gitprovider/gitlab/gitlab.go
=> fix: remove hardcoded RemoveSourceBranch flag in gitlab gitprovider CreatePullRequest

ui/package.json, ui/pnpm-lock.yaml, ui/src/extensions/extensions-context.ts, ui/src/extensions/types.ts, ui/src/features/stage/stage-details.tsx
This backport needed to be done manually due to merge conflicts.
It's UI stuff, do @rpelczar @Marvin9 it would be great for one of you to validate that I didn't botch this.
=> chore: manual backport of #3835

Makefile, api/v1alpha1/generated.proto, api/v1alpha1/project_config_types.go, charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml, charts/kargo/resources/crds/kargo.akuity.io_projects.yaml, ui/src/gen/api/v1alpha1/generated_pb.ts, ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json, ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Addresses something that went wrong at some point in #3875.
=> fix(api): CEL validation `PromotionPolicy`

ui/src/features/project/list/project-item/project-item.module.less, ui/src/features/project/list/project-item/project-item.tsx, ui/src/features/project/list/project-list-filter.tsx, ui/src/features/project/list/projects-list.tsx, ui/src/pages/projects.tsx
=> feat(ui): Project List Redesign

ui/src/features/freight/freight-details.tsx, ui/src/features/project/settings/views/roles/create-role.tsx, ui/src/features/stage/create-stage.tsx, ui/src/features/stage/create-warehouse/create-warehouse.tsx
=> feat(ui): Drawer views improvements

docs/docs/40-operator-guide/20-advanced-installation/20-advanced-with-argocd.md
Everything's in the PR title :)
=> docs(installation): fix minor typo (double `with`)

ui/src/features/project/pipelines/freight/filter-timerange-utils.ts, ui/src/features/project/pipelines/graph/stack-nodes.ts, ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/promotion/promotion.tsx, ui/src/features/stage/tabs/freight-history/freight-history.tsx, ui/src/features/stage/tabs/freight-history/use-get-freight-map.ts, ui/src/features/stage/verifications.tsx, ui/src/utils/decode-raw-data.ts
- Less timerange option in filters
- white text color when color is used
- promotion manifest in promotion modal
=> chore: pipeline view updates

ui/src/features/project/pipelines/freight/freight-card.tsx, ui/src/features/project/pipelines/freight/freight-timeline.tsx, ui/src/features/project/pipelines/freight/promotion-mode-header.tsx
In this PR, I improved the promotion flow and updated the design for the freight item.
https://github.com/user-attachments/assets/2c46972f-cf70-4d51-bf79-e3186e7d265c
=> feat(ui): Freightline/Promotion UI improvements

ui/src/features/project/pipelines/freight/freight-card.tsx, ui/src/features/project/pipelines/freight/freight-timeline.tsx
https://github.com/akuity/kargo/issues/3984
=> chore(ui): show collapsed freights

docs/docs/50-user-guide/60-reference-docs/15-promotion-templates.md
=> docs: document always(), failure(), and success()

ui/src/features/project/pipelines/freight/freight-timeline-filters.tsx, ui/src/features/project/pipelines/pipelines.tsx
fixes #4011 
More details: https://github.com/akuity/kargo/issues/4011#issuecomment-2863443451
=> fix(ui): Invisible filters cover pipeline view

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
closes https://github.com/akuity/kargo/issues/3919
=> docs: add timeout info to argocd-update step

docs/docs/40-operator-guide/40-security/20-openid-connect.md
Fix docs for the OpenID connector.
=> docs: update 20-openid-connect.md

internal/promotion/runner/builtin/http_requester.go
This condition was already handled a few lines above.
=> chore(controller): remove redundant condition in http step logic

docs/docs/40-operator-guide/40-security/40-managing-credentials.md
Closes https://github.com/akuity/kargo/issues/4027
=> docs: Improve GCP WIF section

ui/src/features/stage/stage-details.tsx, ui/src/features/stage/verifications.tsx
=> fix(ui): App crashes when we open verifications tab

ui/src/features/project/pipelines/freight/freight-timeline.tsx, ui/src/features/project/pipelines/freight/use-promotion-eligible-freight.ts
downstream promotion was showing ineligible freights
=> fix(ui): downstream promotion must be verified in current stage

api/v1alpha1/generated.proto, api/v1alpha1/stage_types.go, api/v1alpha1/warehouse_types.go, charts/kargo/resources/crds/kargo.akuity.io_stages.yaml, charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml, internal/image/selector.go, ui/src/gen/api/v1alpha1/generated_pb.ts, ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json, ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
closes https://github.com/akuity/kargo/issues/3221
=> chore: document accepted values for certain crd fields

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
=> docs: include releaseName field in helm-template example

ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/use-stage-auto-promotion-map.ts
https://github.com/akuity/kargo/issues/4085
=> fix(ui): map promotion policies from projectconfig

ui/src/features/project/pipelines/freight/short-version-utils.ts
https://github.com/akuity/kargo/issues/4116
=> fix(ui): valid short version

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md, internal/promotion/runner/builtin/output_composer.go
closes https://github.com/akuity/kargo/issues/4115
related code: https://github.com/akuity/kargo/pull/3884/files#diff-78fb132e475aea04eed1f2fa339cecbbdea5e1c2398759da40bc02ffe64c3ff3
=> docs: update git-open-pr step

internal/controller/stages/regular_stages.go, internal/rollouts/analysis_run_builder_test.go, internal/rollouts/options.go, internal/rollouts/options_test.go
=> fix(controller): make stage spec.vars referenceable from verifications

docs/docusaurus.config.js, docs/package.json, docs/pnpm-lock.yaml, docs/src/components/Home/index.tsx
This moves from the quite awkward "local search" to the service from Algolia.
It may need some tweaking in the future, but  I count this as a big step forward in terms of actually being able to find things again.
=> docs: switch to Algolia for search

ui/src/features/project/pipelines/nodes/stage-node.tsx
=> fix(ui): Replace icon in stage details button

ui/src/features/freight/freight-status-list.tsx, ui/src/features/project/pipelines/freight/freight-card.tsx, ui/src/features/project/settings/views/credentials/create-credentials-modal.tsx, ui/src/plugins/pr-plugin/deep-link/promotion-step.tsx, ui/src/plugins/pr-plugin/get-pr-link.ts
fixes 
https://github.com/akuity/kargo/issues/3952 
https://github.com/akuity/kargo/issues/4138
https://github.com/akuity/kargo/issues/4171
=> fix(ui): git provider deeplink and cred form schema

ui/src/features/project/pipelines/freight/freight-timeline.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/use-watch-freight.ts, ui/src/features/project/pipelines/use-watch-freights.ts, ui/src/features/utils/cache/freight.ts
fixes https://github.com/akuity/kargo/issues/4173
=> feat(ui): watch freights

internal/controller/stages/regular_stages.go, internal/controller/stages/regular_stages_test.go
=> fix(controller): properly deregister Stage from Freight

internal/webhook/external/github.go, internal/webhook/external/github_test.go
Closes https://github.com/akuity/kargo/issues/4258
=> feat: add ping event support

ui/src/features/auth/jwt-utils.ts, ui/src/pages/user.tsx
fixes https://github.com/akuity/kargo/issues/3818
=> feat(ui): dump all claims from identity token on user details page

ui/src/features/project/pipelines/promotion/freight-details.tsx
https://github.com/akuity/kargo/issues/4170
- Add verified in and approved in stages metadata
- Add freight yaml
- Add alias
=> feat(ui): more freight details in promotion space

ui/src/features/project/pipelines/freight/short-version-utils.ts, ui/src/features/project/pipelines/promotion/freight-details.tsx, ui/src/features/stage/stage-details.tsx, ui/src/features/stage/tabs/freight-history/freight-history.tsx, ui/src/features/stage/tabs/freight-history/use-promotions-by-freight-collection.ts
fixes https://github.com/akuity/kargo/issues/4172
=> feat(ui): freight history improvements

ui/src/features/project/pipelines/graph/use-pipeline-graph.ts
=> fix(ui): convoluted edges for large graphs

charts/kargo/templates/management-controller/deployment.yaml
Updates the label selector used in the management controller deployment to use the `kargo.labels` helper function.
This ensures consistency and proper label application across the chart.
=> fix: Updates label selector in deployment

ui/src/features/assemble-freight/assemble-freight.tsx
=> fix(ui): image annotations in assembled Freight

ui/src/features/project/pipelines/promotion/get-promotion-stage.ts, ui/src/features/project/pipelines/promotion/promotion.tsx
fixes https://github.com/akuity/kargo/issues/4153
=> feat(ui): refresh stage in promotion modal

ui/src/features/stage/utils/index.ts
=> fix(ui): stage colors are not present on freights

ui/src/features/project/settings/views/project-config/project-config.tsx, ui/src/features/project/settings/views/project-config/refresh.tsx
=> feat(ui): refresh ProjectConfig

Dockerfile
=> chore: build w/ `-trimpath` and `-ldflags -w`

charts/kargo/templates/kubernetes-webhooks-server/webhooks.yaml, cmd/controlplane/kubernetes_webhooks.go, internal/webhook/kubernetes/clusterconfig/webhook.go, internal/webhook/kubernetes/clusterpromotiontask/webhook.go, internal/webhook/kubernetes/clusterpromotiontask/webhook_test.go, internal/webhook/kubernetes/freight/webhook.go, internal/webhook/kubernetes/freight/webhook_test.go, internal/webhook/kubernetes/project.go, internal/webhook/kubernetes/project/webhook.go, internal/webhook/kubernetes/projectconfig/webhook.go, internal/webhook/kubernetes/promotion/webhook.go, internal/webhook/kubernetes/promotion/webhook_test.go, internal/webhook/kubernetes/promotion_steps.go, internal/webhook/kubernetes/promotion_steps_test.go, internal/webhook/kubernetes/promotiontask/webhook.go, internal/webhook/kubernetes/promotiontask/webhook_test.go, internal/webhook/kubernetes/stage/webhook.go, internal/webhook/kubernetes/stage/webhook_test.go, internal/webhook/kubernetes/warehouse/webhook.go, internal/webhook/kubernetes/warehouse/webhook_test.go
This PR validates that Stages, PromotionTasks, and ClusterPromotionTasks do not contain any duplicate step aliases.
I've validated this end-to-end in addition to the unit test coverage.
=> feat: validate no duplicate step aliases

internal/webhook/kubernetes/freight/webhook.go, internal/webhook/kubernetes/freight/webhook_test.go
=> fix(webhook): prevent panic on Freight validation

ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/use-stage-auto-promotion-map.ts
fixes https://github.com/akuity/kargo/issues/4288
=> feat(ui): accurate auto promotion label in stages

ui/src/features/assemble-freight/artifact-menu-item.tsx, ui/src/features/assemble-freight/commit-table.tsx, ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx
fixes 
https://github.com/akuity/kargo/issues/4670
https://github.com/akuity/kargo/issues/4665
https://github.com/akuity/kargo/issues/4664
=> feat(ui): warehouse details view improvement

ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/url-params/use-freight-timeline-controller-store.ts
fixes https://github.com/akuity/kargo/issues/4548
=> feat(ui): pipeline filters in URL query

docs/docs/50-user-guide/50-security/30-managing-credentials.md, internal/credentials/kubernetes/github/app.go, internal/credentials/kubernetes/github/app_test.go, internal/credentials/kubernetes/github/app_token_source.go, internal/credentials/kubernetes/github/app_token_source_test.go
Closes #4294 
Supersedes #4606
Draft because I've not yet tested this against actual GitHub.
@fuskovic any change I could ask you to follow the revised docs in this PR to validate that things work as expected whether using client ID or App ID?
=> feat: support client id when authenticating to github as a github app

ui/src/features/common/code-editor/yaml-editor-lazy.tsx
https://github.com/akuity/kargo/issues/4434
=> fix(ui): managedFields visible even if hide managed fields is enabled

internal/promotion/runner/builtin/http_downloader.go, internal/promotion/runner/builtin/http_downloader_test.go
=> chore: address nits `http-download` step

ui/src/features/common/code-editor/yaml-editor-lazy.tsx
caused by https://github.com/akuity/kargo/pull/4725
=> fix(ui): infinite render in yaml view

ui/src/features/assemble-freight/artifact-menu-item.tsx, ui/src/features/assemble-freight/assemble-freight.tsx, ui/src/features/assemble-freight/unique-subscription-key.ts
fixes https://github.com/akuity/kargo/issues/3721
=> fix(ui): assemble multiple Helm chart from same repo

ui/src/features/project/settings/views/credentials/credentials.tsx, ui/src/features/settings/cluster-secret/cluster-secret.tsx
=> feat(ui): fix position of actions in secrets table

internal/image/semver_selector.go
=> fix(image): do not apply lexical sort after semver

ui/src/features/common/analysis-modal/analysis-modal.tsx, ui/src/features/common/code-editor/yaml-editor-lazy.tsx, ui/src/features/common/manifest-preview.tsx, ui/src/features/project/pipelines/promotion/promotion.tsx, ui/src/features/project/pipelines/warehouse/tabs/settings/warehouse-edit-form.tsx, ui/src/features/project/pipelines/warehouse/warehouse-details.tsx, ui/src/features/project/settings/views/analysis-templates/edit-analysis-template-modal.tsx, ui/src/features/project/settings/views/config-maps/upsert-config-maps.tsx, ui/src/features/project/settings/views/general/general-settings.tsx, ui/src/features/project/settings/views/project-config/project-config.tsx, ui/src/features/project/settings/views/promotion-tasks/edit-promotion-task-modal.tsx, ui/src/features/settings/analysis-templates/edit-cluster-analysis-template-modal.tsx, ui/src/features/settings/cluster-config/cluster-config.tsx, ui/src/features/settings/cluster-promotion-tasks/edit-cluster-promotion-task-modal.tsx, ui/src/features/stage/stage-details.tsx, ui/src/features/stage/tabs/settings/stage-edit-form.tsx
we can bring it back if required
=> chore(ui): do not show managedFields

internal/controller/management/projects/projects.go
=> fix: Added `patch` action for promotions in adminRole

internal/credentials/kubernetes/database.go, internal/credentials/kubernetes/database_test.go
Closes: https://github.com/akuity/kargo/issues/4833
=> fix: account for normalization when matching regex to urls

docs/docs/20-quickstart/index.md, docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
Closes https://github.com/akuity/kargo/issues/4754
=> docs: replace `semver` with `constraint`

ui/src/features/project/pipelines/freight/freight-timeline.tsx
fixes https://github.com/akuity/kargo/issues/4221
https://github.com/user-attachments/assets/87956eba-bfd4-4445-a57c-124278f0ed9e
=> feat(ui): auto select relevant warehouse during promotion

pkg/event/freight.go
I accidentally missed renaming this field in #5023
=> fix(event): Fix missing rename

ui/package.json, ui/pnpm-lock.yaml, ui/src/features/common/confirm-modal/confirm-modal.tsx, ui/src/features/common/confirm-modal/use-confirm-modal.tsx, ui/src/features/project/pipelines/freight/freight-card.tsx, ui/src/features/project/pipelines/freight/freight-timeline.tsx, ui/src/features/project/pipelines/nodes/stage-node.less, ui/src/features/project/pipelines/nodes/stage-node.tsx, ui/src/features/project/pipelines/pipelines.tsx, ui/src/features/project/pipelines/promotion/drag-and-drop/dnd-promotion-context.tsx, ui/src/features/project/pipelines/promotion/drag-and-drop/drop-overlay.module.less, ui/src/features/project/pipelines/promotion/drag-and-drop/drop-overlay.tsx, ui/src/features/project/pipelines/promotion/use-manual-approval-modal.tsx
Fixes #4894 
https://github.com/user-attachments/assets/016e8e3f-bd05-4715-8e1b-2481d20a7fd5
=> feat(ui): Drag and Drop Promotion

Makefile
* Some uses of docker now replaced with the variable CONTAINER_RUNTIME.
* Some incorrect whitespace (spaces instead of tabs) in make recipes.
=> fix: makefile syntax changes

pkg/promotion/runner/builtin/git_pr_opener.go
closes https://github.com/akuity/kargo/issues/4952
this pr restores short-circuit logic for git-open-pr step. PR #3884 removed short-circuit logic that checked if a previous execution of the `git-open-pr` step had already opened a PR. That removal was a mistake.
While promotion bookkeeping now tracks which step was last executed, this particular step still benefits from self-checking to avoid unnecessary or duplicate PRs. This commit restores the short-circuit check and its helper function (getPRNumber)
=> revert: re-strengthen short-circuiting logic in git-open-pr step

pkg/controller/stages/regular_stages.go, pkg/controller/stages/regular_stages_test.go
=> fix(controller): avoid infinite loop of failed auto-promotions

pkg/controller/stages/regular_stages.go
Somewhat related to #3016...
The option to keep a Stage perpetually synced to its upstream (#5143) involved relaxing a check that had been the only thing preventing a dramatic increase in the prevalence of the otherwise edge case described in #3016.
This PR conditionally re-strengthens that check.
If auto-promotion is based on perpetually taking the newest Freight, we will not auto-promote if we see _any_ existing Promotion referencing the same Stage and Freight. It is evidence that the Stage has been in that state before, then was manually restored to an older state by a user. We do not want (existing) newer Freight to preempt the user's wishes as described in #3016. _Brand new_ Freight will still auto-promote. This is the stronger check and was the "classic" behavior from before #5143. …
=> fix(controller): improve auto-promotion criteria

pkg/controller/stages/regular_stages.go
This is a very small bit of cleanup I'd intended to tack on to #5151.
This adds a sanity check that searching for available Freight _also_ used immediately upstream does not yield more than one result, as it _should_ be impossible for one upstream Stage to be using more than one piece of Freight from the same origin.
I also added a TODO about a simplification that may be possible after #3016 is addressed.
=> chore(controller): sanity check + slight cleanup of auto-promotion comments
