akuity/kargo

.github/workflows/ci.yaml

Now that Bookkeeper is public, we don't need to be logged into ghcr anymore to pull the Bookkeeper image during the Kargo image build.
This step has actually been failing the last two days anyway, but rather than fix it, I am removing since there's no reason for it anymore.

do not log in to ghcr.io during ci

---

docs/docs/20-quickstart.mdx

This PR fixes an issue @dhpup discovered in the quickstart.
Unbeknownst to me, kind and k3d use different usernames.
I've updated the `PromotionPolicy` resources to grant authority over `Promotion` resources for each `Environment` on the basis of group membership. Users of k3d and kind clusters should mutually belong to the `system:masters` group.

fix permissions issue in quickstart

---

README.md

https://kargo.akuity.io is live now, so this PR updates links in the `README.md`.

update doc links in readme

---

internal/images/image_updater.go
internal/images/image_updater_test.go
internal/images/images.go
internal/images/semver.go

Fixes #313
There are upstream fixes opened related to this as well, but it's unclear how long it will be before we can take advantage of those fixes here.
This PR cribs code from Argo CD Image Updater and Masterminds/semver and makes minimal modifications to correct the root issue.

work around non-deterministic sorts in Masterminds/semver

---

Dockerfile
cmd/cli/main.go
cmd/controlplane/main.go
internal/cmd/cli/root.go
internal/cmd/controlplane/api.go
internal/cmd/controlplane/api_proxy.go
internal/cmd/controlplane/controller.go
internal/cmd/controlplane/root.go
internal/cmd/controlplane/version.go

Part of #262
This commit splits existing cmd into `cli` and `controlplane` to let users communicate with controlplane (API) by CLI.

feat: bootstrap CLI

---

.github/workflows/release.yaml
Dockerfile
Makefile
Tiltfile
internal/version/version.go

Fixes #345
The root cause of the issue is that many build details were previously determined at runtime using `debug.ReadBuildInfo()` and because the `.git/` dir is (rightfully) not present in the container when the `kargo` binary is built, git related details are absent from that `BuildInfo` object.
The resolution is to inject commit ID and tree state using linker flags instead.

fix missing version info in official images

---

api/v1alpha1/environment_types.go
charts/kargo-kit/crds/kargo.akuity.io_environments.yaml
charts/kargo/crds/kargo.akuity.io_environments.yaml
internal/controller/environments/git.go
internal/controller/environments/webhook.go
internal/controller/environments/webhook_test.go
internal/controller/promotions/bookkeeper.go
internal/controller/promotions/bookkeeper_test.go
internal/controller/promotions/git.go
internal/controller/promotions/git_test.go
internal/controller/promotions/promotions.go
internal/git/convenience.go
internal/git/convenience_test.go
internal/git/repo.go

After a lot of analysis and discussion, @jessesuen and I determined that scenarios wherein someone tries to write to a branch that they also subscribe to is the root of many bugs, difficulties, and odd behaviors and simply should neither be shown in our examples -- or even permitted.
This PR addresses that. It breaks down like this:
1. Subscriptions _must_ specify a branch now. It's no longer optional. Previously, when unspecified, it equated to the default branch -- whatever that happened to be. It's become prudent to be more explicit about this because...
1. When a new commit is found, we record what branch the commit was found on. This is important later during promotion because...
1. We look at any commits contained in the new state (freight) for the exact set of manifests or other …

discourage and prevent subscription loops

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

@rbreeze mentioned he thought he saw the old netlify URL somewhere. He was right.
This fixes it.

use our newer/prettier URL in CODE_OF_CONDUCT.md and CONTRIBUTING.md

---

internal/git/repo.go

This fixes a bug that resulted from incompatible changes in #353 and #355 that went unnoticed because they didn't actually manifest as a merge conflict.

fix git reset --hard command

---

docs/docs/20-quickstart.mdx

Fixes #349 
This PR makes the following changes to the quickstart:
* Upgrades to latest, most stable release
* Simplifies the example:
* Subscribes only to an image repo instead of image repo _and_ git repo. Subscribing to a git repo _and_ updating that same repo puts one in a scenario where you _must_ write to a separate, environment-specific branch to avoid forming a loop. This detail is too much to include in a quickstart that is meant to be simple and approachable.
* Promotes from environment-to-environment by moving changes (new image, in this case) from one environment-specific directory to another (and no longer uses other tricks like updating each `Application`'s `targetRevision` field). Again, this is the simplest and most approachable pattern.
* Typos fixed
* New summary section …

simplify and otherwise improve the quickstart

---

go.mod
go.sum

Some Kubernetes types have `protobuf:"-"` tag (same as the `json`) to be skipped from protobuf library. However, these types shows `proto: tag has too few fields` error, since `-` tag is not allowed in current implementation of `gogoproto` - current protobuf library.
This commit silences this error log by using a forked version of gogoproto ([akuity/gogoproto](https://github.com/akuity/gogoproto)), which allows `-` tag.
Related issue: https://github.com/istio/istio/issues/19735

Silence `proto: tag has too few fields` warning

---

internal/api/handler/types_v1alpha1.go

Fixes type mapper panicking when the  `Subscriptions.Repos` is nil.

Check subscription repos nilability before mapping

---

hack/generate-proto.sh

`make codegen` should generate `generated.proto` file from the Kubernetes type definitions. However, the current `codegen` target doesn’t update `generated.proto` file even if there are changes.
This PR fixes this issue by cleaning up directory before generating Kubernetes types proto.

Cleanup directory before generating Kubernetes types proto

---

go.mod
go.sum

The newest Bookkeeper release has more concise commit messages, which leads to a much better signal-to-noise ratio in repo history/logs.

use latest Bookkeeper release

---

.github/workflows/ci.yaml
Makefile

This ensures more consistent linting results across CI and developers running `make lint` (or `make hack-lint`) locally.

make go linting in CI reuse make target

---

internal/api/handler/promote_environment_v1alpha1.go

Fixes promotion failure because of the empty `apiVersion` and `kind`.

Set owner reference typemeta explicitly

---

internal/controller/promotions/git.go
internal/controller/promotions/git_test.go
internal/controller/promotions/helm.go
internal/controller/promotions/helm_test.go
internal/controller/promotions/kustomize.go
internal/controller/promotions/kustomize_test.go
internal/controller/promotions/promotions.go

Fixes #213
This PR updates functions that are involved in applying changes to a Git repo to also return a summary of those changes as a `[]string`.
A new `buildCommitMessage(changeSummary []string) string` function can convert that summary into a nicely formatted commit message.
* If the summary has no items in it, the message is very generic. This really shouldn't happen, but I'm covering my bases.
* If the summary has one item in it, that one item becomes the commit message.
* If the summary has multiple items in it, the first line is very generic and subsequent lines summarize all changes.

improve commit messages for non-bookkeeper cases

---

cmd/controlplane/api.go
internal/api/server.go
internal/config/config.go

This commit updates `Serve` method to take listener as an argument for letting CLI to run API server in the local (user environment) to use with Dashboard or CLI itself.

Update `Serve` method to take listener as an argument

---

docs/docs/15-concepts.md
docs/docs/20-quickstart.mdx

Do not merge until after the `v0.10.0-rc.10` release since there are statements in these doc changes that are currently true only if Kargo was built from source.

update docs for v0.1.0-rc.10 release

---

cmd/cli/main.go
cmd/cli/root.go
cmd/cli/version.go
go.mod
internal/api/option/option.go
internal/cli/env/env.go
internal/cli/env/promote.go
internal/cli/option/flag.go
internal/cli/option/option.go
internal/config/config.go

Resolves https://github.com/akuity/kargo/issues/263
This commit adds environment promotion command to CLI. Since we discussed about launching dashboard in local environment (to utilize user's `KUBECONFIG`), this commit runs API server in local if the `local-server` flag is passed to the command.
Signed-off-by: Sunghoon Kang <hoon@akuity.io>

Add promote command to CLI

---

docs/docusaurus.config.js

- current tag referred to docs.akuity.io

chore: separate analytics for kargo docs

---

charts/kargo/templates/controller/deployment.yaml
charts/kargo/values.yaml
cmd/controlplane/controller.go
internal/config/config.go
internal/credentials/credentials.go
internal/os/env.go
internal/os/env_test.go

Repository credentials (specially formatted Secrets) in Argo CD's namespace already require a special annotation to opt _in_ to being borrowed by the Kargo controller on behalf of a particular project or projects.
This feature takes things a step further and permits the operator who installs Kargo to opt out of credential borrowing behavior entirely.

add option to opt-out of cred borrowing entirely

---

cmd/controlplane/common.go
cmd/controlplane/controller.go

`config.GetConfig()` will honor the `KUBECONFIG` env var as we intended.

fix incorrect call for loading default rest config

---

charts/argocd-kit/templates/argocd/role-binding.yaml
charts/argocd-kit/templates/argocd/role.yaml
charts/argocd-kit/values.yaml
charts/kargo/templates/argocd/role-binding.yaml
charts/kargo/templates/argocd/role.yaml

This PR improves the full `kargo` and `argocd-kit` charts to reduce the breadth of `Secret` reading permissions required by the Kargo controller.
For `argo-kit`, this means that `Secret` reading permissions are granted _only_ for the namespace that Argo CD is installed into and, even then, only if "credential borrowing" is enabled per `argocd.enableCredentialBorrowing`.
The logic for the full `kargo` chart is quite similar, _however_, at present, the Kargo controller gets permission to read `Secret` resources from all namespaces regardless, but this is set to change once #250 is addressed.

chart improvements to require less sweeping permissions to read secrets

---

charts/kargo/templates/webhooks-server/cluster-role-binding.yaml
charts/kargo/templates/webhooks-server/cluster-role.yaml
internal/webhooks/promotions/webhooks.go
internal/webhooks/promotions/webhooks_test.go

With this change, we no longer need special logic in the webhooks to accommodate cases where the namespace controller is cleaning up a deleted namespace.
cc @gdsoumya. I believe we had previously discussed this.

webhooks: remove special authz logic for namespace controller 

---

api/v1alpha1/generated.proto
api/v1alpha1/stage_types.go
charts/kargo-kit/crds/kargo.akuity.io_stages.yaml
charts/kargo/crds/kargo.akuity.io_stages.yaml
pkg/api/v1alpha1/generated.pb.go
ui/src/gen/v1alpha1/generated_pb.ts

Image registry domains, paths, and names may contain a hyphen. Fixes #451 
Regex tests here: https://regexr.com/7gra7

fix(api): allow hyphens in image name and domain

---

README.md
docs/docs/10-overview.md
docs/docs/15-concepts.md
docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
docs/docs/30-how-to-guides/20-managing-credentials.md

This is a comprehensive overhaul of the docs to account for all breaking changes that have occurred since rc.10.
This includes the change from `Environment`s to `Stage`s and the decreased dependence on `PromotionPolicy` resources, and increased reliance on RBAC and the virtual "promote" verb.
The Netlify preview of the changes is probably the most convenient way to review this.

bring docs up to date

---

cmd/controlplane/controller.go

This is a remnant from when the webhooks were served by the controller. (And even the webhooks don't interact directly with RBAC types anymore, so this code is doubly deal. 👋 )

removed unused rbac api from controller schema

---

internal/helm/helm_test.go

I can't see any reason to revisit this, so it's no longer a TODO.
Also, since Kargo now has an oci-based chart repo of its own, we can use that for the test instead of referencing another project.

fix todo in helm chart subscription tests

---

internal/api/handler/get_stage_v1alpha1_test.go
internal/api/handler/list_stages_v1alpha1_test.go
internal/api/handler/promote_stage_v1alpha1_test.go
internal/kubeclient/transport_test.go

Let's prefer using `context.Background()` over `context.TODO()` in test code. The latter creates the impression there is something in need of fixing when there really isn't anything to fix.

fix use of context.TODO() in tests

---

charts/kargo/templates/controller/deployment.yaml
charts/kargo/values.yaml
cmd/controlplane/controller.go
internal/controller/applications/applications.go
internal/controller/applications/applications_test.go
internal/controller/common.go
internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go

I anticipate some follow-ups to this, but this works.
cc @gdsoumya: I think this PR is of particular interest to you.
__Edit:__ More details...
This PR mainly involves updates to each of the three reconcilers.
1. Stages: The reconciler only watches Stages labeled as this controller's responsibility
1. Promotions: The reconciler only watches Promotions labeled as this controller's responsibility
1. Argo CD Applications: The reconciler still watches all Applications that it can see, but the index of "Stages by Application" is now "Stages labeled as this controller's responsibility by Application." (There are reasons this is possibly unnecessary, but it seemed like a quick, easy, and reasonable safeguard.)
Additionally, if and when the Stages reconciler creates a Promotion (auto-promotion), …

low-level sharding support in the controller

---

.dockerignore

This speeds up the execution of `make hack-build` by quite a bit if you're like me and have a `docs/` directory chock full of `node_modules`.

add docs/ to .dockerignore

---

Dockerfile.dev

I rely on `Dockerfile.dev` to provide the correct versions of different tools we use.
The containerized analog to `make codegen` (`make hack-codegen`) has bee broken lately because it was lacking Node.js and pnpm, both of which are required for the TS/JS code generation steps.
This PR fixes this.

add nodejs and pnpm to Dockerfile.dev

---

internal/kubeclient/auth.go

Every time I look at this function I need to refresh my memory on how it actually works...
Adding a comment to spare myself some future effort.

add comments to kubeclient.GetCredential func

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Makefile

Fixes #501
`make build-cli` will cross-compile the CLI for any OS and CPU architecture.
`make hack-build-cli` will cross-compile the CLI for any OS and CPU architecture _inside a container_.
In either case, the OS and CPU architecture default to those of the _host_ machine.
In CI the process, we build the CLI just once to validate there are no compilation errors.
In the release process, we invoke `make build-cli` six times for six common OS/arch combinations. All of these get uploaded to the release page.

add CLI build to CI and release processes

---

go.mod
go.sum
internal/cli/config/config.go
internal/cli/config/config_test.go
internal/cli/login/login.go

Part of #482 
No matter how you log in, this saves server address, a token, and, if applicable, a refresh token in a local configuration file.
The token could be any of:
* An ID token issued by an OIDC provider
* An ID token issued by the Kargo API server itself
* A bearer token gleaned from local kubeconfig
In all cases, we treat the token the same. i.e. Even ID tokens will (in a future PR) be _used_ as bearer tokens when interacting with the Kargo API server. This is not technically a correct thing to do, but there is widespread precedent for it.

cli: persist bearer and/or refresh tokens in ~/.kargo/config on login

---

internal/api/option/auth.go
internal/api/option/auth_test.go
internal/kubeclient/auth.go

Related to #508
I have observed that when we use `kubeclient.GetCredential()` to glean the Kubernetes bearer token from the current Kubeconfig, the result returned includes the prefix `"Bearer "`.
This can even be seen in the config that is saved upon login in #508:
```console
cat ~/.config/kargo/config
apiAddress: http://localhost:30081
bearerToken: Bearer <redacted>
```
Since I don't want to store an _HTTP header_ and want to store _just the token_, I need to strip the "Bearer " prefix from the header value at the end of `kubeclient.GetCredential()`.
If we strip it there, we _also_ have to put it back before using it -- hence the complementary changes in the `option` package.
In the end, this is cleaner because awareness of how to format the header correctly is built into the components …

strip/add "Bearer " prefix when reading/setting auth header

---

internal/cli/config/config.go
internal/cli/config/config_test.go

This is a slight refactor of recent changes from #508.
I had anticipated cases where I might try to load config and find that none existed and proceed _without_ an error, but I am not finding any such case. Since that isn't required, this approach is more straightforward.

slight refactoring of config.LoadCLIConfig() func

---

internal/cli/login/login_test.go

Fixes #517 
This PR fixes the flaky `TestRandStringFromCharset` test by updating the charset used to the default value.

fix: fixes random string generation test

---

charts/kargo/templates/api/service.yaml
charts/kargo/values.yaml

Lacking this feature has presented a barrier to a meaningful installation in a real cluster.

chart: make api service configurable

---

Tiltfile
charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/api/ingress.yaml
charts/kargo/templates/api/service.yaml
charts/kargo/templates/dex-server/configmap.yaml
charts/kargo/values.yaml

This adds an option to include an Ingress resource in the chart installation.
I found myself having to add an ingress manually earlier today and figured we should just square it away here.

chart: add option to create ingress resource

---

charts/kargo/templates/garbage-collector/cron-job.yaml

This setting was incorrectly nested under the job template and was causing a warning on install.
This PR fixes it.

chart: fix concurrency policy for gc cron job

---

charts/kargo/templates/api/ingress-cert.yaml
charts/kargo/templates/common/cert-issuer.yaml

#540 was missing some templates that are needed when API ingress with a self-signed cert is enabled.

chart: fix missing cert resource for ingress

---

charts/kargo/templates/api/deployment.yaml

This is the only case where we inject secrets into env vars.
This is the common approach to replace pods with new ones having updated env vars any time the underlying secret changes.

chart: bounce api server when secret changes

---

Tiltfile
charts/kargo/templates/dex-server/deployment.yaml
charts/kargo/templates/dex-server/secret.yaml

Dex connector config is extremely likely to contain OIDC client secrets.
We're better off storing this fragment of configuration in a `Secret` than a `ConfigMap`.

chart: put dex config in a secret

---

charts/kargo/values.yaml

This is a follow-up to #541 to simplify instructions for how to BYO certs.

chart: clean up cert-related comments in values.yaml

---

.dockerignore

This speeds up local builds of the image a lot by sparing us hundreds of MBs of context transfer.

add ui/node_modules to .dockerignore

---

ui/src/config/transport.ts
ui/vite.config.ts

We're deciding **_not_** to prefix the Connect routes with `/api` due to the consequences described [here](https://connectrpc.com/docs/go/routing/#prefixing-routes):
> Unfortunately, grpc-go clients don't support prefixes: if you need to support gRPC clients, don't prefix your routes!
(basically with prefixing we would no longer be a gRPC server). This PR updates UI behavior to use standard/unprefixed gRPC/Connect route locations.
The UI seems to be working now in a real env:
@rbreeze @rpelczar - I blindly made the vite.config.ts changes, so they are untested.

fix: UI should use standard Connect routes

---

Tiltfile

#540 split `api.address` into two fields -- `api.protocol` and `api.host` -- and the port number was mistakenly dropped from the Tiltfile at that time. This PR puts it back.

Tiltfile: fix api.host value set when rendering chart

---

api/v1alpha1/promotion_types.go
api/v1alpha1/stage_types.go
internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/kubeclient/patch.go

Closes https://github.com/akuity/kargo/issues/564
Conflict modification errors are happening because reconcilers are using stale objects from the informer to make updates. There are several ways to deal with it. Initially, I attempted to use non-cached clients that read promotions directly from the informer, however, it would require a big refactoring. Unfortunately, I could not find any easy way to conditionally disable the cache .
I've realized that conflict errors are happening due to frequent status updates. So it is safe to "force" update status using patch.

fix: use patch to make stage/promotion status changes to avoid conflict errors

---

cmd/cli/root.go
cmd/controlplane/api.go
internal/api/config/config.go
internal/api/option/option.go
internal/api/server.go

This is a tiny bit of refactoring to include the `LocalMode` field in the server config object instead of passing around a loose boolean.
I have an upcoming PR that will start passing config objects to funcs that are already receiving the loose `localMode` boolean. The two feel redundant and function signatures end up much tidier this way.
There are no functional changes in this PR.

refactor: make localMode part of server config

---

.golangci.yaml

This rule is giving me trouble in some other branches and doesn't seem sensible.
Early returns make code _more_ readable by eliminating conditionals.
Limiting the number of early returns from a function is not a good idea.

linting: adjust revive rules

---

internal/api/option/auth.go
internal/cli/client/token_refresher.go

I've just discovered that service account tokens can be JWTs that don't expire, so we need to account for that when checking if a token the CLI is holding in its configuration is expired or not.

cli: account for jwts that don't expire

---

charts/kargo/templates/api/deployment.yaml
internal/api/config/config.go
internal/api/handler/admin_login_v1alpha1.go

This PR adds the `AUD` (audience) claim to the JWTs issued as admin account ID tokens.
Outside of OIDC, `AUD` is optional, but this claim adds useful information about the token's intended use, so it's good to set it.

add AUD claim to admin tokens

---

charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/dex-server/secret.yaml

Up until now, when Dex is in play, we've used a hard-coded client ID `kargo` for public clients (Kargo CLI or SPA).
Since the OIDC spec says the client ID _must_ appear in the `AUD` claim of an ID token, Dex is  putting `kargo` in that claim. This isn't right in our case because the OIDC spec also says _access tokens_ must use the `AUD` claim to indicate the resource server(s) the token gives access to. Like Kubernetes, Kargo uses ID tokens _as_ access tokens. Resource servers _must_ verify that they are the intended audience of the token they receive.
We can satisfy both conditions by setting client ID to the Kargo API server's configured hostname. By doing so, Dex uses that as the value of the `AUD` claim and the token then contains correct information about its intended use:
e.g. As an …

fix AUD claim on IDP-issued tokens

---

charts/kargo/templates/api/deployment.yaml
internal/api/config/config.go
internal/api/handler/admin_login_v1alpha1.go
internal/api/option/auth.go
internal/api/option/auth_test.go

Up until now we've been using a hard coded value `kargo` in the `ISS` (issuer) claim of ID tokens issued for the admin account.
This is not technically a correct thing to do as it bears insufficient information about the provenance of the token and that matters when the token is presented back to the API server by the client. We use the `ISS` claim to decide which logic to apply to properly verify the token. (i.e. Verify it as an admin token, a token from an OIDC identity provider, or a SA token issued by Kubernetes.)
Making this change will prevent a Kargo API server from attempting to verify admin tokens clearly issued by _other_ Kargo API servers. (fwiw, that verification would fail anyway as long as both servers used different signing keys, but we probably should not take it for …

fix ISS claim on admin tokens

---

api/v1alpha1/promotion_types.go
api/v1alpha1/stage_types.go
charts/kargo/templates/controller/cluster-roles.yaml
internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/kubeclient/patch.go

Reverts https://github.com/akuity/kargo/pull/589, which reverted  https://github.com/akuity/kargo/pull/567.
But additionally adds `patch` privileges to `kargo-controller` 
```yaml
- apiGroups:
- kargo.akuity.io
resources:
- stages/status
- promotions/status
verbs:
- update
- patch  # <<< added
```

fix(controller): use patch to make stage/promotion status changes to avoid conflict errors

---

ui/src/features/project/project-details/project-details.tsx

Currently, we have this error: 
It is caused by creating a new Transport that doesn't inject the token.

fix(ui): Use created Transport on WatchStages query

---

go.mod
internal/controller/promotions/argocd.go
internal/controller/promotions/argocd_test.go

I found it a bit tedious to exactly match the authorized stage by the exact name. I would like to make the UX easier so that users can allow all stages in a project using a glob wildcard. e.g.:
```yaml
metadata:
annotations:
kargo.akuity.io/authorized-stage: kargo-demo:*
```
Or even:
```yaml
metadata:
annotations:
kargo.akuity.io/authorized-stage: '*:*'
```

feat: support wildcards in kargo.akuity.io/authorized-stage annotation

---

api/v1alpha1/stage_types.go
charts/kargo-kit/crds/kargo.akuity.io_stages.yaml
charts/kargo/crds/kargo.akuity.io_stages.yaml
internal/api/types/v1alpha1/types.go
internal/controller/promotion/composite.go
internal/controller/promotion/composite_test.go
internal/controller/stages/stages.go
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json

Fixes #622
Built on top of #628
Merge after #628 and only review commits starting with df73a4ed4e7e7c96435cabb9d0023021308c7603
This works by removing the constraint that all Stages must have one or more promotion mechanisms defined.
It makes this possible:

control flow stages

---

.github/governance.yml

We were conspicuously missing labels for area/garbage-collector and, more importantly, area/crds -- since we should pay very close attention to PRs that update CRDs.

add component labels to governance bot

---

charts/kargo/templates/api/secret.yaml
charts/kargo/values.yaml

We should allow users to supply the bcrypt hash of the password instead of the plaintext password in the values.yaml. Since the hash is safe to store in plaintext/git but a password is not.
Additionally, the `bcrypt` function is not hermetic/stable/gitops-friendly and so if user uses password, every time user applies the helm chart, they will get a different hash. But supplying a hash **_is_** hermetic and wouldn't change between applies.

feat: support supplying bcrypt hash of admin password

---

api/v1alpha1/stage_types.go
charts/kargo-kit/crds/kargo.akuity.io_stages.yaml
charts/kargo/crds/kargo.akuity.io_stages.yaml
internal/controller/applications/applications.go
internal/controller/promotion/argocd.go
internal/controller/stages/argocd.go
internal/kubeclient/indexer.go
internal/webhook/stage/webhook.go
internal/webhook/stage/webhook_test.go
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json

The Stage's argocd application namespace (typically `argocd`) currently:
1. is required that it be specified
2. and if left unspecified, we will default the value to that of the Stage namespace
The issue I have with this is:
1. application namespace is generally not a concern for end users (in the default and most common operation mode of Argo CD).
2. the correct namespace will be more commonly `argocd` instead of the Stage's namespace
3. an admin should be able to change this centrally, without touching everyone's stages
4. the defaulting behavior done by our webhook, will cause problems with GitOps (because this is a list field)
This PR makes it such that:
1. we don't default the namespace in the webhook
2. we will choose to use ARGOCD_NAMESPACE if unspecified
3. and if ARGOCD_NAMESPACE …

feat: argocd app namespace is optional and not defaulted

---

internal/controller/applications/applications.go
internal/controller/options.go
internal/controller/promotions/promotions.go
internal/controller/stages/stages.go

Partially resolves https://github.com/akuity/kargo/issues/656
Depends on https://github.com/akuity/kargo/pull/650
If a promotion function panics, we will fail the promotion rather than crash the controller, and the promotion will have a proper message and phase:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Promotion
metadata:
creationTimestamp: "2023-09-06T21:11:10Z"
generation: 1
name: dev.01h9p5bczmwqj1z5hhf6880p8f.e9b3b60
namespace: kargo-guestbook
ownerReferences:
- apiVersion: kargo.akuity.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: Stage
name: dev
uid: 32626a1f-c00f-468a-8e76-d1a0d83e7920
resourceVersion: "127330362"
uid: 5482cac2-16ed-4f5f-ad55-2d3a4e5c8db7
spec:
freight: e9b3b603e17ea2e291535b605a58c2e62f1949be
stage: dev
status:
error: 'runtime error: …
```

fix: don't crash controller on reconcile panics

---

ui/src/features/stage/available-freight.tsx

In my case, `healthCheckCommit` was not populated in my availableFreight and so the link was wrong.

ui fix: link to repo url was incorrect

---

ui/src/features/stage/promotions.tsx

Fixes wrong variable names in promotions live update implementation.
The `isLoading` check is required because react effect depends on it . I still need to have `promotionsResponse` check to make sure data was loaded and did not crash due to error
https://github.com/akuity/kargo/blob/e3c340e51f1f9aabd5989917272f9b58d6429653/ui/src/features/stage/promotions.tsx#L31

fix: correct incorrect naming in promotions live update implementation

---

api/v1alpha1/stage_types.go
charts/kargo-kit/crds/kargo.akuity.io_stages.yaml
charts/kargo/crds/kargo.akuity.io_stages.yaml
internal/controller/stages/git.go
internal/controller/stages/git_test.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json

Stores git commit message in freight so we can show it in the UI
```yaml
availableFreight:
- commits:
- branch: main
id: 5c7d29985412024a39dff4b0286bf9eb3f2a0450
message: 'feat: remove github workflow to render manifests'
repoURL: https://github.com/jessesuen/guestbook-deploy.git
firstSeen: "2023-09-07T22:48:07Z"
id: 4e1f65309798525de29191ea734ea4f980f07b43
images:
- gitRepoURL: https://github.com/jessesuen/guestbook/tree/v0.0.6
repoURL: ghcr.io/jessesuen/guestbook
tag: v0.0.6
```

feat: add commit message to Freight metadata

---

internal/controller/applications/applications.go
internal/controller/applications/applications_test.go
internal/controller/stages/argocd.go

I noticed that stages were inexplicably being modified/reconciled. Digging deeper, I found that we refreshed stages whenever there was a change to Applications.
Since apps are very churny, we should only refresh a stage if the app changes sync or health status. This PR adds a predicate to prevent unnecessary stage reconciliations, by only processing apps if health or sync status changes.
NOTE: it's incorrect to rely on sync status for Freight health. I filed a separate issue https://github.com/akuity/kargo/issues/670 for this.

feat: reduce unnecessary stage reconciles with app predicate

---

internal/controller/stages/argocd.go
internal/controller/stages/argocd_test.go

Fixes #670 
If applicable, this still checks whether an App is "synced," but it's based solely on revision and not on sync state.

evaluate whether an App is synced only on basis of revision

---

ui/src/features/project/project-details/project-details.tsx

Closes https://github.com/akuity/kargo/issues/716
The second attempt to fix flapping freight ids. The bug was happening because the code assumed that  `client.setQueryData` happens instantaneously. In reality, is takes a few milliseconds so data is calculated wrong when events are received too quickly.

fix: freighs are flapping during promotion

---

internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go

In my project, I have a control-flow Stage used to promote simultaneously to all downstream Stages. However, currently it requires I create promotion jobs to get freight into that history. It doesn't make sense for me to kick off a bunch of promotion jobs for control-flow stages that are essentially no-ops for getting freight into history. I simply want all availableFreight to be immediately become promotable to downstream.
This PR does the following:
1. A stage with no promotion mechanisms copies all availableFreight into history, and marks them all as qualified.
2. If, for some reason, a promotion job was run against a control-flow stage (which is technically something we should try and prevent in API), it will act as a no-op instead of muck around with the Stage's history.

feat: qualify all availableFreight in control-flow stages

---

ui/src/features/freightline/freightline.tsx

fix(ui): return to normal freightline after clicking promote YES button

---

ui/src/features/project/project-details/nodes/repo-node.module.less
ui/src/features/project/project-details/nodes/repo-node.tsx
ui/src/features/stage/stage-actions.tsx
ui/src/features/stage/subscriptions.tsx
ui/src/utils/url.ts

https://github.com/akuity/kargo/assets/7262558/786cc2dd-c347-41e5-95bb-a5779c651d7d

feat(ui): more linkage

---

.gitignore
Makefile

codegen fails if `zx` (and other dev-time dependencies?) isn't already installed in `ui/node_modules`.
This PR fixes that.

fix codegen process

---

internal/cli/client/client.go
internal/cli/client/token_refresher.go
internal/cli/client/token_refresher_test.go
internal/cli/config/config.go
internal/cli/login/login.go

cli: persist --insecure-skip-tls-verify option in config if specified during login

---

Tiltfile
charts/kargo/templates/api/cert.yaml
charts/kargo/templates/api/configmap.yaml
charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/api/ingress.yaml
charts/kargo/templates/api/service.yaml
charts/kargo/templates/dex-server/secret.yaml
charts/kargo/values.yaml
internal/api/config/config.go
internal/api/server.go

This fixes #548 
As noted in the issue, this covers cases where Ingress is not used or Ingress _is_ used and company policy requires TLS end-to-end. (I guess those people should have service meshes, but you never know. 🤷 )
TLS with a self-signed cert is also enabled _by default_ so users who ignore installation options still start off on more secure footing.

enable API server to use TLS natively (without ingress)

---

charts/kargo/templates/api/deployment.yaml

If OIDC/Dex are disabled and no custom kubeconfig is specified, but TLS is used for the API server, you can end up with a volume containing the certs, but the corresponding `volumeMount` will be missing.
This PR uses the same conditional for both.

chart: fix missing volumemount

---

internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go

Whether a Stage's available Freight are marked as qualified or not is not supposed to matter. (And doesn't.) Qualification in an immediately upstream Stage is a _pre-req_ for making it _into_ that collection to begin with.
It can, however, spark confusion if available Freight are marked as unqualified. Is it available or isn't it?
This PR ensures that available Freight _always_ will appear qualified. They are.
The flip-side of this is that Freight is now explicitly _disqualified_ when it is promoted to be a Stage's _current_ Freight.

keep all available freight qualified

---

internal/cli/get/get.go

Before:
```shell
kargo get stages --project kargo-demo            
NAME   AGE
uat    121m
test   122m
```
After:
```shell
kargo get stages --project kargo-demo
NAME   CURRENT FREIGHT                            HEALTH    AGE
test   b73f9d1afaca87254b64e64e5439557e86dcba79   Healthy   123m
uat    b73f9d1afaca87254b64e64e5439557e86dcba79   Healthy   121m
```
We need this if we're to have a CLI-centric quickstart. See #721
Long-term, idk about using this package for printing tables. It was nothing but pain.

cli: add special table printer for stages

---

docs/docs/20-quickstart.mdx

This is an all new quickstart!
Fixes #721
Key changes:
1. CLI-centric instead of `kubectl`-centric
1. Removes auto-promotion: As with @jessesuen's webinar, which did not involve any auto-promotion, I feel that leaving this out provides a better introduction to the concepts. We do mention that auto-promotion is possible.
1. Explains more of what is going on behind the scenes
1. Steps for promoting to uat and prod are removed since they are markedly similar to the initial step for promoting into test. These second and third promotions are left to the user as a suggested exercise. This goes a long way toward shortening the quickstart.
Note to reviewers: I suggest viewing the Netlify preview and validating that you are successful following this.

all new quickstart

---

cmd/cli/root.go

Fixes #812
The issue is that the CLI was unconditionally creating a k8s client, but that is only needed when using the `--local` flag.
Moving instantiation of the client within the conditional solves the problem.

cli: fix broken auto-completion

---

.github/workflows/release.yaml
cmd/cli/root.go
go.mod
go.sum

@rbreeze iirc, you're a Fig fan.

release process: publish fig autocomplete spec for kargo CLI

---

charts/kargo/templates/api/cluster-role.yaml

Fixes #811
OpenShift enables certain, more restrictive admission controllers that are not enabled by default on other k8s distros.
This change should make promotions work on OpenShift and shouldn't have any adverse impact if you're _not_ running on OpenShift.
Many thanks to @tal-hason for finding this issue.

chart: fix api server permissions to work on openshift

---

docs/docs/40-contributor-guide/10-hacking-on-kargo.md

Makes links of things that should have been and weren't.
Mentions that cert warnings can be safely ignored.
Adds mention of UI -- didn't exist when this was last touched.
Fixes CLI build instructions, which were incorrect.

update contributor docs

---

docs/docs/20-quickstart.mdx

This PR is meant to fix the small mixup of `kustomize` and `kargo`, described in #840

docs: Fixes mentioning of 'kustomize edit set image'

---

docs/docs/20-quickstart.mdx

Fixes #837         
Added more instructions for the CLI installation involving download of release package and adding system's `PATH` environment variable.

improved CLI installation instructions in quickstart

---

internal/controller/promotion/argocd.go

Fixes #874
Create namespace option (among others) wasn't being honored when Kargo programmatically syncs an App.

fix app syncing to account for syncpolicy/options

---

.github/workflows/stale.yml

On weekdays, this workflow will run once in the morning*. If an issue of `priority/low` or `priority/wontfix` has been inactive for 90 days, it will be marked as stale (by adding the `stale` label), and a comment will be left. If it remains inactive for another 30 days, it will be closed (but can be re-opened if needed, i.e. not locked).

ci(stale): add scheduled workflow

---

docs/docs/20-quickstart.mdx

fix(docs): update commands for mac x86

---

docs/docusaurus.config.js

resolves #923 
Not terribly familiar with how to generate these docs but this request seemed trivial enough.
I wasn't able to find instructions in the repo for how to build/generate the docs, so any pointers are very welcome.

feat(docs): Add Discord link to header

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

These same changes were applied to Kargo Render earlier today in the course of trying to work out permission issues that were partly caused by that repo's recent rename (from bookkeeper).
This allows us to delete some of our Action secrets in favor of a per-execution username/secret that GH Actions manages _for_ us. The updated versions of Actions we use are in order to take full advantage of that.

improve ci and release processes

---

CODEOWNERS

Swapping individuals with teams in CODEOWNERS to avoid spamming everyone with emails on each PR.
Also closes #959

chore: use teams instead of individuals in CODEOWNERS

---

.github/workflows/release.yaml

This _should_ fix the step that opens a PR with fig completion info upon release.
The old config was copied from https://github.com/withfig/push-to-fig-autocomplete-action#usage and appears to be incorrect.
New config comes from the fig doc site:
https://fig.io/docs/guides/integrating/push-to-autocomplete-action

fix fig step in release.yaml

---

internal/controller/warehouses/git.go
internal/controller/warehouses/helm.go
internal/controller/warehouses/images.go

This fixes a bug in the Warehouse reconciler that was creating freight that _always_ has a number of images, a number of git commits, and a number of charts, _each_ equal to the total number of subscriptions -- and most of those will be zero values. This is both confusing to look at and also causes problems at promotion time.

warehouse bug fix

---

internal/controller/stages/stages.go
internal/controller/stages/stages_test.go

Fixes #992
In the process of fixing this, I broke syncing for normal Stages and control flow Stages into two separate functions since the sync behavior for the two is increasingly disparate.

fix stage qualifications for flow control stages

---

.github/workflows/release.yaml

We need to add permissions for OIDC for nightly cli builds.
Fixes: https://github.com/akuity/kargo/actions/runs/6661699931/job/18105128095
cc: @krancour

fix: add permissions for nightly cli build

---

cmd/controlplane/controller.go
internal/cli/stage/promote.go
internal/controller/promotions/promoqueues.go
internal/controller/promotions/promoqueues_test.go
internal/controller/promotions/promotions.go
internal/controller/promotions/promotions_test.go
internal/controller/promotions/watches.go
internal/controller/runtime/queues.go
internal/controller/runtime/queues_test.go
internal/controller/stages/stages.go
internal/controller/stages/watches.go
internal/kargo/kargo.go

This change refactors the promo controller to support long lived promotions as well as make it more reactive to completions of other promos on the stage.
Changes:
1. PromoteFn is called during normal Reconcile() instead of background go routine
2. Reconcile() is a no-op for promos that are already terminal, or is not their turn to run
3. If no promotions for a stage is currently running, Reconcile() will only allow the highest priority promo to reconcile (based on creationTimestamp and name). All others will be a no-op
4. Reconcile() allows any Promotion that is already Running to continue to run. This set us up for long-lived promotions (to be implemented in future PR).
5. PriorityQueue has a Peek() function
6. PriorityQueue ignores nil objects if pushed
7. PriorityQueue is a no-op if …

feat(promo): support long-lived promotions and improve reactiveness

---

docs/package.json
docs/yarn.lock

This PR updates docusaurus to 2.4.3, if this works, we can follow up with an upgrade to 3.x. I wanted to do this in steps since 3.x has backward-incompatible changes that will require changes and is a risker upgrade.

Updated docusaurus to 2.4.3

---

docs/docs/10-overview.md
docs/docusaurus.config.js
docs/package.json
docs/plugins/gtag/package.json
docs/plugins/gtag/tsconfig.client.json
docs/plugins/gtag/yarn.lock
docs/yarn.lock
netlify.toml

This upgrades the docs to version 3.0.0. I'm not sure if it is fully working correctly. The "Allow cookies" banner doesn't seem to be working, so we will need to fix that before we merge. @krancour maybe you can take a look and see if you know what is causing the issue.

Upgrade the docs to Docusaurus version 3.0.0

---

docs/docs/15-concepts.md
docs/docs/20-quickstart.mdx

Fixes #988
This PR reworks the quickstart and concepts documentation for v0.2.0.
__This should not be merged until after v0.2.0 is released or else this change will break the quickstart.__

update docs for v0.2.0

---

internal/kargo-render/render.go

This is a follow-up to #1109.
I'm not sure how it was that I ever observed #1109 working correctly. All Kargo Render CLI invocations now fail.
The issue is that once `cmd.Env` for the child process exec'ing Kargo Render becomes non-nil (as it did starting in #1109), the child process no longer inherits its parent's environment -- the Go docs say so:
```golang
// Env specifies the environment of the process.
// Each entry is of the form "key=value".
// If Env is nil, the new process uses the current process's
// environment.
// If Env contains duplicate environment keys, only the last
// value in the slice for each duplicate key is used.
// As a special case on Windows, SYSTEMROOT is always added if
// missing and not explicitly set to the empty string.
Env []string
```
This causes `PATH` …

fix error invoking kargo render

---

.github/workflows/release.yaml

🤦 I did not realize that the CLI images were built in a container.  The container by default does not include the awscli.
Fixes: https://github.com/akuity/kargo/actions/workflows/release.yaml?query=event%3Aschedule

chore: add awscli for nightly build

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

A counterpart to #1096 so there's parity between local containerized tests and CI / release processes.

upgrade golang image used in ci and release processes

---

.github/workflows/ci.yaml

Make CI run for:
- Any PR, regardless of target branch (since we sometimes PR to other branches now)
- Merge queue trigger -- again, regardless of target branch (merge queue not enabled yet in repo settings)
- Post-merge for branches that looks like they're for maintenance of older releases

update ci triggers

---

go.mod
go.sum
internal/controller/runtime/queues_test.go

The priority queue doesn't grow when one adds a duplicate key.
Sometimes we were getting unlucky and the random names we generated for queue elements weren't entirely unique.
This was sometimes causing an assertion about the queue's depth to fail.
This PR stops using names generated from the moniker library and starts using UUIDs as unique "names" instead:
1. They're guaranteed unique
2. UUIDs are partly random, so we know we're not accidentally building a queue that's already ordered. i.e. We can still assert the queue reorders itself by priority.

fix flakey priority queue test

---

ui/src/features/project/project-details/nodes/repo-node.module.less
ui/src/features/project/project-details/nodes/repo-node.tsx
ui/src/features/project/project-details/nodes/stage-node.module.less
ui/src/features/project/project-details/nodes/stage-node.tsx
ui/src/features/project/project-details/project-details.tsx

Improvements:
- Too long warehouse name truncated
- Fixed styles in the warehouse node view (the border-bottom is not visible)
- Added truncating styles to the repo link instead of characters limitation (chars have different widths, so sometimes the link has two lines)
- Aligned health status in the stage node view
Before:
After:

fix(ui): Node view styles improvements

---

.github/workflows/release.yaml

Remove ACL permissions for Kargo nightly CLI build.

chore: remove ACL permissions for Kargo Nightly CLI

---

go.mod
go.sum
internal/cli/config/config.go
internal/cli/config/config_test.go

The `github.com/ghodss/yaml` package is no longer actively maintained. There are numerous inquiries about the project's status on its issue tracker: https://github.com/ghodss/yaml/issues. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
Since `sigs.k8s.io/yaml` was already a dependency before this pull request was made, we can remove 1 extra dependency by replacing `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`.

chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

---

internal/controller/stages/stages.go
internal/controller/stages/watches.go
internal/kubeclient/indexer.go

Fixes #1157
This PR indexes Stages by Warehouse. Whenever new Freight is created, a new event handler finds Stages subscribed to the Warehouse that created the Freight and enqueues them for reconciliation.
This makes Stages that subscribe directly to Warehouses far more responsive.
There is a tiny bit of renaming of existing event handlers in this PR. I've added two in the past two days and wanted to adopt a different naming convention that seems it can be applied consistently as the number of handlers likely grows.
cc @tal-hason

on new freight, enqueue subscribed stages

---

ui/src/features/freightline/freightline.tsx
ui/src/features/project/project-details/nodes/stage-node.tsx

fix(ui): clarify why freight is available for promotion

---

ui/package.json

Vite serves the UI during development only, so this has no bearing on anything but devx.
Making vite bind to 0.0.0.0 instead of 127.0.0.1 only makes it possible to run vite in a container without affecting the ability to run it as a native process.

make vite bind to 0.0.0.0

---

cmd/controlplane/api.go
internal/api/kubernetes/client.go
internal/api/kubernetes/client_test.go
internal/api/option/auth.go
internal/api/user/user.go

This is a follow-up to #1190, which forgot to make the API server's authorizing kube client wrapper evaluate the SAs in admin-designated namespaces for suitability.
@devholic you know this part of the code well, so I'm hoping you can do the review for this one. 🙏

make authorizing client wrapper check all admin-designated namespaces for SA mappings

---

.github/workflows/lint-pr.yaml

This should make it easier for generating release notes, noting breaking changes, and being organized

chore: enforce conventional commit messages on PR titles

---

internal/image/repository_client.go
internal/image/repository_client_test.go
internal/image/tag_selector_ghcr_test.go

fix(controller): make tag selector ignore references in an oci image index that don't look like they refer to an image

---

.dockerignore
Dockerfile
Tiltfile
hack/tilt/ui.yaml

I had a lot of conversations with @rbreeze last week about reasons he typically opts to run Kargo components as native processes instead of a local cluster. It was enlightening and inspired me to fix everything that was slowing Tilt down.
If using Tilt to develop in a local cluster, this PR will make image builds faster overall, achieve sub-second restarts on every component, and the UI component will even be live updated as code changes.
How it works:
1. Two new stages are added to the Dockerfile. These two new stages are not involved in the official image that is built and published by our release process. They are only for facilitating local development, and the differences between them and the stage that produces the official image are minor.
There is one new stage for the back end …

chore(devx): make tilt crazy fast

---

internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/warehouses/warehouses.go
internal/kargo/kargo.go
internal/kargo/kargo_test.go

Currently when someone clicks refresh on a Stage, Warehouse, we get two reconciles:
1. first reconcile happens because refresh annotation was set by kargo-api
2. second reconcile happens because controller patches the objects annotation to clear the refresh annotation
This introduces a predicate which will filter out the event if the update event was to clear the annotation, preventing the second reconcile.

fix: eliminate double reconcile during refresh requests

---

ui/src/features/project/project-details/nodes/repo-node.tsx
ui/src/features/project/project-details/project-details.tsx
ui/src/features/project/project-details/types.ts

Fixes #1202 (for real this time 🙂)

fix: refresh freightline after warehouse completes refresh

---

docs/docs/10-overview.md
docs/docs/15-concepts.md
docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
docs/docs/30-how-to-guides/20-managing-credentials.md
docs/docs/40-contributor-guide/10-hacking-on-kargo.mdx
docs/docs/40-contributor-guide/20-signing-commits.md
docs/docs/40-contributor-guide/30-code-of-conduct.md
docs/docs/40-contributor-guide/index.md
docs/docs/50-roadmap.md

Added SEO changes to Kargo docs
In short:
- meta title is inherited from the first H1 of the document
- `sidebar_label` exists only in the context of navigating through the docs
- `description` serves as metadata description and should be a bit longer (55+ chars)

docs: Metadata changes

---

docs/docs/10-overview.md

This fixes an error that is stopping the docs site from building.
I'm not sure if this is somehow related to the issue @rbreeze is currently looking at, but this needs to be fixed either way.

fix(docs): error in overview page front matter

---

ui/src/features/freightline/freight-item.tsx
ui/src/features/freightline/freightline.module.less
ui/src/features/project/project-details/nodes/stage-node.module.less
ui/src/features/project/project-details/nodes/stage-node.tsx
ui/src/features/project/project-details/project-details.tsx

feat(ui): highlight appropriate stage when hovering freight and vice versa

---

internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/warehouses/warehouses.go

fix(controller): ensure warehouses and running promotions are routinely re-reconciled

---

ui/src/features/stage/promotions.test.ts
ui/src/features/stage/promotions.tsx
ui/src/features/stage/utils/sort.ts

Fixes https://github.com/akuity/kargo/issues/1037
@jessesuen In the issue above, you mentioned adding a special section in the UI for currently running promotions. This seems like a separate issue to me, but I'm happy to keep the above issue open if you prefer to track it there

fix: sort promotions with running and pending first

---

internal/controller/promotion/helm.go
internal/controller/promotion/helm_test.go

fix(controller): when updating a values.yaml, make sure image tags that look like a number are still treated as strings

---

ui/src/app.tsx
ui/src/config/auth.ts
ui/src/config/paths.ts
ui/src/config/transport.ts
ui/src/features/auth/context/auth-context-provider.tsx
ui/src/features/auth/context/auth-context.tsx
ui/src/features/auth/oidc-login.tsx
ui/src/features/auth/protected-route.tsx
ui/src/features/auth/token-renew.tsx
ui/src/features/project/project-details/project-details.tsx
ui/src/features/stage/promotions.tsx

Fixes #877 
In this PR, I implemented a refresh token exchange.
How it works: when the token is expired before any API call, the user is redirected to the token renewal page, where the loader is visible for a second, and after the token exchange process, the user is redirected to the previous page.
The perfect solution is a request in the background, but unfortunately, we can't use React hooks inside the interceptor for now (library limitations), which is needed for our auth flow.

feat(ui): Refresh token exchange

---

internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/warehouses/warehouses.go
ui/src/features/project/project-details/project-details.tsx
ui/src/features/stage/promotions.tsx

fix(ui): hovering on a DAG node would highlight other nodes with same freight

---

docs/docs/50-roadmap.md

A bit of roadmap cleanup:
* Present what's behind us in the past tense
* Defer things not accomplished in v0.3.0 to v0.4.0
* Clarify where we currently are on the roadmap
* Minor formatting improvements

chore(docs): update roadmap

---

cmd/cli/main.go
internal/cli/client/client.go
internal/cli/cmd/config/set.go
internal/cli/cmd/config/unset.go
internal/cli/cmd/create/project.go
internal/cli/cmd/delete/project.go
internal/cli/cmd/delete/stage.go
internal/cli/cmd/delete/warehouse.go
internal/cli/cmd/get/freight.go
internal/cli/cmd/get/projects.go
internal/cli/cmd/get/promotions.go
internal/cli/cmd/get/stages.go
internal/cli/cmd/get/warehouse.go
internal/cli/cmd/update/freight-alias.go
internal/cli/config/config.go
internal/cli/config/errors.go

Fixes https://github.com/akuity/kargo/issues/1341
Currently, the CLI entrypoint and some commands assumes that the config file exists in the home directory. So all commands and config-related commands (e.g. `config set`, `config unset`) are failing if the config file does not exist.
This commit fixes this issue by returning an default config if the config file does not exists in the CLI entrypoint and creates the config file if necessary in config-related commands.

fix(cli): handle CLI config file not found error

---

ui/src/features/freightline/freight-contents.tsx
ui/src/features/freightline/freight-item.tsx

Fixes #830
If there are 2+ freight items, a vertical scrollbar appears and users can scroll through every item (the scroll bar disappeared for the screenshot):

fix(ui): Freightline items overflow with 2+ items

---

internal/credentials/credentials.go
internal/credentials/credentials_options.go
internal/credentials/credentials_test.go

As kubernetesDatabaseConfig has private vars, envconf didn't fill their content from defined env vars

fix: configuring kubernetesDatabaseConfig with env vars

---

Dockerfile

kargo-rencer rc.34 introduced significant changes to the `kargo-render.yaml` file structure.
The underlying error I am trying to work around is:
```
Error: error loading Kargo Render configuration from repo: error normalizing and validating Kargo
Render configuration: error validating Kargo Render configuration:
branchConfigs.0.appConfigs.testservice.configManagement: Must validate one and only one schema (oneOf);
branchConfigs.0.appConfigs.testservice.configManagement: Additional property path is not allowed;
branchConfigs.0.appConfigs.testservice.configManagement.helm: Additional property valueFiles is not allowed
```
I believe this is because my `kargo-render.yaml` file is set up to work with rc.34, but kargo is still importing rc.33.

chore: Update to kargo-render v0.1.0-rc34

---

api/v1alpha1/stage_types.go
api/v1alpha1/warehouse_types.go
charts/kargo/crds/kargo.akuity.io_stages.yaml
charts/kargo/crds/kargo.akuity.io_warehouses.yaml
internal/controller/git/git.go
internal/controller/promotion/git.go
internal/controller/warehouses/git.go
internal/controller/warehouses/git_test.go
internal/controller/warehouses/warehouses.go
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json

Fixes #1224
I verified this against gitea in a local cluster with ingress and a self-signed cert.
Worked as expected.
cc @geowalrus4gh, I think you were looking for this.

feat(controller): support git repos with self-signed cert

---

docs/docs/20-quickstart.mdx

This is leftover from when the quickstart used to borrow a secret from Argo CD.
The quickstart no longer demonstrates that behavior, so the field removed by this PR was a useless detail and a distraction.

fix(docs): remove superfluous detail from quickstart

---

cmd/cli/root.go
internal/cli/cmd/approve/approve.go

feat(cli): add command for manually approving freight for a stage

---

cmd/cli/root.go
cmd/cli/version.go
internal/cli/cmd/apply/apply.go
internal/cli/cmd/create/create.go
internal/cli/cmd/delete/delete.go
internal/cli/cmd/get/get.go
internal/cli/cmd/login/login.go
internal/cli/cmd/refresh/refresh.go
internal/cli/cmd/stage/stage.go
internal/cli/cmd/update/update.go

refactor(cli): restrict common flags to subcommands branches where they're applicable

---

go.mod
go.sum
internal/logging/context.go
internal/os/env.go

Changes:
1. Introduces an env var `KLOG_LEVEL` which will set the Kubernetes integer log level for the go-client. This is often necessary to debug issues, such as https://github.com/akuity/kargo/issues/1414
2. Calls `sigs.k8s.io/controller-runtime/pkg/log` `SetLogger` to silence the `log.SetLogger(...) was never called; logs will not be displayed.` error.
Example output of `KLOG_LEVEL=7`:
```
INFO[0000] Starting Kargo Controller                     commit= version=devel+unknown.dirty
I0124 11:33:23.520710   98235 loader.go:395] Config loaded from file:  /Users/jesse/.kube/config
I0124 11:33:23.523716   98235 loader.go:395] Config loaded from file:  /Users/jesse/.kube/config
I0124 11:33:23.524361   98235 round_trippers.go:463] GET …
```

fix: add KLOG_LEVEL to set kubernetes logging level

---

docs/docs/40-contributor-guide/10-hacking-on-kargo.mdx

When attempting to get Kargo up and running following the Quickstart documentation I ran into the following error when running the kargo login command as specified in the docs:
`Error: error retrieving public configuration from server: unavailable: http: server gave HTTP response to HTTPS client`
I have also confirmed that the config is note actually save properly when this error occurs so it seems to defintely be an issue.
Once I resolved that by changing https -> http, I ran into one more issue because the Kargo UI was not available at the specified URL, (https://localhost:30081) it was only available at http:localhost:30082). Looking through the code a bit this seems to make sense and just be an error in the documentation.
However, I'm brand new to the project so please point out …

fix(docs): Fix incorrect login command & UI url

---

ui/src/features/project/project-details/project-details.tsx

This reverts #1423 / commit ce84805cfa7eb99be8864b87367e3bdae1b9fb84.
#1423 blindly cherry-picked a small fix from `main` without realizing that there were _other_ things needed from `main` in order for it to work. #1423 therefore created a new bug.
We've since discovered that synchronously refreshing the freightline after Warehouse sync is not the improvement we're really looking for, regardless. Since the Warehouse refresh is carried out asynchronously by the controller, there is no guarantee of a synchronously refreshed freightline showing any new Freight.

fix(ui): undo #1423 -- release-0.3

---

internal/kubeclient/indexer.go

I found that if there is an error launching an AnalysisRun, it is possible for `stage.Status.CurrentFreight.VerificationInfo` to be non-nil, while `tage.Status.CurrentFreight.VerificationInfo.AnalysisRun` _is_ nil.

fix(controller): add another nil check in stages by analysis runs indexer

---

charts/kargo/templates/management-controller/cluster-roles.yaml
charts/kargo/templates/webhooks-server/cluster-role.yaml
charts/kargo/templates/webhooks/webhooks.yaml
internal/controller/management/projects/projects.go
internal/controller/management/projects/projects_test.go
internal/webhook/project/webhook.go
internal/webhook/project/webhook_test.go

Fixes #1415 
#1388 began creating the namespace associated with a Project asynchronously as part of Project reconciliation.
Although rarely encountered, it became possible for creation of resources _in_ the Project's namespace to fail because the Project was not yet reconciled for the first time.
This change absolves the Project reconciler of responsibility for namespace creation and makes that task the responsibility of the Project validation webhook. This webhook used to at least check for availability of the namespace, but now it creates it. Namespace creation is synchronous now, which eliminates the potential for the failure described.

refactor: create project namespaces synchronously

---

cmd/cli/root.go
internal/cli/cmd/dashboard/dashboard.go

This should close #549 .
Just to note this will not work in development when using tilt (it won't break but it will open the API Url which in the Tilt method is not currently the URL for the dashboard).

feat(cli): Add kargo dashboard command

---

internal/api/common.go

#1388 removed the API server's permissions to create and delete namespaces.
This is now done indirectly via Project resources instead.
With this in mind, having the API server prioritizing namespace creation over creation of other resources doesn't make sense.
The choices are either:
* Restore the API server's permission to create namespaces so the special treatment makes sense again.
* Remove this special treatment.
I've chosen the latter, because I think it's a good thing that the API server (the component with the most attackable surface area) doesn't have that powerful permission.

refactor: no special treatment for ns in api server apply

---

charts/kargo/templates/webhooks-server/cluster-role.yaml
internal/webhook/project/webhook.go
internal/webhook/project/webhook_test.go

Fixes #1443
Draft because this is built on top of #1417, which should be merged first.
```
If the namespace exists:
If it's already owned by the Project:
Done
If it's labeled like a Project and not already owned by anything else:
Project adopts it
If the project label is not present on the namespace or the namespace has an existing owner:
Conflict
```

feat(webhook): allow legacy project ns to be adopted by project when created

---

internal/controller/warehouses/images.go
internal/controller/warehouses/images_test.go
internal/controller/warehouses/warehouses.go
internal/controller/warehouses/warehouses_test.go

Over the course of other recent PRs, variables and functions involved in the Warehouse reconciler's selection of commits and charts have been changed to avoid use of the term "latest," which can be misleading, since user-defined selection criteria often results in selection of a commit or chart that is _not_ the most recent.
This PR applies similar name changes to variables and functions involved in the Warehouse reconciler's selection of container images.
There are no functional changes in this PR. This is purely for readability and clarity of code.

chore(controller): change image selection func and variable names for clarity

---

internal/controller/stages/stages.go

Fixes a nil pointer dereference that @gdsoumya discovered.
These some controller managers can be nil when Argo CD and/or Argo Rollouts integrations are disabled. In those cases, we don't need the corresponding watches anyway.

fix(controller): add new nil checks in stages reconciler initialization

---

internal/controller/stages/stages.go

Sometimes the controller cache for stages is stale and doesn't show updated result of a promotion leading to a situation where CurrentFreight is nil temporary and so it sets the phase as NotApplicable. But in reality the CurrentFreight is already updated in live state but because the controller has now patched the phase as not applicable any future reconciliations completely skip the verification step as phase doesn't match the required value.

fix: stage reconciler failures if cache is stale

---

charts/kargo/templates/management-controller/cluster-roles.yaml
internal/controller/management/projects/projects.go
internal/controller/management/projects/projects_test.go
internal/webhook/project/webhook.go

Since #1431 we rely on a webhook to create Project namespaces synchronously. Although this was a valid decision made for well-documented reasons, one undesired side-effect has been difficulty bootstraping Kargo with a default Project already in place:
* If the Project is applied before the webhook registration, Project creation succeeds, but creation of the underlying namespace does not take place. If the manifests contain additional resources that belong in that namespace, their creation will fail.
* If the webhook registration is applied before the Project, Project creation will fail since the webhook server isn't running yet. Creation of the underlying namespace does not take place and, as above, if the manifests contain additional resources that belong in that namespace, their …

refactor: make management controller able to create project namespaces again

---

docs/docs/15-concepts.md
docs/docs/30-how-to-guides/15-working-with-freight.md
docs/docs/30-how-to-guides/20-managing-credentials.md

General doc updates covering major changes in v0.4.0 and other miscellaneous fixes. Quickstart updates in a separate PR. 
Highlights:
* Document Project CRD
* Remove PromotionPolicy CRD docs / combine with Project CRD docs (PromotionPolicy is no longer a top-level type)
* Be more clear about the _two_ ways Freight can become qualified for promotion to a Stage -- verification upstream or manual approval (Changed in v0.3.0, but there were bits of doc we didn't update thoroughly enough.)
* Remove docs re: Argo CD "credential sharing"

docs: update concepts and how to sections for v0.4

---

Makefile

On an AMD64 system, `uname -m` will return `x86_64` instead of the Go accepted `amd64`. Detect when this is returned (or provided), and overwrite it with the correct value.
This ensures the `build-cli` Make target actually works on AMD64 Linux systems.

fix: transform uname arch into valid Go arch

---

api/v1alpha1/stage_types.go
api/v1alpha1/warehouse_types.go
charts/kargo/crds/kargo.akuity.io_stages.yaml
charts/kargo/crds/kargo.akuity.io_warehouses.yaml
internal/credentials/credentials.go
internal/credentials/credentials_test.go
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json

Fixes: #872
This adds support for connecting to Git repositories over an (insecure) HTTP wire as described in https://github.com/akuity/kargo/issues/872#issuecomment-1761972854, while taking into account the effect it would have on HTTP Helm repositories as observed in https://github.com/akuity/kargo/issues/872#issuecomment-1956378143.
Effectively, this means that connecting to any HTTP endpoint is now allowed as long as this does not require authentication. This includes "classic" Helm repositories served over HTTP, where basic authentication used to be supported in the past.

feat: allow connecting to HTTP Git repositories

---

docs/docs/50-roadmap.md

v0.4.0 was overly ambitious in scope. Factors like company off-site, PTO, and technical challenges imposed a dose of reality.
This PR proposes partially re-purposing v0.5.0 to further the objectives of v0.4.0 and to play catch up on things like UI.
It makes a commitment to design/proposal work for extensible promotion mechanisms in the v0.5.0 time frame, but defers implementation to v0.6.0.
@jessesuen @christianh814 let's connect offline about all of this.

docs: update roadmap

---

docs/docs/20-quickstart.mdx

Before a release, I usually recruit help to validate, among other things, that the updated quickstart works flawlessy against a release candidate.
This, unfortunately, requires reviewers to be aware of which parts of the quickstart may require small tweaks. As a for instance, one cannot install the "latest" version of the Kargo chart, because Helm counts something like `v0.4.0-rc.1` as pre-release and will only install it if you explicitly request it. The commands are buried in a script, which needs to be downloaded and modified instead of simply curl|bash'ed...
It's a pain, frankly.
I'm trying something different this time, for the convenience of all who help to validate this. I've updated all those little things _for you_ in a temporary commit that I will remove before this PR gets …

docs: update quickstart for v0.4

---

cmd/cli/version.go
internal/cli/option/flag.go
internal/cli/option/option.go

Fixes: #1511 
This adds support for supplying a `--client` flag to `kargo version`, which avoids the command from attempting to collect version information from the API server.
```console
$ kargo version --client
Client Version: devel+unknown.dirty
```
In addition, the order of collecting information has been adjusted to allow partial information to be printed when the API server can not be reached before returning an error.
```console
$ kargo version
Client Version: devel+unknown.dirty
Error: get version info from server: unavailable: dial tcp [::1]:30081: connect: connection refused
$ kargo version --output yaml
apiVersion: kargo.akuity.io/v1alpha1
cli:
buildTime: "2024-02-22T11:18:51Z"
compiler: gc
gitTreeDirty: true
goVersion: go1.21.3
platform: linux/amd64
version: …
```

feat(cli): add `--client` flag to `kargo version`

---

charts/kargo/templates/management-controller/cluster-roles.yaml
charts/kargo/templates/webhooks-server/cluster-role.yaml

Fixes #1513
In two places, an RBAC rule like this was used in an attempt to constrain creation of RoleBindings _only_ to ones named `kargo-api-server-manage-project-secrets`.
```
- apiGroups:
- rbac.authorization.k8s.io
resources:
- rolebindings
name: kargo-api-server-manage-project-secrets
verbs:
- create
```
`name` was the wrong field name. I was looking for `resourceNames`. 🤦‍♂️ 
After attempting the following, I've now learned that resource _creation_ (and deletion) can not actually be constrained by resource name:
```
- apiGroups:
- rbac.authorization.k8s.io
resources:
- rolebindings
resourceName:
- kargo-api-server-manage-project-secrets
verbs:
- create
```
This PR just removes this constraint instead and that fixes the installation warnings.
cc @christianh814

fix(chart): warnings in chart install/upgrade

---

api/v1alpha1/stage_types.go

Fixes issue @christianh814 reported to me offline.
Example Stage:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
name: test
namespace: kargo-demo
spec:
subscriptions:
warehouse: kargo-demo
promotionMechanisms:
gitRepoUpdates:
- repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
writeBranch: stage/test # Write to stage-specific branch
render: {}
argoCDAppUpdates:
- appName: kargo-demo-test
verification:
analysisTemplates:
- name: kargo-demo
```
Error when applying:
```
Error from server (Invalid): error when creating "kargo.yaml": Stage.kargo.akuity.io "test" is invalid: spec.promotionMechanisms.gitRepoUpdates[0].render.images: Invalid value: "null": spec.promotionMechanisms.gitRepoUpdates[0].render.images in body must be of type array: "null"
```
The `render` …

fix(crds): stage validation issue with kargo render promo mechs

---

api/v1alpha1/stage_types.go

Cherry-picking the bug fix from https://github.com/akuity/kargo/pull/1519 into `main`.

fix(crds): stage validation issue with kargo render promo mechs (#1519)

---

Dockerfile.dev
Makefile

Fixes #1506 
This addresses an issue observed on Linux systems where files written to mount paths would end up being owned by root, or files could not be read because they were _not_ owned by the container's user.
It is achieved by creating a user within the development image with the same UID and GID as the caller on the host, while ensuring mount target paths do exist for this user and group before the container starts.
This effectively makes the `hack-build-cli` target work while also delivering smoother operations with `hack-codegen`.
In the future, we should likely rethink the way we work with tooling dependencies and their versions. As this problem was harder to tackle due to the `codegen` target performing system-global installations.

fix(devx): mount permission issues on Linux

---

internal/cli/option/kubernetes.go

This fixes an issue @jessesuen discovered wherein kubeconfig is getting caught up in `kargo create`, `apply`, and `delete` reading bytes from files.
This fix is quick and dirty due to its urgency. It works, but there is no test coverage.
I will improve this in a follow-up and worry about getting this into `main` later.

fix(cli): don't involve kubeconfig in reading bytes from files

---

docs/docs/30-how-to-guides/15-working-with-freight.md
internal/cli/cmd/update/freight.go
internal/cli/cmd/update/update.go

xref: https://github.com/akuity/kargo/issues/1163#issuecomment-1966752230
This refactors the `kargo update freight-alias` command to `kargo update freight`, to avoid it accepting multi-positional arguments while simultaneously aligning it with other commands like `kargo create`, `kargo delete` and `kargo refresh`.
Effectively, this means that instead of running:
```shell
kargo update freight-alias --project=my-project abc123 my-new-alias
```
one should now run:
```shell
kargo update freight --project=my-project abc123 --alias=my-new-alias
```
As Freight besides the alias is immutable, this may still not be perfect as it _could_ imply other updates can be facilitated as well. However, it is the best "uniform" alternative I could think of at the moment when comparing it to other existing …

refactor(cli)!: change `update freight-alias` command to `update freight`

---

cmd/cli/root.go
go.mod
internal/cli/cmd/apply/apply.go
internal/cli/cmd/approve/approve.go
internal/cli/cmd/config/config.go
internal/cli/cmd/config/set_project.go
internal/cli/cmd/create/create.go
internal/cli/cmd/create/project.go
internal/cli/cmd/dashboard/dashboard.go
internal/cli/cmd/delete/delete.go
internal/cli/cmd/delete/project.go
internal/cli/cmd/delete/stage.go
internal/cli/cmd/delete/warehouse.go
internal/cli/cmd/get/freight.go
internal/cli/cmd/get/get.go
internal/cli/cmd/get/projects.go
internal/cli/cmd/get/promotions.go
internal/cli/cmd/get/stages.go
internal/cli/cmd/get/warehouse.go
internal/cli/cmd/login/login.go
internal/cli/cmd/promote/promote.go
internal/cli/cmd/refresh/refresh.go
internal/cli/cmd/refresh/stage.go
internal/cli/cmd/refresh/warehouse.go
internal/cli/cmd/update/freight.go
internal/cli/cmd/update/update.go
internal/cli/option/flag.go
internal/cli/option/option.go

Touches into #1163
This pull request achieves multiple things:
1. Commands no longer make use of lengthy in-line `func`s to perform an action. Instead, they are built around "option" `struct`s with methods to add flags, parse command arguments, validate, and run the actual command logic. By doing this, we introduce a separation of concerns while also allowing things to (hypothetically) be tested without relying on further Cobra functionalities.
2. Flags are now registered as required, mutually exclusive, taking file and/or directory inputs, etc. using Cobra features. Which improves out-of-the-box validation, while also enriching the shell completion instructions. For more information around this, see e.g. https://pkg.go.dev/github.com/spf13/cobra#Command.MarkFlagRequired
```go
struct …
```

refactor(cli): restructure commands, option flags and validation

---

api/v1alpha1/labels.go
cmd/controlplane/controller.go
internal/controller/labels.go
internal/controller/labels_test.go
internal/credentials/credentials.go
internal/credentials/credentials_test.go

Fixes #1554 
This configures the Kargo manager client to only watch Secrets with a `kargo.akuity.io/cred-type` label set to a recognized type.
When testing this with 100 randomly generated Secrets in the `default` namespace using:
```shell
for i in {1..100}; do head -c 500000 /dev/urandom | base64 | kubectl create secret generic random-$i --from-file=my-file=/dev/stdin; done
```
This makes the memory consumption as reported by kube-metrics go from 199Mi before the patch to 14Mi afterwards.

feat(controller): watch only Secrets w/ Kargo labels

---

internal/cli/cmd/apply/apply.go
internal/cli/cmd/approve/approve.go
internal/cli/cmd/config/config.go
internal/cli/cmd/config/set_project.go
internal/cli/cmd/create/create.go
internal/cli/cmd/create/project.go
internal/cli/cmd/dashboard/dashboard.go
internal/cli/cmd/delete/delete.go
internal/cli/cmd/delete/project.go
internal/cli/cmd/delete/stage.go
internal/cli/cmd/delete/warehouse.go
internal/cli/cmd/get/freight.go
internal/cli/cmd/get/get.go
internal/cli/cmd/get/projects.go
internal/cli/cmd/get/promotions.go
internal/cli/cmd/get/stages.go
internal/cli/cmd/get/warehouse.go
internal/cli/cmd/login/login.go
internal/cli/cmd/logout/logout.go
internal/cli/cmd/promote/promote.go
internal/cli/cmd/refresh/refresh.go
internal/cli/cmd/refresh/stage.go
internal/cli/cmd/refresh/warehouse.go
internal/cli/cmd/update/freight.go
internal/cli/cmd/update/update.go
internal/cli/cmd/version/version.go

Fixes #1163 
This updates all command usages, examples, etc. to use the same syntax, which matches the syntax used for `kubectl` commands.
In addition, where applicable various variations of command options have been documented in places where a command works with a series of options.

chore(cli): update all usages and examples

---

internal/api/promote_stage_v1alpha1.go
internal/api/promote_subscribers_v1alpha1.go

I overlooked that `freightName` can now be empty if the client provided `freightAlias` instead.

fix(api): bug in updated promotion endpoints

---

docs/docs/30-how-to-guides/15-working-with-freight.md

The current link for key concepts is broken in https://kargo.akuity.io/how-to-guides/working-with-freight

chore(docs): fixing link for concepts in working-with-freight.md

---

internal/credentials/credentials.go
internal/helm/helm.go
internal/webhook/warehouse/webhook.go
internal/webhook/warehouse/webhook_test.go

Fixes: #1583 
This adds validation to ensure a Warehouse does not contain multiple subscription entries pointing to the same URL, or in the case of a HTTP/S Helm chart, to the same URL and chart name.
```console
$ kubectl apply -f warehouse.yaml
The Warehouse "my-warehouse" is invalid:
* spec.subscriptions[2].image: Invalid value: "nginx": subscription for image repository already exists at "spec.subscriptions[0].image"
* spec.subscriptions[4].git: Invalid value: "https://github.com/example/kargo-demo.git": subscription for Git repository already exists at "spec.subscriptions[1].git"
* spec.subscriptions[5].chart: Invalid value: "https://example.com/charts/": subscription for chart "nginx" already exists at "spec.subscriptions[3].chart"
* spec.subscriptions[7].chart: Invalid value: …
```

feat(webhook): detect duplicate warehouse subs

---

api/v1alpha1/stage_types.go
charts/kargo/templates/api/cert.yaml
charts/kargo/templates/api/configmap.yaml
charts/kargo/templates/api/ingress-cert.yaml
charts/kargo/templates/api/ingress.yaml
charts/kargo/templates/argocd/role-binding.yaml
charts/kargo/templates/argocd/role.yaml
charts/kargo/templates/controller/configmap.yaml
charts/kargo/templates/dex-server/secret.yaml
charts/kargo/templates/garbage-collector/configmap.yaml
charts/kargo/templates/management-controller/configmap.yaml
charts/kargo/templates/webhooks-server/configmap.yaml
cmd/controlplane/controller.go
internal/api/config/config.go
internal/api/get_config_v1alpha1.go
internal/api/get_config_v1alpha1_test.go
internal/argocd/namespace.go
internal/controller/promotion/argocd.go
internal/controller/stages/health.go
internal/kubeclient/indexer.go

Fixes #1549
Alternative to #1594
Some users who install Kargo via Argo CD have noted difficulties syncing that are likely attributable to https://github.com/argoproj/argo-cd/issues/15566
While #1594 proposed two specific changes to the most noteworthy occurrences of the problem, this PR attempts a more holistic remedy.
1. In Go code, define default namespace for Argo CD _in only one place._ This information is used by multiple components, and each previously set their own default (although they all set it the same). Remedying this seemed necessary for what follows...
1. In Go code, make the default ttl for admin tokens 24h. This differed from the default set in the chart itself. Once again, this seemed necessary for what follows...
1. Chart modification according to the following …

chore(chart): be more careful about undefined values

---

internal/api/kubernetes/client.go

Fixes a bug that snuck in with #1599. I'm not sure how many other similar mistakes may exist.

fix: bug loading rest config

---

internal/cli/cmd/get/get.go

Noticed that I could only get yaml or json output if only a single object was passed to `printObjects`.
This fixes it.

fix(cli): fix bug with output flag

---

internal/api/delete_project_v1alpha1.go
internal/api/delete_stage_v1alpha1.go
internal/api/delete_warehouse_v1alpha1.go
internal/api/get_project_v1alpha1.go
internal/api/get_promotion_v1alpha1.go
internal/api/get_stage_v1alpha1.go
internal/api/get_warehouse_v1alpha1.go
internal/api/watch_promotion_v1alpha1.go
internal/api/watch_promotions_v1alpha1.go
internal/api/watch_stages_v1alpha1.go
internal/api/watch_warehouses_v1alpha1.go

Working on resolving merge conflicts in #1566, I noticed some weirdness in existing endpoints.
This PR:
* Removes unnecessary gets before deletes.
* Removes unnecessary wrapping of Kubernetes "not found" errors as connect "not found" errors. Our error interceptor is already smart enough to do that. We don't need to do it explicitly.

chore: minor endpoint cleanup

---

.github/workflows/ci.yaml

Massive amounts of generated code are ruining our coverage numbers.
In fact #1515 reduced us from ~50% to ~20%.
After a bit of research, grep is the most direct way to fix this.

chore: exclude generated code from coverage report

---

api/v1alpha1/stage_types.go
charts/kargo/crds/kargo.akuity.io_stages.yaml

Fixes an issue introduced in #1609, after which the "current freight" column for `kubectl get stages` would always be empty.

fix(api): print `.name` as stage's current freight

---

charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/controller/deployment.yaml
charts/kargo/templates/dex-server/deployment.yaml
charts/kargo/templates/garbage-collector/cron-job.yaml
charts/kargo/templates/management-controller/deployment.yaml
charts/kargo/templates/webhooks-server/deployment.yaml

Fixes: #1617 
By picking only the `data` or `stringData` subset for the respective ConfigMap or Secret to calculate the checksum. Ensuring only actual value changes update the annotation value.

fix(chart): enhance ConfigMap/Secret checksum annotation logic

---

.github/workflows/release.yaml

Unstable nightly (which is built off of main) is currently being produced as `v0.4.1-unstable-20240313`, even though there is an officially released v0.4.2, v0.4.3. This will bump the Y (in X.Y) rather than current Z in (X.Y.Z).
Here is how it will calculate nightly version after this change:
```
$ LATEST_VERSION=$(go list -m -versions github.com/akuity/kargo | awk '{print $NF}' | awk -F "." '{print $1"."$2".0"}')
$ NEW_VERSION=$(awk 'BEGIN {FS=OFS="."} {$2++; print}' <<< "${LATEST_VERSION}")
$ echo "unstable-version=${NEW_VERSION}-unstable-$(date +'%Y%m%d')"
unstable-version=v0.5.0-unstable-20240313
```

chore: calculate unstable version as X.Y+1.0 instead of X.Y.Z+1

---

internal/kargo/kargo.go
internal/kargo/kargo_test.go
internal/webhook/promotion/webhook.go
internal/webhook/promotion/webhook_test.go

feat: set promotion shard in webhook

---

Tiltfile
charts/kargo/templates/webhooks-server/cluster-role-binding.yaml
charts/kargo/templates/webhooks-server/cluster-role.yaml

This fix gives permission to "promote" (not really) to the Kubernetes generic garbage collector, which needs the permission for the same reason the namespace controller always has. See comments in the chart for further explanation.
This will allow deletion of a Stage to properly cascade to the Promotions it owns -- which was not happening before. This _may_ be a factor in some issues that @gdsoumya has reported to me offline that occur when managing Kargo Projects via Argo CD.

fix(chart): add permissions for k8s generic gc to "promote"

---

api/v1alpha1/helpers.go
api/v1alpha1/helpers_test.go
internal/controller/stages/stages.go
internal/webhook/stage/webhook.go
internal/webhook/stage/webhook_test.go

@gdsoumya had a discussion offline and decided this was preferable because it means the finalizer only ever gets added to Stages if the controller is actually running...
This makes it easier to delete Stages that have never been reconciled.

refactor: add finalizer to stages in controller instead of webhook

---

internal/api/create_or_update_resource_v1alpha1.go
internal/api/create_resource_v1alpha1.go
internal/api/update_resource_v1alpha1.go

Fixes #1648 
The create, update, and "create or update" endpoints tend to always return results that appear error-free unless closely inspected. This is because each line item in the response indicates success or failure for a single resource.
I'm a little iffy on what status code we should be returning for a request where creates or updates succeeded and others failed -- and we can debate that separately.
What this PR does is revamps the error-handling so that _at least_ in the case of a _single_ resource being created/updated, when an issue is encountered creating/updating that one resource, the issue with that one create/update will dictate the return code for the entire request.
This PR also updates the create process to explicitly check for existence before creating or updating using …

fix(api): improve error handling in create/update/apply resource endpoints

---

docs/docs/15-concepts.md
docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/15-working-with-freight.md

~~Fixes:~~ Partly addresses: #1656
- Remove mentions of `id` field for Freight.
- Change `verificationResult` to `verificationInfo`.
- Document newly introduced `verificationHistory` field.
- Document `alias` field and label for Freight.
- Small fixes of things I found along the way.

chore(docs): update documentation for v0.5.0

---

charts/kargo/README.md
charts/kargo/templates/crds.yaml
charts/kargo/values.yaml
hack/tilt/values.dev.yaml

This introduces a new change to the chart which allows the Custom Resource Definitions to be managed as part of the release, effectively allowing upgrades. Which is not possible with [Helm's built-in Custom Resource Definition management](https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds).
The behavior can be opted-out of by setting `crds.create` to `false`, causing them to be excluded from the Helm release manifests which effectively causes a fallback to Helm's default behavior.
With this change, existing installations will have to adopt the Custom Resource Definitions by configuring the following annotations and label on the resources:
```sh
RELEASE=<Helm release name>
NAMESPACE=<Helm release namespace>
for name in $(kubectl get crds -o name | grep kargo.akuity.io); …
```

feat(chart)!: manage CRDs as part of release

---

internal/controller/promotion/git_test.go
internal/controller/promotion/helm_test.go

This ensures the clean up of temporary directories, even in case of test failures, is guaranteed. Which is not the case with `defer` calls.

chore(tests): use `t.TempDir`

---

Dockerfile
internal/controller/git/git.go
internal/controller/promotion/git.go
internal/controller/promotion/git_test.go
internal/controller/promotion/helm.go
internal/controller/promotion/helm_test.go
internal/controller/promotion/kustomize.go
internal/controller/promotion/kustomize_test.go
internal/controller/promotion/pullrequest.go
internal/controller/promotion/render.go
internal/controller/promotion/render_test.go
internal/kargo-render/render.go

Fixes #1330
~~Depends on https://github.com/akuity/kargo-render/pull/268~~
This PR:
* Upgrades us to Kargo Render v0.1.0-rc.38, which has three important, new features:
* Can take input from a local repository instead of a remote repository
* Can write output to a local path instead of a branch in a remote repository
* Does not refuse to manage an existing branch that lacks Kargo Render metadata, _as long as the branch is 100% empty_
* Fixes a bug in Kargo's existing PR-based promotions where the base branch is assumed to exist
* We now create it if it doesn't
* Make Kargo Render promotion mechanism behave much more like the Helm and Kustomize-based ones:
* Points Kargo Render at the path of the already-cloned repo, which will already be sitting on the desired commit
Taken together, these …

feat: make pr-based promotions work with kargo render

---

docs/docs/30-how-to-guides/15-working-with-freight.md

Hi,
I noticed there was a dead link to localhost:3000 in the documentation.
This PR fixes it.
\Mathias

chore(doc): Remove invalid link to localhost:3000 in documentation

---

api/v1alpha1/generated.proto
api/v1alpha1/stage_types.go
charts/kargo/crds/kargo.akuity.io_stages.yaml
internal/webhook/stage/webhook.go
internal/webhook/stage/webhook_test.go
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

Fixes #1699
#1683 has also received a complementary change.

fix(webhook): sync shard field and label in only one direction

---

internal/cli/cmd/create/create.go

The interesting thing is that this became apparent due to Bash auto-completion showing odd behavior, as it would complete `kargo create project` with the short description added `(Create a project)`.

fix(cli): remove duplicate `create project` cmd

---

api/v1alpha1/stage_types.go
api/v1alpha1/stage_types_test.go
internal/controller/promotions/promotions.go
internal/controller/stages/stages.go

This ensures that besides the initial push of a `FreightReference` to the history of a `Stage`, it is actually kept up-to-date with any new changes at the end of a reconciliation run. By doing this, we can provide the user with historical bookkeeping of verification information for the past `Freight` of a `Stage`.
Required to properly address #1694

fix(controller): keep Stage history up-to-date

---

internal/webhook/freight/webhook.go
internal/webhook/freight/webhook_test.go
internal/webhook/warehouse/webhook.go
internal/webhook/warehouse/webhook_test.go

Similar to #1699/#1701, this PR updates logic in webhooks to sync only one-way between important labels and their corresponding "convenience fields." This removes the surprising behavior that clearing such a field has no effect.

fix(webhooks): label sync logic in webhooks

---

internal/cli/option/kubernetes.go

Similar to #1715, but for v0.4.x. Reverts/replaces what was done in #1528

fix(cli): restore ability to read manifests from stdin -- 0.4 edition

---

ui/src/features/freightline/freight-contents.tsx

fix: support helm in freightline

---

docs/docs/20-quickstart.mdx
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR locks the docs in `release-0.4` (which are the current production docs) into v0.4.5 of the chart and quickstart scripts from the `release-0.4` branch.
This will keep what are now the production docs working correctly even as we begin to tackle v0.5.0-specific release chores in `main`.

chore: release chores 0.4

---

docs/docs/20-quickstart.mdx
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.5.0-rc.2` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.5.0` release.

chore: v0.5.0 release chores

---

docs/docs/20-quickstart.mdx

Adds the shard column to some of the sample output.
Also stops using Freight's `id` field, which is empty for all _new_ Freight.
Instead of using Freight's `metadata.name` in place of `id`, the docs now opt for using the Freight's `alias`, which is now supported just as well as `metadata.name` as a means of identifying a piece of Freight.
These fixes also need to be cherry-picked into the `release-0.5` branch.
cc @christianh814

fix(docs): minor fixes to the quickstart

---

ui/src/features/common/freight-label.tsx
ui/src/features/common/utils.ts
ui/src/features/freightline/freight-item.tsx
ui/src/features/project/project-details/nodes/repo-node.module.less
ui/src/features/project/project-details/nodes/repo-node.tsx
ui/src/features/project/project-details/nodes/stage-node.module.less
ui/src/features/project/project-details/nodes/stage-node.tsx
ui/src/features/project/project-details/project-details.tsx
ui/src/features/project/project-details/types.ts
ui/src/features/project/project-details/update-freight-alias-modal.tsx

This cherry-picks #1736 into the `release-0.5` branch.

feat: surface warehouse reconciliation errors in DAG -- release-0.5 edition

---

docs/docs/20-quickstart.mdx
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

v0.5.0-rc.3 is on its way out the door as we speak.
This PR will make it easier for non-engineers to validate the quickstart using https://main.kargo.akuity.io/quickstart
This is a follow-up to #1740 and can be rolled back at a later date.

chore: update scripts and quickstart for v0.5.0-rc.3

---

internal/cli/cmd/promote/promote.go

CLI panics when failed to promote stage subscribers, since it tries to access `nil` response. 
This PR fixes this issue by checking the error before printing results to not access `nil` response.

fix(cli): don't panic on promote stage subscribers failure

---

docs/docs/20-quickstart.mdx
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This reverts temporary changes that made the edge docs `v0.5.0-rc.3`-specific for the benefit of those test-driving the RC.

chore: revert #1747 and #1740

---

ui/hack/generate-proto-extensions.mjs
ui/src/gen/k8s.io/apimachinery/pkg/util/intstr/generated_pb.ts
ui/tests/api/apimachinery.spec.ts

`intstr.IntOrString` relies on `gogo/protobuf` for JSON encoding/decoding, which is incompatible with the protobuf dependency used in our UI.
This commit extends `IntOrString` to encode/decode to/from JSON value to make compatible with
`gogo/protobuf`.
Related:
- https://github.com/akuity/kargo/issues/708
- https://github.com/akuity/kargo/pull/1515

feat(ui): extend IntOrString to support JsonValue

---

internal/cli/cmd/get/credentials.go
internal/cli/cmd/get/freight.go
internal/cli/cmd/get/get.go
internal/cli/cmd/get/projects.go
internal/cli/cmd/get/promotions.go
internal/cli/cmd/get/stages.go
internal/cli/cmd/get/warehouse.go
internal/cli/option/flag.go

Fixes #1751
So I hope this way of solving it is okay, please be critical because I haven't worked much on cobra before.
I've added the flag to the options pacakge just to keep it clean, I believe we have done that for all flags as far as I can tell.
I set the --no-headers flag as a persistent flag on the get (root) command using the same options pattern.
In the options structs of all subcommands I have embedded the getOptions (kept it unexported for now), so that we can easily add more get options to all subcommands. **Struct embedding felt natural here to me as we are using it across all get commands, but happy to amend that if needed** just means we get o.getOptions.NoHeaders instead of o.NoHeaders in a few places.
For the printTable function I ended up just adding a no headers bool as …

feat(cli): add --no-headers flag to all get commands.

---

ui/hack/generate-proto-extensions.mjs
ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts

Fixes #1783 
When serializing resources as JSON, this change will interpret zero value timestamps (i.e. `{seconds: 0, nanos: 0}`) as `undefined` instead of throwing a parsing error.
@rpelczar this solves the problem that we were debugging together earlier.
@hoon I think you'd be the best person to review this. 🙏

fix(ui): when serializing resources as json, interpret zero value timestamps as undefined

---

charts/kargo/templates/users/cluster-roles.yaml

Without these being present on the roles, it appears that the get functionalities in the UI for AnalysisRuns do not work as expected.

fix(chart): add AnalysisRun permissions for users

---

ui/src/features/common/freight-label.tsx

Using `placement='bottom'` does not work immediately and would likely require fiddling with CSS for an hour or two... but `placement='right'` works with a one line change. I'd prefer bottom placement but it's not worth the refactoring
Fixes #1773

fix: change placement of freightline tooltips

---

ui/hack/generate-proto-extensions.mjs
ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts
ui/tests/api/apimachinery.spec.ts

Fixes https://github.com/akuity/kargo/issues/1783
UI fails to render `metav1.Time` because properties are omitted during deserialization. However, those omitted number properties should be treated as `zero` by the protobuf speiciation (https://protobuf.dev/programming-guides/proto2/#optional).
This commit narrows down the fix provided in https://github.com/akuity/kargo/issues/1783 by ensuring omitted (undefined) properties to be treated as `zero` by providing initialization value to the properties. Also make sure to `metav1.Time` to be serialized to `null` when the both of properties are `zero` (or undefined) - same as the Go implementation.

fix(ui): provide initialization value to `metav1.Time` properties

---

Dockerfile

This PR backports #1802 to the `release-0.5` branch.

fix: pass version info to UI during build -- release-0.5 edition

---

cmd/controlplane/api.go
cmd/controlplane/controller.go
cmd/controlplane/garbage_collector.go
cmd/controlplane/management_controller.go
cmd/controlplane/version.go
cmd/controlplane/webhooks.go

This is the "control plane" version of #1547.
While it does move things into a better direction by creating a better separation of concerns, this continues to be a candidate to be revised again when we have time.

refactor(controller): restructure controlplane commands

---

api/v1alpha1/stage_types.go
api/v1alpha1/stage_types_test.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go
internal/controller/stages/verification.go
internal/controller/stages/verification_test.go
internal/kubeclient/errors.go
internal/kubeclient/errors_test.go

Addresses (part of) #1640
This improves the handling of transient Kubernetes API errors which may occur during the verification step of a Stage's current Freight.
It does this by selectively returning errors which should be retried, causing the reconciler to not leave the `Verifying` phase and allowing it to retry the action it performed on the next reconciliation attempt.
To allow the reconciler to distinguish a creation error from a failed attempt to retrieve results, closer inspection is performed on the existence of an `AnalysisRun` reference in the `VerificationInfo`.

feat(verification): improve transient error handling

---

.golangci.yaml
go.mod

closes #1790 
As @krancour said dependabot did most of the work yesterday but in golangci lint and the go module itself we were still on 1.20/1.21.

chore(deps): bump golang to 1.22 (everywhere)

---

internal/api/list_promotions_v1alpha1.go
internal/api/list_promotions_v1alpha1_test.go

Follow up on https://github.com/akuity/kargo/pull/1810.

fix(api): order Promotions by creation timestamp

---

docs/docs/20-quickstart.mdx

In zsh this command fails, which is remedied by a bit of quoting.

docs: quote uname-arch

---

internal/controller/git/git.go
internal/helm/helm.go
internal/kustomize/kustomize.go

This PR allows sub processes to have access to the parent environment variables (usually set on the container).
For example, certain environments use an HTTP_PROXY to forward traffic. In order to support this use-case, Kargo needs to forward the container's environment variables to the sub processes.
The updated processes are `git`, `helm` and `kustomize`. `kargo-render` is already passing the `os.Environ()` down to the sub process (see [here](https://github.com/akuity/kargo/blob/2d9101eebdbe4ddb1b121f2cdbe885a42721e1c4/internal/kargo-render/render.go#L73-L77))
Let me know if you'd like me to create an issue for this also.

fix: pass environment variables to sub processes

---

internal/controller/promotions/promotions.go

This PR adds Promotion details (namespace and name) to logger to let controller log with contexts to track on.

feat: inject reconcile target details to Promotion controller logger

---

api/v1alpha1/labels.go
internal/controller/stages/verification.go
internal/controller/stages/verification_test.go

Currently, there is no way to figure out the AnalysisRun is triggered by whether Promotion or reverification.
This PR adds the last Promotion name to the AnalysisRun label if it's not triggered by reverification.
cc @jessesuen @gdsoumya

feat: add current Promotion name to AnalysisRun label

---

Makefile

Fixes #1789
I put this at the top level to pass to all hack commands so it covers both the hack-test-unit and hack-build-cli commands (and any future commands that may be affected).

fix(devx): Disable vcs stamping when running in docker container.

---

api/v1alpha1/annotations.go
api/v1alpha1/helpers.go
api/v1alpha1/helpers_test.go
api/v1alpha1/stage_helpers.go
cmd/controlplane/webhooks.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go
internal/controller/stages/verification.go
internal/webhook/stage/webhook.go
internal/webhook/stage/webhook_test.go

> Part of #1231 
This PR sets actor information on Stage and AnalysisRun to allow controller to track who triggered (re-)Verification.
If the Stage or AnalysisRun has re-verify actor annotation, the controller will override the actor information with the given actor when emitting `FreightVerification` events.

feat: track actor who triggered reverification

---

api/v1alpha1/freight_types.go

#1837 got me thinking about this.
Tag information should be incorporated into the canonical representation of a piece of Freight that is used for deterministically generating its ID.
We already do something similar for images, where we factor in both tag and digest.

feat: factor git tag into freight ids

---

ui/src/features/stage/analysis-run-modal.tsx

Follow up to #1827.
Ensures the modal actually displays the YAML, even if it does not make use of the raw response API option yet.

fix(ui): correctly display AnalysisRun YAML

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
internal/controller/warehouses/git.go
internal/controller/warehouses/git_test.go
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

feat(controller): support filtering Git subscriptions using globs and path prefixes

---

.github/workflows/release.yaml
Dockerfile
Makefile
internal/api/config/config.go
internal/api/server.go
ui/package.json

This small change embeds all UI assets into the CLI and control plane binaries, constituting a minor step toward #1728, specifically the "It should allow the user to visit the UI in their browser" part.
Although it makes the server launched by the CLI capable of serving the UI, the UI still doesn't allow for the possibility of not needing to authn.
As I said... a minor step.

refactor: embed ui assets in binaries

---

api/v1alpha1/freight_types.go
internal/git/git_test.go

Follow-up to #1854.
I've realized that we should use normalized URLs when constructing Freight IDs.
This way, if someone updates a subscription in a Warehouse to use a new URL that is semantically equivalent to the old URL, we won't end up with a new piece of Freight just because of that.

refactor: use normalized URLs in constructing freight id

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
docs/docs/15-concepts.md
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

Partly addresses #1869
@hiddeco you are best to review this since you are also very familiar with the details of this feature.

docs: Document new includePaths and excludePaths options

---

api/v1alpha1/annotations.go
api/v1alpha1/event.go
internal/api/promote_to_stage_subscribers_v1alpha1.go
internal/api/promote_to_stage_v1alpha1.go
internal/controller/stages/stages.go
internal/kargo/kargo.go
internal/kargo/kargo_test.go
internal/webhook/promotion/webhook.go
internal/webhook/promotion/webhook_test.go

This PR allows to controller to track who triggered Promotion by the actor information set by API / Webhook when the Promotion is created.

feat: set promotion actor to the annotation

---

internal/api/server.go

After #1833, installing the chart into a cluster will cause links to nested paths to return 404.
- Install `0.6.0-unstable-20240419`
- Navigate to Kargo Dashboard
- Create new project (kargo-demo)
- Navigate to new project (https://host/project/kargo-demo)
- Refresh and you'll see:
`404 page not found`
Since assets are served through the API server, the router needs to redirect the URLs to `index.html` since the UI is a single page application.
@krancour I figured you'd have context on this, so tagging you. I'm not sure if this is something you've encountered and were thinking of an alternative solution.

fix(api): allow ui refresh to deep links

---

go.mod
go.sum
internal/api/query_freights_v1alpha1.go
internal/controller/warehouses/git.go
internal/helm/helm.go
internal/image/selector_docker_hub_test.go
internal/image/selector_ghcr_test.go
internal/webhook/warehouse/webhook.go

Fixes inconsistency in using two versions of the `Masterminds/semver` package. The API for v3 is identical, but with bug fixes and improvements to the semver mechanisms.

chore(deps): remove Masterminds/semver@v1.5.0

---

Dockerfile
Dockerfile.dev
ui/package.json

This unblocks the CI from merge failures, see e.g. https://github.com/akuity/kargo/actions/runs/8812620833/job/24188756463

fix(build): pin pnpm version and update to 9.0.3

---

api/v1alpha1/promotion_types.go
internal/controller/promotions/promotions.go

Follow up on https://github.com/akuity/kargo/pull/1721
I also debated with myself about the suggestion to make the Promotion mechanism(s) responsible for setting the Freight in the Status. In the end, I decided against it partly because it would make the composite mechanism more difficult to understand. As for any mechanism other than the first, the new Freight reference input would have to be taken from the Status.

chore(api): remove redundant setter from Promotion

---

internal/api/get_analysisrun_v1alpha1.go
internal/api/get_analysisrun_v1alpha1_test.go
internal/api/get_analysistemplate_v1alpha1.go
internal/api/get_analysistemplate_v1alpha1_test.go
internal/api/get_freight_v1alpha1.go
internal/api/get_freight_v1alpha1_test.go
internal/api/get_project_v1alpha1.go
internal/api/get_project_v1alpha1_test.go
internal/api/get_promotion_v1alpha1.go
internal/api/get_promotion_v1alpha1_test.go
internal/api/get_stage_v1alpha1.go
internal/api/get_stage_v1alpha1_test.go
internal/api/get_warehouse_v1alpha1.go
internal/api/get_warehouse_v1alpha1_test.go

Fixes: #1899
This pull request ensures that the raw object data returned by the Kargo API matches the data from the Kubernetes API server. Which, unlike the JSON and YAML serializers, purges empty structures.

fix(api): use Unstructured to return raw response

---

internal/cli/option/option.go

This caught my eye while reviewing #1906

fix(cli): use stdout config from cmd in helpers

---

internal/controller/management/projects/projects.go
internal/controller/management/projects/projects_test.go
internal/webhook/project/webhook.go
internal/webhook/project/webhook_test.go

This PR changes the names of a few functions and RoleBindings to better reflect what they actually do as of #1906.
Note that changing the RoleBinding name used for _new_ Projects doesn't hurt old Projects in any way. Nevertheless, I _will_ make the Project upgrade reconciler (headed for the `release-0.6` branch only) tidy this up just for consistency.

refactor: small bit of cleanup after role mgmt feature

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR locks the docs in `release-0.5` (which are the current production docs) into v0.5.2 of the chart and quickstart scripts from the `release-0.5` branch.
This will keep what are now the production docs working correctly even as we begin to tackle v0.6.0-specific release chores in `main`.

chore: release chores 0.5

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.6.0-rc.1` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.6.0` release.

chore: release chores 0.6

---

internal/controller/warehouses/git.go
internal/controller/warehouses/git_test.go

feat(controller): Apply Warehouse Git subscription path filters to all CommitSelectionStrategy types

---

internal/api/rbac/roles.go
internal/api/rbac/roles_test.go

Fixes a bug @rbreeze found just now where wholesale update of a "Kargo Role" could add to claim annotations on the underlying ServiceAccount, but couldn't remove values from them.
I also updated a test case to surface the issue and prove it's fixed.

fix(api): fix bug in kargo role update logic

---

docs/docs/40-contributor-guide/15-release-procedures.md

To account for the possibility that I will not always be the one to do it, this PR adds formal documentation for the procedures to orchestrate a minor or major release.

docs: document minor and major release procedures

---

docs/docs/50-roadmap.md

Roadmap adjustments.
These will also be backported to the `release-0.6` since that branch will become the source of production docs once we release v0.6.0.
Also, I am making a note in the release procedures documentation I am working on that, in the future, these roadmap adjustments should be performed _prior_ to creating the release branch so that backporting these changes won't be necessary.
I want sign-off (or feedback) from both @jessesuen and @christianh814 on these changes, please. 🙏

docs: roadmap adjustments

---

ui/src/features/freightline/freight-contents.tsx
ui/src/features/freightline/stage-indicators.tsx

Difficult to see because of the lack of contrast, so it wasn't noticed until I worked on changing the freightline to light mode #1955.
Before:
After:

fix(ui): freight contents corner radius cut off

---

ui/src/features/freightline/freight-contents.tsx
ui/src/features/project/pipelines/pipelines.tsx

Was due to bad merge conflict resolution. Before and after (size difference is due to screenshot):

fix(ui): freightline contents background renders text unreadable

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Update docs and scripts to lock `release-0.6` branch to (to be released) latest version.

chore: release chores v0.6.0

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This reverts the temporary pointers to the v0.6.0 release candidates in `main`.

chore: revert pointers to v0.6.0 RCs

---

cmd/cli/root.go
internal/cli/cmd/login/login.go
internal/cli/option/option.go

Fixes https://github.com/akuity/kargo/issues/1974
This commit uses the address in config if no address is passed to the login command.

feat: use config value if no address passed to login command

---

ui/src/features/common/freight-label.tsx
ui/src/features/freightline/freight-item.tsx
ui/src/features/freightline/freightline.module.less
ui/src/features/freightline/freightline.tsx
ui/src/features/project/pipelines/nodes/repo-node.module.less
ui/src/features/project/pipelines/nodes/stage-node.tsx
ui/src/features/project/pipelines/utils/graph.ts

- When freight alias is too long to fit in Freightline box, break on the hyphen and overflow with an ellipsis
- Make Freightline boxes slightly taller+wider
- When freight aliases are too wide to fit in Stage nodes, truncate with ellipsis instead of overflowing
- Make Pipeline nodes slightly wider
- Add human-readable timestamp to Stage nodes
- Add full timestamp to Stage node tooltips

fix(ui): Better display of long labels

---

ui/src/features/freight/freight-details.tsx
ui/src/features/freightline/freight-contents.tsx
ui/src/features/freightline/freight-item.tsx
ui/src/features/freightline/freightline.module.less
ui/src/features/stage/promotions.tsx

Also adds links to Freight Details in Promotions table, and a tooltip showing the Freight alias (related to #1822):

feat(ui): display freight contents in freight details page

---

.github/workflows/backport.yaml

Fixes: #1935
If merged, pull requests can be backported automagically if labeled with `backport/<release-branch>`.

feat(devx): allow automated backporting of PRs

---

.github/workflows/ci.yaml
Makefile

Minor changes:
1. Make it convenient to run UI linting with make: `make lint-ui`
2. Make it convenient to run UI linting in a container (as similar as possible to CI): `make hack-lint-ui`
3. Make `make lint`/`make hack-lint` include UI linting with all the other linting it already does
4. Make second "stage" of CI jobs (the "expensive" ones) depend on successful completion of the `lint-ui` job (along with all the other faster/cheaper ones)

chore: minor ui linting cleanup

---

.github/workflows/backport.yaml

This should ensure workflows are properly triggered in all scenarios. Follow up on #1936.

fix: use akuitybot PAT for backport worfklow

---

internal/controller/warehouses/warehouses.go

Follow up to #1984.
Freight have always been indexed by the Warehouse that created them. This is important in determining a piece of Freight's eligibility for promotion to an Stage that's subscribed _directly_ to a Warehouse wherein all Freight from that Warehouse are implicitly qualified.
#1984 mistakenly did not set the Warehouse field on new Freight, which broke that index and, by extension, has made new Freight unavailable for promotion to "zero Stages."

fix(controller): populate warehouse field in new freight

---

go.mod
go.sum
internal/controller/warehouses/images.go
internal/image/creds.go
internal/image/digest_selector.go
internal/image/image.go
internal/image/image_test.go
internal/image/lexical_selector.go
internal/image/newest_build_selector.go
internal/image/registry.go
internal/image/registry_test.go
internal/image/repository_client.go
internal/image/repository_client_docker_hub_test.go
internal/image/repository_client_test.go
internal/image/selector_docker_hub_test.go
internal/image/selector_ghcr_test.go
internal/image/selector_test.go
internal/image/semver_selector.go
internal/image/semver_selector_test.go

Fixes #1488
This is a giant step toward solving #1885 since go-containerregistry supports quite a variety of authn options, including the ability to emulate ACR, ECR, and GCR Docker credentials helpers. Those new authn methods are not included in this PR. Those will come in a follow-up.
~~Note that I prefer we merge #1984 before this since I know there will be merge conflicts between the two PRs and I volunteer as tribute.~~ All set.

refactor: use container image repo client from go-containerregistry

---

internal/controller/promotion/argocd.go

Fixes #2017
Probably a candidate to be backported to `release-0.6`.

fix(promotion): set namespace on ArgoCD event

---

internal/controller/warehouses/git.go
internal/controller/warehouses/helm.go
internal/controller/warehouses/helm_test.go
internal/controller/warehouses/images.go
internal/image/newest_build_selector.go

Related to #1984
This brings the logging for Git and Helm artifact discovery up to the same level as what was already done for container images. Providing much richer data on trace level, and more structured information at the debug level.

chore(warehouse): enrich discovery logs

---

docs/docs/50-roadmap.md

While looking up some information on the roadmap, it didn't feel right that I had to scroll to the bottom of the page to become aware of what the "next new thing" would be. This is an attempt to solve this annoyance.

docs: slightly reorder roadmap entries

---

cmd/controlplane/controller.go
internal/controller/promotion/root_test.go
internal/credentials/credentials.go
internal/credentials/credentials_test.go
internal/credentials/ecr/access_key_test.go
internal/credentials/ecr/pod_identity.go
internal/credentials/ecr/pod_identity_test.go

Fixes #1885 
This is a follow-up to #2059, which accidentally addressed a large portion of #1885.
This adds unit tests to our `ecr` package, improves existing ones, fixes a cache bug, and improves how we determine the AWS account ID, which we need for calculating the ARN of the roles to be assumed by the Kargo controller.

feat(controller): fully support eks pod identity for ecr access

---

charts/kargo/templates/dex-server/deployment.yaml

Chart render fails with additional dex volumes added, using example in values.yaml results in error due to volume formatting.
```
volumes:
- name: config
projected:
sources:
- secret:
name: kargo-dex-server-cert
items:
- key: tls.crt
path: tls.crt
- key: tls.key
path: tls.key
- secret:
name: kargo-dex-server
items:
- key: config.yaml
path: config.yaml
- name: google-json
secret:
defaultMode: 420
secretName: kargo-google-groups-json
```

fix(chart): dex additional volumes indentation

---

internal/credentials/gar/service_account_key.go

This isn't an especially serious flaw, as scopes only _limit_ a token's privileges and can not expand them beyond the associated service account's own privileges, but requesting read/write access when obtaining an access token for Artifact Registry is unnecessary as Kargo only ever _reads_ from container image repositories.

fix: reduce scope of artifact registry access token

---

docs/docs/30-how-to-guides/20-managing-credentials.md

docs: document cred management with cli + specific support for ecr and google artifact registry

---

ui/src/features/stage/promotions.tsx

Hello,
It's will be nice to have approver informations inside the UI of the stage with all other informations we kept form promotions.

feat: add approved by column in the UI of the stage

---

internal/api/server.go
internal/http/http.go

chore(ui): add cache headers for static assets

---

ui/src/features/common/truncate-middle.tsx
ui/src/features/freightline/freight-contents.tsx
ui/src/features/freightline/freightline-header.tsx

fix(ui): better handle long freight content tags

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.7.0-rc.1` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.7.0` release.

chore: release chores 0.7

---

docs/docs/20-quickstart.mdx

v0.6.x docs will soon be archived at https://release-0-6.kargo.akuity.io/, so this PR locks them into using the v0.6.0 CLI.
New production docs will be published from `release-0.7` after the v0.7.0 release.
Note: There would ordinarily be more changes in a PR of this nature, but it seems various other references to v0.6.0 in docs and scripts were already set prematurely at the time of the v0.6.0 release. We should avoid that in the future because by _not_ specifying exact versions, we would _naturally_ get the latest things and wouldn't need to update docs to reference every new patch release.

chore: lock v0.6.x docs into v0.6.x scripts

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Follow up to #2103 
This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.7.0-rc.2` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.7.0` release.
This should not be merged until `v0.7.0-rc.2` is released.

chore: bump references in docs from v0.7.0-rc.1 to v0.7.0-rc.2

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Undoes #2113 and #2103 so edge docs once again, implicitly, reference latest available binaries and charts.

docs: 0.7 release chores

---

internal/controller/git/git.go

The previous approach was inherited from when there was a need to be able to obtain the diff paths for a range of commits. With the refactoring in v0.7.0, however, this is no longer a requirement.
Because of this, we can switch to `git show` to obtain the diff paths for a specific commit. Using `--name-only` to print the paths, while further supplying `--pretty=""` to omit any other commit (message) data. Effectively yielding the same output as the previous command, except that it now also works for root commits.
Fixes: #2140

fix: allow obtaining diff paths for root commit

---

internal/gitprovider/github/github.go
internal/gitprovider/github/github_test.go

fix(controller): support parsing github enterprise urls

---

docs/STYLE_GUIDE.md
docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/20-managing-credentials.md
docs/docs/40-contributor-guide/10-hacking-on-kargo.md
docs/docs/40-contributor-guide/index.md
docs/src/theme/MDXComponents/A.js
docs/src/theme/MDXComponents/Code.js
docs/src/theme/MDXComponents/Details.js
docs/src/theme/MDXComponents/Heading.js
docs/src/theme/MDXComponents/Img/index.js
docs/src/theme/MDXComponents/Img/styles.module.css
docs/src/theme/MDXComponents/Pre.js
docs/src/theme/MDXComponents/Ul/index.js
docs/src/theme/MDXComponents/Ul/styles.module.css
docs/src/theme/MDXComponents/index.js

In the course of documenting #2139 and fixing https://github.com/akuityio/docs.akuity.io/issues/491 / https://github.com/akuityio/docs.akuity.io/pull/493 I learned how to [swizzle](https://docusaurus.io/docs/swizzling) Docusaurus 3 correctly.
For reference:
```shell
npm run swizzle @docusaurus/theme-classic MDXComponents -- --eject
```
This change makes `Tabs`, `TabItem`, and `Hlt` available globally, even in files that use the `.md` extension and _not_ `.mdx`.
There's really no point to this other than that it will save effort on future doc additions.

docs: DRY things up a bit by swizzling

---

internal/api/kubernetes/client.go

Happened to notice today that when our authorizing client wrapper tries to find a ServiceAccount that the SSO user is entitled to use, and which _also_ has suitable permissions for the resource + operation in question, it checks all Project namespaces for such ServiceAccounts _when the resource in question is cluster-scoped._
Although a ServiceAccount living in some Project namespace _could_ have ClusterRoleBindings that give it access to cluster-scoped resources, I believe users would find it surprising for anything that goes on within a Project namespace to have ramifications _beyond_ that namespace.
This PR narrows the subset of SAs (to which the user is federated with) that will be considered for operations on cluster-scoped resources. It will _only_ consider SAs within the so-called …

fix: do not check project namespaces for sas when operating on cluster-scoped resources

---

internal/controller/promotion/git.go
internal/controller/promotion/pullrequest.go
internal/gitprovider/github/github.go
internal/gitprovider/gitlab/gitlab.go
internal/gitprovider/gitprovider.go
internal/gitprovider/registry.go

Follow up to #2158, #2145, #1274
The last remaining difficulty I have been able to detect with PR-based promotions to repositories in self-hosted GitHub Enterprise or GitLab is that the `insecureSkipTLSVerify` option available at the pull request level is not honored by the clients used by the relevant GitProviders.
This PR fixes that.
And with this PR, I can also confirm Kargo working e2e with an actual instance of GHE Server.

fix(controller): make pull request-based promotions honor cert ignore option

---

internal/controller/promotion/argocd.go

This addresses #2162, which unlike the issue indicates, never actually worked in any Kargo version.

fix(promo): record failure message for Argo CD Application

---

docs/docs/15-concepts.md
docs/docs/20-quickstart.md
ui/src/features/project/pipelines/utils/stage-yaml-example.ts

Partially addresses #1966
Long-term, I'd like if the quickstart perhaps transitioned to using forks of the https://github.com/akuity/guestbook-deploy repo, but this PR is an interim step that at least eliminates the quickstart's dependency on Docker Hub, thereby dramatically reducing the possibility that any one run through the quickstart fails due to rate-limiting.
fwiw, I have been able to run discovery (with a limit of 20) on the Nginx repo in ECR 10x without being rate-limited, so no one should really encounter rate limits with the Warehouse discovery limit set to 5 and performing discovery on its regular schedule.
This should not be merged immediately after approval because it requires corresponding changes to the [akuity/kargo-demo](https://github.com/akuity/kargo-demo) repo.

refactor(docs): don't use dockerhub in the quickstart or concepts doc

---

ui/src/features/common/code-editor/yaml-editor-lazy.tsx
ui/src/features/project/list/create-project-modal.tsx
ui/src/features/project/pipelines/create-stage-modal.tsx
ui/src/features/project/pipelines/create-warehouse-modal.tsx
ui/src/features/project/pipelines/warehouse/edit-warehouse.tsx
ui/src/features/project/settings/components/edit-project-modal.tsx
ui/src/features/stage/edit-stage-modal.tsx

fix(ui): use correct JSON schema URL in YAML editors

---

api/v1alpha1/stage_types.go
api/v1alpha1/stage_types_test.go

This backfills some tests for logic added in #2187

chore(api): backfill API tests for FreightHistory

---

.github/ISSUE_TEMPLATE/feature_request.md

@jessesuen we discussed this quite some time ago.
To refresh:
There was some confusion over the `kind/feature-request` vs `kind/enhancement` labels.
I had intended that the former be, as it says, _a request_, while the latter is _more than a request_ -- something we're committed to doing.
We agreed this wasn't very intuitive and that we would change the template to add both `kind/enhancement` _and_ `kind/proposal` and that maintainers can simply drop `kind/proposal` when we've agreed that a feature is worth implementing. 
Well... here it is. Sorry for the delay.
After this is merged, I'll update outstanding `kind/feature-request` to be `kind/proposal` + `kind/enhancement` instead.

chore: change labels used by feature request template

---

api/v1alpha1/stage_types.go
api/v1alpha1/stage_types_test.go
internal/argocd/health.go
internal/argocd/health_test.go
internal/controller/stages/health_test.go
internal/controller/stages/stages.go

This is the most elegant way I could think of to enable support for multi-Freight health checks.
It works by determining which Freight element from a `FreightCombination` applies to the Application, leveraging the existing logic to determine the desired revision (based on source matching of the Freight against the Application data).
For each match, the further "revision health" is assessed, which will either return early in case of an "unhealthy" state or allow it to continue when it passes for all applicable Freight.

refactor(controller): support multi-Freight health checks 

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

In the CRD docs `freightCreationPolicy` is required, even though strictly speaking if not specified it will be set to `Automatic`.

chore: clarify optionality

---

ui/src/features/freightline/freight-item.tsx
ui/src/features/freightline/freightline-header.tsx
ui/src/features/freightline/freightline.tsx
ui/src/features/project/pipelines/pipelines.tsx

In many cases, Freightline are full of dozens or hundreds of old, unused freight that slows down the UI. This PR adds a toggle to hide all freight older than the oldest freight currently in use.

feat(ui): ability to collapse old freight in freightline

---

api/v1alpha1/freight_types.go
api/v1alpha1/freight_types_test.go

feat: factor origin into freight name

---

ui/src/features/project/pipelines/nodes/stage-node.tsx

Empty label was missing with new multi pipelines logic:

fix(ui): bring back empty freight label

---

ui/src/features/freight-timeline/freight-contents.tsx

Previosuly, with more than ~2 items in a piece of Freight, the Freight Timeline would overflow them with a vertical scrollbar (by design). A recent PR, which updated the `FreightContents` component for re-use elsewhere, accidentally broke this behavior. This PR restores it.

fix(ui): freight contents overflowing horizontally

---

docs/docs/20-quickstart.mdx
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR locks the docs in `release-0.7` (which are the current production docs) into v0.7.1 of the chart and quickstart scripts from the `release-0.7` branch.
This will keep what are now the production docs working correctly even as we begin to tackle v0.8.0-specific release chores in `main`.

chore: update docs and scripts to lock release-0.7 branch into latest stabe release

---

docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.8.0-rc.1` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.8.0` release.

chore: update docs and scripts to work with v0.8.0-rc.1

---

api/v1alpha1/helpers.go
api/v1alpha1/labels.go
charts/kargo/templates/controller/cluster-roles.yaml
charts/kargo/templates/management-controller/cluster-roles.yaml
cmd/controlplane/controller.go
cmd/controlplane/management_controller.go
go.mod
internal/controller/management/upgrade/freight.go
internal/controller/promotions/promotions.go
internal/controller/stages/stages.go
internal/controller/stages/upgrade.go
internal/controller/warehouses/warehouses.go
internal/controller/warehouses/warehouses_test.go
internal/kubeclient/indexer.go
internal/webhook/freight/webhook.go
internal/webhook/freight/webhook_test.go

This PR provides a smooth upgrade path from Kargo v0.7.x to v0.8.x, focusing on migrating Stages and Freight resources to support the multi-pipeline functionality.
Key changes:
1. Stage migration:
- Adds upgrade logic to the Stage reconciler to migrate Stages from <=0.7.x to 0.8.x compatibility
- Converts old `Subscriptions` field to new `RequestedFreight` field
- Migrates `History` to new `FreightHistory` format
- Adds v0.8 compatibility label to track which resources have been migrated
2. Freight migration:
- Introduces a new Freight reconciler in the management controller to handle upgrades
- Migrates `Warehouse` field to new `Origin` field
- Ensures backward compatibility by syncing `Origin` and `Warehouse` fields
- Adds v0.8 compatibility label to prevent further migrations
3. …

feat: add v0.7.x --> v0.8.x upgrade logic

---

internal/kubeclient/indexer.go
internal/kubeclient/indexer_test.go

Backfills some tests and other tidying around indexers which I happened to run into.

chore(kubeclient): tidy indexers and add tests

---

internal/controller/promotions/promotions.go

- Fixes crash by adding additional nil checks
- Resolves #2361

fix(controller): fix panic when last promotion has no freight collection

---

ui/src/features/project/pipelines/warehouse/warehouse-details.tsx

Before, if a warehouse had the same name as its project (common in demos), the Warehouse Details view could be confusing:
This PR adds a label and icon to make it clear that this is the Warehouse Details view:

chore(ui): indicate resource type in Warehouse Details view

---

ui/src/features/auth/token-renew.tsx

fix(ui): infinite redirect loop when renewing OIDC token

---

ui/src/features/common/health-status/health-status-icon.tsx
ui/src/features/freight-timeline/freight-item.tsx
ui/src/features/project/pipelines/nodes/stage-node.tsx

Two small fixes.
Before:
After:
Before:
After:

fix(ui): promoting freight cutoff + health status icon fixes

---

internal/cli/cmd/login/login.go

Fixes: https://github.com/akuity/kargo/issues/2363

fix(cli): retain config changes on re-login

---

internal/argocd/revision.go
internal/controller/promotion/argocd.go
internal/controller/promotion/argocd_test.go
internal/controller/promotion/helm.go

Fixes #2407
If I am not mistaken, these differences were more thoroughly accounted for prior to the large bit of refactoring in v0.8.0, where they were overlooked.

fix(controller): account for differences in kargo, argo cd, and helm before searching for oci helm charts

---

internal/controller/promotion/argocd.go
internal/controller/promotion/argocd_test.go
internal/kubeclient/patch.go

This PR changes the approach to patching Argo CD Applications, using unstructured data. This addresses an issue where fields not present in Kargo's Application shim (which we maintain to not rely on Argo CD and its dependencies) could accidentally be removed during patch operations (see #2423).
It achieves this by modifying and patching the Argo CD Application as an unstructured Kubernetes object, using replace and merge operations where applicable to update the fields Kargo cares about. To ensure merges of list items (i.e. `.spec.sources`) do not result in an unintended result (for example, because an `ApplicationSet` made a change to the list) — both the generation of the objects are compared before the modifying operations, and an optimistic lock is used during the actual patch …

fix(promotion): patch Application w/ Unstructured

---

charts/kargo/templates/api/cluster-role.yaml

This commit grants API to manage ConfigMap, which allows users to manage ConfigMaps that used in `AnalysisTemplate` through Kargo API.

feat(api): grant API to manage ConfigMap

---

internal/controller/promotion/argocd.go
internal/controller/promotion/argocd_test.go
internal/controller/promotion/composite.go
internal/controller/promotion/composite_test.go
internal/controller/promotion/git.go
internal/controller/promotion/git_test.go
internal/controller/promotion/pullrequest.go
internal/controller/promotion/root.go
internal/controller/promotion/root_test.go
internal/controller/promotions/promotions.go

Fixes #2427 
925b765b461bd3fc19fd7e9055698140bd76e5a3 (the second commit) is the actual bug fix and is pretty straightforward. It modifies the sync operations we initiate to include the id of the Freight collection that is being promoted. We check for this information when determining if we need to initiate a sync operation. This allows a promotion to wait for a sync operation to complete in cases where we previously would not have simply for lack of any means to determine whether the completed sync operation was indeed the one we'd been waiting for.
fe15116e9e8447a2f12b9f6da5a392216606b61c (the first commit) changes the interface of promotion mechanisms to be quite a bit cleaner. The bug fix described above required the Argo CD app update promotion mechanism to have access to the Freight …

fix(controller): improve logic to determine when syncing an argo cd app is required

---

charts/kargo/templates/management-controller/cluster-roles.yaml
charts/kargo/templates/webhooks-server/cluster-role.yaml

#2430 gave new permissions to the ClusterRole that is dynamically bound (with a RoleBinding) to the API server's and Project admin's ServicesAccounts at Project creation time, however, the webhook server and management controller, both of which play a role in creating those bindings, were not updated with the same permissions. This makes these two components incapable of delegating this permission they lack.
This PR fixes it.

fix: webhook server and controller permissions

---

Makefile
cmd/controlplane/api.go
internal/api/delete_analysistemplate_v1alpha1_test.go
internal/api/get_analysisrun_v1alpha1_test.go
internal/api/get_analysistemplate_v1alpha1_test.go
internal/api/get_config_v1alpha1_test.go
internal/api/get_credentials_v1alpha1_test.go
internal/api/get_freight_v1alpha1_test.go
internal/api/get_project_v1alpha1_test.go
internal/api/get_promotion_v1alpha1_test.go
internal/api/get_stage_v1alpha1_test.go
internal/api/get_warehouse_v1alpha1_test.go
internal/api/kubernetes/client.go
internal/api/list_analysistemplates_v1alpha1_test.go
internal/api/list_projects_v1alpha1_test.go
internal/api/list_promotions_v1alpha1_test.go
internal/api/list_stages_v1alpha1_test.go
internal/api/option/option.go
internal/api/refresh_stage_v1alpha1.go
internal/api/refresh_stage_v1alpha1_test.go
internal/api/server.go
internal/api/server_test.go
internal/cli/cmd/server/server.go
internal/kubeclient/indexer.go
ui/vite.config.ts

Fixes #1728
Follows up on #2395 cc @rbreeze 
This makes some modifications to how we construct the custom k8s client used by the API server only. This makes a lot of the boilerplate configuration of that client a bit DRYer so that we can more easily use it in multiple places -- with one of those places being the `kargo server` command.
`kargo server` fully works after this.
Note that to try this, you need to make sure the UI is baked into the CLI, which it typically isn't except by our actual release process.
I did something like this to ensure that:
```console
cd ui
pnpm install
NODE_ENV=production pnpm run build
cd ..
rm -rf internal/api/ui
mv ui/build internal/api/ui
go run cmd/cli/*.go server
```

feat: make local server work finally

---

internal/controller/git/bare_repo.go
internal/controller/git/bare_repo_test.go
internal/controller/git/base_repo.go
internal/controller/git/repo.go
internal/controller/git/repo_test.go
internal/controller/git/work_tree.go
internal/controller/git/work_tree_test.go
internal/controller/promotion/git.go
internal/controller/promotion/pullrequest.go
internal/controller/warehouses/git.go

This adds a couple more enhancements to our git package:
* On clone, persists preference for ignoring cert errors as config so that preference does not need to be re-specified when loading an existing repo from the FS.
* Add option when pushing to push to a remote branch with a different name than the current local branch.
There are more prerequisite capabilities for the git-based promotion directives.

feat(controller): more git pkg enhancements

---

internal/controller/git/bare_repo.go
internal/controller/git/bare_repo_test.go
internal/controller/git/base_repo.go
internal/controller/git/work_tree.go
internal/controller/git/work_tree_test.go

These are more incremental improvements to the git package that will be important for git-based promotion directives:
* Add `Clear()` (`git rm -rf .`) to the WorkingTree interface.
* Add `RemoteBranchExists()` to the `BareRepo` interface and move the existing implementation of that from the `workTree` type to the `baseRepo` type.
* Add options to the `BareRepo.AddWorkTree()` func so that it is possible now possible to add a working tree for a brand new orphaned branch.
cc @hiddeco
These improvements felt small and non-controversial enough that I thought it best, as with other recent improvements to the git package, to directly PR these to `main` so that our feature branch you and I have been working on isn't bigger than it really needs to be.

feat(controller): more git pkg improvements

---

internal/directives/kustomize_set_image_directive.go
internal/directives/kustomize_set_image_directive_test.go

Plus some minor changes to the tests to properly reference images (without a tag).

fix(directives): return `kustomize-set-image` result

---

api/v1alpha1/event.go

Regression introduced in #2315 
Replace unsafe type assertions on `u.Claims` with safe pattern, to avoid a panic on missing (nil) or non-string claims.

fix(api): prevent panic in FormatEventUserActor

---

internal/directives/argocd_update_directive.go
internal/directives/argocd_update_directive_test.go
internal/directives/origins.go
internal/directives/origins_test.go
internal/directives/schemas/argocd-update-config.json
internal/directives/zz_config_types.go

This adds the `argocd-update` directive.
It's a lot of code, _but_ a vast majority of it is copied from the existing `internal/controller/promotion` package and then _minimally_ adapted to work with the configs for directive, which have been generated from JSON schema.
This means this logic is mostly tried and true and also means we have pretty decent test coverage.
Note there was no attempt to make this code common and shared between the older promotion mechanisms and this directive since it is anticipated that the older promotion mechanisms will be removed within a couple releases anyway.
Unsurprisingly, configuration should look remarkably similar to the existing Argo CD promotion mechanism:
```yaml
steps:
- step: argocd-update
config:
apps:
- name: my-app
namespace: my-namespace …
```

feat(controller): add argocd-update directive

---

internal/controller/git/bare_repo.go
internal/controller/git/bare_repo_test.go

This changes the listing of Git worktrees by implementing a more robust parsing mechanism for the `git worktree list` command output. The previous implementation struggled with certain edge cases, such as detached HEAD states, leading to parsing errors:
```
error adding work tree ./target to repo https://example.com/org/repo.git: unexpected number of fields: "/tmp/dir/source                67286d2 (detached HEAD)"
```
The new approach utilizes the `--porcelain` option and introduces a line-by-line parsing strategy, capable of extracting detailed information about each worktree, including its path, HEAD commit, branch, etc. without relying on a specific number of columns.

fix(git): improve parsing of worktree list

---

ui/src/features/common/manifest-preview.tsx
ui/src/features/freight/freight-details.tsx
ui/src/features/project/pipelines/pipelines.tsx
ui/src/features/stage/stage-details.tsx

fix(ui): stage/freight live manifest scrolls infinitely

---

internal/directives/argocd_revisions.go
internal/directives/argocd_revisions_test.go
internal/directives/argocd_update_directive.go
internal/directives/argocd_update_directive_test.go

This PR ports a subset of recent improvements to the classic Argo CD promotion mechanisms in #2552 over to the `argocd-update` directive.
There are no functional changes in this PR.
This does pave the way for health check functionality to be added in follow-ups that I am already working on.

refactor: port recent improvements from classic promo mechs to argocd-update directive

---

ui/src/features/project/pipelines/pipelines.tsx
ui/src/features/project/pipelines/utils/use-pipeline-graph.ts

Before
After this fix
Even though this affects "subscription-warehouse" components in graph, I tried to verified with more components

fix(ui): graph line b/w warehouse and multiple subscriptions broken

---

internal/controller/argocd/api/v1alpha1/application_types.go
internal/directives/argocd_health.go
internal/directives/argocd_health_test.go
internal/directives/argocd_revisions.go
internal/directives/argocd_revisions_test.go
internal/directives/argocd_updater.go
internal/directives/argocd_updater_test.go

* Ports legacy Argo CD App health check code to the `argocdUpdater` that was introduced by #2545. Includes recent health check improvements from #2552 (multi-source health checks).
* Further simplifies the above. `Stage` was passed around to a lot of places that didn't need it.
* Implements the new `HealthCheckStepRunner` introduced in #2554.

feat(controller): complementary health checks for argocd-update promotion step

---

internal/directives/argocd_revisions.go
internal/directives/git_commiter.go
internal/directives/git_commiter_test.go
internal/directives/git_pr_opener.go
internal/directives/git_pr_opener_test.go
internal/directives/git_pr_waiter.go
internal/directives/schemas/argocd-update-config.json
internal/directives/schemas/git-commit-config.json
internal/directives/schemas/git-open-pr-config.json
internal/directives/zz_config_types.go

d4b21c242259456facf6e7cfbd42e2dd8f7f2c31 is the main part of this PR.
It opens the possibility of informing source updates in an `argocd-update` step that the desired revision (for a source pointed at a Git repo) should be indicated by the output of some previous step.
This is critically important for the common use case where the promotion workflow has made a commit to some branch and so the commit that a given AppSource should be synced to now is _different_ from what is in the Freight. i.e. This addresses the same concern that "health check commits" previously did with the legacy promotion mechanisms.
eaea784564483739f3a1aea2442a14ea22c42b26 makes `git-wait-for-pr` steps include a commit ID in their output. (To potentially later be referenced by an `argocd-update` step as described …

feat: allow argocd-update steps to learn desired revisions for sources from previous steps

---

internal/directives/git_tree_overwriter.go

It was incorrect to ignore `.git` in the source dir only if it was itself a directory.
Worktrees have a .git _file_.
This can create problems when copying from a working tree, as `.git` will be copied, which was not the intention.

fix: fix bug in git overwrite promotion step

---

internal/directives/simple_engine.go

The `DeepCopyJSON()` logic borrowed from apimachinery doesn't seem to like our `State` type. But our `State` type is just a `map[string]any` with some additional methods added to it. If we cast the output from our promotion steps as `map[string]any`, the deep copy succeeds and we're no worse off.

fix: cast output from promotion steps as map[string]any

---

internal/directives/git_commiter.go

This logic was present in the legacy promotion mechanisms and was overlooked in the git-commit directive.

fix: make git-commit promotion step check for diffs before committing

---

internal/directives/argocd_health.go
internal/directives/argocd_revisions.go
internal/directives/git_commiter.go
internal/directives/git_commiter_test.go
internal/directives/git_pr_opener.go
internal/directives/git_pr_opener_test.go
internal/directives/git_pr_waiter.go
internal/directives/git_pusher.go
internal/directives/git_pusher_test.go
internal/directives/health_checks.go
internal/directives/helm_chart_updater.go
internal/directives/helm_chart_updater_test.go
internal/directives/helm_image_updater.go
internal/directives/helm_image_updater_test.go
internal/directives/kustomize_image_setter.go
internal/directives/kustomize_image_setter_test.go
internal/directives/promotions.go
internal/directives/simple_engine.go
internal/directives/simple_engine_test.go

Follow-up on #2589
The change wasn't as safe as I thought.
This is a more holistic fix that switches the output from promotion steps from a `State` to a regular `map[string]any`.
The only benefit a `State` has over a normal `map[string]any` is a few convenience methods, including `DeepCopy()`. We only need that at the _top_ of the state map. i.e. There's no reason that output from individual steps can't be a normal map.
I can vouch for this fix better than I could for #2589 because when this is combined with #2590, I can now observe most of the Git-based promotion steps working together correctly from end-to-end.

fix: prefer map[string]any everywhere where we don't actually need to use DeepCopy

---

ui/src/features/project/pipelines/nodes/stage-node.tsx

fixes https://github.com/akuity/kargo/issues/2587

fix(ui): unblock promotions when promotion directives are used

---

internal/directives/git_tree_overwriter.go

It escaped my notice until now that `git-overwrite` promotion step couldn't handle a single file as a source.
This is essential because the `helm-template` and `kustomize-build` promotion steps both write their output to a single file. (Aside: I will open a separate issue for adding the option to split the output into individual files for every resource the way that Kargo Render could.)

fix: allow overwriter promotion step to handle individual files

---

internal/directives/git_pr_opener.go

There was some logic that ran prior to this that might have found a branch to use other than `cfg.SourceBranch`, but incorrectly using `cfg.SourceBranch` instead of `sourceBranch` means that logic was not being taken into account.

fix(controller): fix source branch used by pr-opener

---

internal/directives/simple_engine.go

The simple engine was allowing for success or failure only and wasn't accounting for the possibility of a step that is pending a change in external state, such as waiting for a PR to be merged.

fix(controller): make simple engine short-circuit step execution on non-success

---

internal/directives/git_pr_waiter.go
internal/directives/git_pr_waiter_test.go
internal/directives/schemas/git-wait-for-pr-config.json
internal/directives/zz_config_types.go

This swaps the `prNumberFromOpen` field for `prNumberFromStep`, thereby not implying that the `prNumber` output this step consumes _needs_ to have come from an `git-open-pr` step.
This improves consistency with the other built-in promotion steps, which use the same syntax to avoid implying that input _needs_ to have come from a particular kind of step.
All this will be moot once we have some kind of EL built, but for now, this matters.

refactor: update wait-for-pr step for improved consistency with other built-ins

---

docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR locks the docs in `release-0.8` (which are the current production docs) into v0.8.7 of the chart and quickstart scripts from the `release-0.8` branch.
This will keep what are now the production docs working correctly even as we begin to tackle v0.9.0-specific release chores in `main`.

docs: update docs and scripts to lock release-0.8 branch into latest stable release

---

docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.9.0-rc.1` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.9.0` release.

docs: update docs and scripts to work with v0.9.0-rc.1

---

cmd/controlplane/garbage_collector.go
cmd/controlplane/webhooks.go
internal/api/kubernetes/client.go
internal/api/list_project_events_v1alpha1.go
internal/api/list_promotions_v1alpha1.go
internal/api/option/auth.go
internal/api/query_freights_v1alpha1.go
internal/controller/promotions/promotions.go
internal/controller/promotions/watches.go
internal/controller/promotions/watches_test.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go
internal/controller/stages/watches.go
internal/garbage/freight.go
internal/garbage/promotions.go
internal/indexer/indexer.go
internal/indexer/indexer_test.go
internal/webhook/freight/webhook.go

Variation of #2593.
As noted in the `// TODO`, I would like at some point for us to _not_ treat certain directives as "special" — but from a functional point of view, that's not a strict requirement at this point.
I did have to move the indexers out of `kubeclient`, to get around a cyclic import.

fix(indexer): extract Apps from Promotion directives

---

internal/directives/helm_template_runner.go
internal/directives/helm_template_runner_test.go
internal/directives/schemas/helm-template-config.json
internal/directives/zz_config_types.go

Helm-related part for #2596.
This makes the directive behave the same as `helm template` when passing a directory (non `.yaml` or `.yml`) as output path. Writing each manifests to `<outPath>/<chartName>/<pathInChart>`, or `<outPath>/<releaseName>/<pathInChart>` when `useReleaseName` is configured.

feat(directives): support multi file write for `helm-template`

---

internal/directives/schemas/helm-template-config.json
internal/directives/zz_config_types.go

This solves a potential annoyance people could run into as without a release name specified, Helm defaults it to `release-name`. Which causes something like you see in the screenshot below:

fix(directives): require release name for `helm-template`

---

internal/directives/kustomize_builder.go
internal/directives/kustomize_builder_test.go

feat(directives): support writing kustomize output to multiple files

---

internal/controller/promotions/promotions.go
internal/directives/argocd_updater.go
internal/directives/argocd_updater_test.go
internal/directives/fake_engine.go
internal/directives/fake_engine_test.go
internal/directives/file_copier.go
internal/directives/file_copier_test.go
internal/directives/git_cloner.go
internal/directives/git_cloner_test.go
internal/directives/git_commiter.go
internal/directives/git_commiter_test.go
internal/directives/git_pr_opener.go
internal/directives/git_pr_waiter.go
internal/directives/git_pr_waiter_test.go
internal/directives/git_pusher.go
internal/directives/git_tree_overwriter.go
internal/directives/git_tree_overwriter_test.go
internal/directives/helm_chart_updater.go
internal/directives/helm_chart_updater_test.go
internal/directives/helm_image_updater.go
internal/directives/helm_image_updater_test.go
internal/directives/helm_template_runner.go
internal/directives/helm_template_runner_test.go
internal/directives/kustomize_builder.go
internal/directives/kustomize_builder_test.go
internal/directives/kustomize_image_setter.go
internal/directives/kustomize_image_setter_test.go
internal/directives/promotions.go
internal/directives/simple_engine.go
internal/directives/simple_engine_test.go

This PR aligns engine/step statues more closely with promotion statuses, in fact it reuses `kargoapi.PromotionPhase`, which eliminates some of the need for mapping engine/step statuses to Promotion phases.
At the same time, it fixes a large discrepancy between Promotion phases and engine/step statuses. Promotions have, for quite some time, used `Errored` for _technical_ failures and `Failed` for non-technical failures.
An example of a non-technical failure would be when a Promotion fails due to user action such as closing a PR without merging.
This PR also updates the `git-wait-for-pr` step to treat that specific scenario as a failure instead of an error.
These changes have been validated end-to-end.

refactor: promo step errors

---

internal/directives/simple_engine.go

Messages in promotion step results were getting lost because the engine wasn't using them to populate the message field for the overall promotion step result.

fix(controller): fix message that was getting lost beteen step and reconciler

---

docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Follow-up to #2612
This PR updates `main` and the edge docs at https://main.kargo.akuity.io/ in a way that facilitates non-engineers being able to easily test-drive the `v0.9.0-rc.2` release candidate just by following the quickstart exactly as it is written.
These changes will outlive their usefulness and should be reverted after we cut the official `v0.9.0` release.

docs: update scripts and docs for v0.9.0-rc.2

---

internal/directives/git_pusher_test.go
internal/directives/schemas/git-push-config.json

This prevents someone from having to define `targetBranch` or `generateTargetBranch` if they want to push to the branch they checked out during `git-clone`.

fix(directives): do not require `targetBranch` for `git-push`

---

internal/argocd/health.go
internal/directives/argocd_health.go

The intention here should be to initialize a slice with a capacity of length rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

refactor(controller): fix slice init length

---

ui/src/features/stage/promotion-details-modal.tsx
ui/src/features/stage/promotions.tsx

- show output
- live view in promotion modal
- show the `as` tag of step

feat(ui): promotion steps view improvement

---

docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Do not merge until v0.9.0-rc.3 is cut.

chore: make edge docs and scripts reference v0.9.0-rc.3

---

internal/controller/promotions/promotions.go

fix(promotion): fail Promotion on validation error

---

docs/docs/15-concepts.md

Improve Kargo concept docs to make the concepts slightly easier to understand

docs: improve kargo concepts docs

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.gitignore
Dockerfile
Makefile
charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/controller/deployment.yaml
kargo-base.apko.yaml

Fixes #2400
This PR applies a hardening strategy previously put to the test on Kargo Render in https://github.com/akuity/kargo-render/pull/297
When building with `make hack-build` or via the official Actions-based CI/release processes, this will build a distroless base image using apko + wolfi and then load that into Docker and than layer the rest of Kargo on top of that. I've verified it works identically to the old image.
I've also verified that changes to the Dockerfile do not disrupt our Tilt-based development workflow.
__Edit:__ I've just realized this will break #2413. Draft until fixed.

feat: harden image using apko and wolfi

---

charts/kargo/templates/api/configmap.yaml

After upgrade to 0.9.0 SSO groups scope stop to work while having dex enabled (api.oidc.dex.enabled). Env OIDC_ADDITIONAL_SCOPES is not added to api configmap.

chore: use additional scopes while having dex enabled

---

internal/controller/git/base_repo.go

This fixes a problem that only occurs when using ssh to interact with a remote repo.
We re-setup auth mechanisms every time we load an already-cloned repo from disk because the possibility always exists that for a long-running promotion step, credentials for the repo have been updated between two executions of that step. I am confident this is the right thing to do, however, when using SSH, there is an `os.Mkdir()` call that can fail because the directory it attempts to create would have been created by the previous execution of the auth setup logic.
This PR solves that problem by using `os.MkdirAll()` instead, as that will not error if the directory already exists.
Part of #2492

fix: use mkdirall when creating ~/.ssh dir to allow for the case where it already exists

---

kargo-base.apko.yaml

Went a bit overboard in #2697.
While I would _love_ not having a shell in the image, I can't get interactions with a remote repo over ssh to work without one.
This is part of #2492

fix: add busybox to base image

---

docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Follow-up to #2706 
This updates the lives scripts (the productions docs site references scripts from main) to omit version information from installs -- which will effectively install the latest release. This should have been done at the time of the release and was overlooked. #2706 did the trick (thank you @christianh814), but omitting version info entirely from the install commands means we don't need to update this every time there is a minor release.
This PR also make similar updates the edge docs at main.kargo.akuity.io (old) and main.docs.kargo.io (new; but not working yet).

chore: remove version info from docs and scripts

---

internal/directives/git_cloner_test.go
internal/directives/schemas/git-clone-config.json

This was too restrictive to permit ssh URLs.
Note that the schemas for `git-open-pr` and `git-wait-for-pr` do not require the same change because you cannot interact with a Git provider's API over ssh, so the http/s URL is _always_ used for those steps.
Part of #2492

fix: relax clone step config validation to allow ssh urls

---

internal/cli/cmd/login/login.go

`kargo login -h` says
```
Log in to a Kargo API server
Usage:
kargo login [SERVER_ADDRESS] (--admin | --kubeconfig | --sso) [flags]
Examples:
[...]
kargo login https://kargo.example.com --kubeconfig --insecure-tls
[...]
```
however `kargo login https://kargo.example.com --kubeconfig --insecure-tls` yields
```
Error: unknown flag: --insecure-tls
```
The correct flag is `--insecure-skip-tls-verify` as also documented in the _Flags_ section of the `kargo login -h` output.

fix(cli): fix flag in login command example

---

docs/docs/30-how-to-guides/20-managing-credentials.md

Closes #2492
After several recent PRs related to this, what's in main already fully works with Git repos accessed via SSH. All that remained was to document it...

docs: document how to use ssh keys for git repos

---

api/v1alpha1/freight_helpers.go
api/v1alpha1/freight_helpers_test.go
internal/api/promote_downstream_v1alpha1.go
internal/api/promote_downstream_v1alpha1_test.go
internal/api/promote_to_stage_v1alpha1.go
internal/api/promote_to_stage_v1alpha1_test.go
internal/api/server.go
internal/controller/promotions/promotions.go
internal/webhook/promotion/webhook.go
internal/webhook/promotion/webhook_test.go

Fixes #2365 
After approaching this problem a few different ways, the thing that came out cleanest was treating the question of whether a piece of Freight is _wanted_ by a given Stage as just another dimension of whether that Freight is _available_ to that Stage.
1b3d577e491eddf6e91b7e463a41ae8c02399419 is some pre-requisite refactoring that made the more prescient refactoring and enhancements in 75d6fcc7d66da56006be5fc371e8c15f965d0de9 a bit easier.
6753bad5a0cb046e891e320508acce410a00356b just updates existing usage of the refactored availability check accordingly.
2559c0c2323e5c544966df8361267e1580e1bc4b adds the availability check to the Promo creation webhook so that availability checks aren't bypassed when using `kubectl` instead of `kargo` or the UI.

fix: improve freight availability checks

---

charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/controller/deployment.yaml
kargo-base.apko.yaml

In #2697 we went distroless _and_ shell-less. At that time, lack of a shell forced us to stop using the official Kargo image for the init container that preps any custom CA bundles. We fell back on using `alpine/curl:latest`
In #2709, for unrelated reasons, we added a minimal shell env (busybox).
As we've discussed offline, now that we've done this, we can resume using the official kargo image as the init container and it shrinks Kargo's overall footprint a tad by eliminating a dependency on an image we're not in control of.
cc @gdsoumya

refactor(chart): resume using official kargo image for cabundle init containers

---

ui/src/features/common/utils.ts
ui/src/features/freight-timeline/freight-timeline-wrapper.tsx
ui/src/features/stage/create-stage.tsx
ui/src/features/stage/freight-history.tsx
ui/src/features/stage/requested-freight.module.less
ui/src/features/stage/requested-freight.tsx
ui/src/features/stage/stage-details.tsx

feat(ui): freight history in stage details

---

Makefile
docs/docs/35-references/10-promotion-steps.md
internal/directives/kustomize_builder.go
internal/directives/kustomize_builder_test.go
internal/directives/schemas/kustomize-build-config.json
internal/directives/zz_config_types.go

Manual backport of #2733 to `release-0.9` due to merge conflicts.

chore(backport release-0.9): feat(directives): enable Helm plugin for `kustomize-build`

---

charts/kargo/templates/controller/configmap.yaml
internal/controller/promotions/promotions.go
internal/directives/git_pr_opener.go
internal/directives/promotions.go
internal/directives/simple_engine.go
internal/gitprovider/github/github.go

feat: add ui stage link to promo prs

---

.github/workflows/release.yaml

This setting was missing from the release workflow. The CI workflow already has it.
A million thanks to @34fathombelow for finding this!

fix(release-process): fix container networking in release image build process

---

internal/directives/argocd_updater.go

As the unstructured patcher already deals with conflicts, this check appears to be obsolete and can result in a (quite frustrating) error.

fix(directives): ignore resource version on app patch

---

api/v1alpha1/stage_types.go
internal/controller/promotions/promotions.go
internal/controller/promotions/promotions_test.go
internal/controller/promotions/watches.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go

Fixes: #2152
Fixes: #2128 
Fixes: #2693
💡With the Stage mechanism determining what Promotion should be allowed to be processed next, we can get rid of the prioritized queue sometime in the future.

fix(stage): wait for running verification to finish before next Promotion

---

internal/controller/stages/stages.go

It's a bit of a flaw that we're potentially making some decisions here based on health assessed in a _previous_ reconciliation loop. That being said, we can sort of get away with it because we only decide to _not_ wait for verification when we see "unhealthy," which means we are already in dire circumstances and the next promo may be what fixes it... turns out, we should handle nil health the same way.
Strategically, @hiddeco and I are in agreement that we need bigger modifications to the stage reconciliation loop to assess health at a different point in that loop so it's ideally never nil and also more up-to-date.
I'll be opening a separate issue for this refactoring.

fix: fix for deciding to wait for verification or skip to next promo

---

docs/docs/20-quickstart.md

Follow-up to #2706 and #2713 
CLI URLs reference v0.9.0-rc.3
Fixing

docs: fix cli download links in quickstart

---

internal/api/kubernetes/client.go

Fixes #2722
When OIDC claims were generalized by #2315, the `user.Info` struct went from having discrete `Sub`, `Email`, and `Groups` fields to having a `map[string]any` of claims. `any` because claim values can be scalars or vectors.
There was once a check in our authz logic for `userInfo.Sub != ""`. Since `sub` is a standard claim, we could infer the user had authenticated using Kargo's identity provider.
#2315 had an undetected bug. That check became `userInfo.Claims["sub"] != ""` and this is _always_ true because `userInfo.Claims["sub"]` isn't a `string`. It's `any` unless coerced into something else.
When this check was functioning correctly, we'd have inferred that the user who presented the token got it from somewhere _besides_ Kargo's IDP. We'd have guessed it _might_ have come …

fix(api): fix broken bearer token auth

---

cmd/controlplane/controller.go
internal/directives/git_pr_opener.go

Fixes #2792
The only reference to the `gitlab` package, ensuring it got registered as a provider, was removed along with the legacy promo mechs.
It probably should have been side-by-side with the `github` provider registration.
This fixes it. This also handles both provider registrations closer to where they're used, which makes things easier to understand.
N.B.: Longer term, I might like to see the Provider interface and registry go away. Instead of updating Kargo to register a lot of new, built-in Provider implementations over time, Kargo can just use third-party steps that integrate with with different git providers.

fix(controller): fix gitlab provider not found

---

charts/kargo/templates/users/cluster-roles.yaml

Fixes #2790 
Follows up on #2749 and #2760
cc @shmargum. Thanks for reporting.

fix(chart): add patchs on promos to kargo-admin clusterrole

---

cmd/controlplane/controller.go
internal/controller/promotions/promotions.go
internal/controller/promotions/watches.go
internal/controller/promotions/watches_test.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go
internal/controller/stages/watches.go
internal/controller/warehouses/warehouses.go

Move shard-based resource filtering from individual controllers (Promotions, Stages, Warehouses) to the controller-manager cache configuration. This simplifies the controllers by removing duplicated shard filtering logic while maintaining the same behavior at the cache level.
This should forever help prevent issues like #2791.

refactor: move shard filtering to cache level

---

cmd/controlplane/controller.go
internal/controller/warehouses/warehouses.go

Allow Warehouse resources to be accessible by all controllers in a sharded setup, while still being handled by one controller at a time.
**Note:** This assumes that only other controller instances desire to access Warehouses. If there is another case of sharding where other kinds are expected to be handled by shard X but able to be "seen" by shard Z, this will still not work.

fix: sharded Warehouse cross-controller access

---

netlify.toml

This is a "forward port." The `release-1.0` branch, which is the production docs branch, already has this fix.
I want it in `main` now so we don't lose the fix when we create a `release-1.1` branch in a few weeks.

docs: fix docs site redirect rule

---

docs/docs/20-quickstart.md

Currently, when make a promotion from test to uat or uat to prod, the kustomize still build the manifest of test stage, it makes the application cannot start because of the same nodePort, and the html content is not correct

fix(docs): kustomize build folder of uat & prod

---

internal/helm/helm.go
internal/helm/helm_test.go

Fixes the second bit of https://github.com/akuity/kargo/issues/2831#issuecomment-2435595674
---
When working with OCI-based Helm charts, version handling needs to be
stricter than with classic HTTP repositories:
1. OCI chart versions must be strict SemVer (e.g. "1.0.0" not "v1.0")
2. OCI registry tags cannot contain "+" characters used in SemVer
build metadata
To solve this:
- Add strict SemVer validation for OCI chart versions
- Convert between OCI's "_" and SemVer's "+" for build metadata

fix(helm): handle OCI version constraints and metadata

---

ui/src/features/freight-timeline/freight-content-item.tsx
ui/src/features/freight-timeline/freight-contents.tsx

Fix: Clicking multiple times on same freight not working
Having components defined inside another components is not the best practice especially without useMemo or something similar since it is quite easy to trigger a lot of re-renders.
In this instance it was triggering loop somehow (not sure 100% what it was causing, my tip is that tooltip) which ends up in:
Since there is no really good reason to have it (FreightContentItem) defined inside another component I extracted it as separate component which fixes the issue.
You can replicate the issue by clicking on highlighted area multiple times:
Note that after first click it will open details of Freight, after second click it will close it and on third click it will do nothing (it should open details again but it does not)... This happens …

fix: Clicking multiple times on same freight not working

---

cmd/controlplane/controller.go
cmd/controlplane/garbage_collector.go
cmd/controlplane/management_controller.go
cmd/controlplane/webhooks.go
docs/docs/40-contributor-guide/5-debugging-kargo.md

This makes it easier to request e.g. a CPU trace, memory profile, or any of the other things that may be handy for issues like #2836.
By default, the endpoint is disabled. It will become active when the `PPROF_BIND_ADDRESS` environment variable is set to a TCP address.
⚠️ Includes documentation: https://deploy-preview-2838.docs.kargo.io/contributor-guide/debugging-kargo

feat(controller): allow enabling pprof

---

go.mod
go.sum
internal/expressions/json_templates.go
internal/expressions/json_templates_test.go

This PR adds a new `expressions` package, which currently exports just one useful function -- `EvaluateJSONTemplate()`. This will take an array of bytes, evaluate them, and return the evaluated bytes.
The idea is that as we continue to build out expression language support in promotion steps, this can be called by an `Engine` implementation to pre-process the raw config for each step.
This is all accomplished with a combination of [fasttemplate](https://github.com/valyala/fasttemplate) and [expr-lang](https://github.com/expr-lang/expr), similar to how Argo Workflows does.
Our implementation varies a bit from Argo Workflows' in some key ways.
1. We use `${{ }}` to offset expressions. This was chosen for the sake of being more similar to GitHub Actions, with which many users are already …

feat: add low-level expression language support

---

ui/src/features/project/list/project-list-filter.tsx
ui/src/features/project/list/projects-list.tsx

Hello, my first contribution.
This adds browser local storage to remember pagination option.
Also improves the search to show only what you searched for and when selection a project you jump into it.

feat(ui): remember pagination option, project search selection jumps into project

---

cmd/controlplane/garbage_collector.go
cmd/controlplane/webhooks.go
internal/api/kubernetes/client.go
internal/api/list_project_events_v1alpha1.go
internal/api/list_promotions_v1alpha1.go
internal/api/option/auth.go
internal/api/query_freights_v1alpha1.go
internal/controller/promotions/promotions.go
internal/controller/promotions/watches.go
internal/controller/promotions/watches_test.go
internal/controller/stages/control_flow_stages.go
internal/controller/stages/control_flow_stages_test.go
internal/controller/stages/event_handlers.go
internal/controller/stages/event_handlers_test.go
internal/controller/stages/stages.go
internal/controller/stages/stages_test.go
internal/garbage/freight.go
internal/garbage/promotions.go
internal/indexer/indexer.go
internal/indexer/indexer_test.go
internal/webhook/freight/webhook.go

Continuation of https://github.com/akuity/kargo/pull/2848#discussion_r1817414034

refactor: remove over-abstraction of indexers

---

internal/api/rbac/policy_rules.go
internal/api/rbac/policy_rules_test.go
internal/api/rbac/roles.go

Related to #2864 
When creating/updating "Kargo Roles," which are an abstraction over a ServiceAccount/Role/RoleBinding trio, policy rules are normalized when read from or written to the underlying Role. Among other things, this normalization includes expansion of the verb `*` to `create, delete, deletecollection, get, list, patch, update, watch`.
Stages have an additional, custom `promote` verb that is unaccounted for.
The result is that when, the `*` verb is used in defining policy rules involving _non-Stage_ resource types, the `*` correctly expands to all the verbs supported by those resource types, but when using the `*` verb in defining policy rules involving the _Stage_ resource type, the expanded verbs lack the important custom `promote` verb.
This PR special cases expansion of …

fix(api-server)!: when normalizing roles, make wildcard verb for stages include promote

---

internal/controller/promotions/promotions.go
internal/directives/git_pusher.go
internal/directives/git_pusher_test.go
internal/directives/promotions.go
internal/directives/simple_engine.go

Part of #2845
This change creates a more obvious relationship between a Promotion and any PR it may create. This also reduces the likelihood of a Promotion attempting to create a new Promotion-specific branch and finding that branch already exists (having been created by a previous Promotion).

refactor(controller): use promotion name when generating branch names

---

ui/src/features/project/pipelines/images.tsx
ui/src/features/project/pipelines/pipelines.tsx
ui/src/features/project/pipelines/utils/watcher.ts
ui/src/features/utils/cache/image-stage-matrix.ts
ui/src/features/utils/cache/index.ts

fixes https://github.com/akuity/kargo/issues/2768
API constructs data for that table. But this lacked live updates. Its expensive to re-construct this view using API. This PR takes an advantage of the fact that Stage resource has lastPromotion field which helps to determine what should be changed in the table. We were already watching Stage events.

fix(ui): live image matrix view

---

api/v1alpha1/promotion_types.go
internal/directives/simple_engine.go
internal/webhook/stage/webhook.go
internal/webhook/stage/webhook_test.go

Part of #2845 
This PR make the step execution engine assign a default alias to any promotion step that doesn't explicitly have an alias specified.
This makes it such that _all_ steps leave behind outputs in the shared state map where that was only possible before for steps that had explicitly been assigned an alias.
This creates the possibility of modifying some step implementations, in a follow-up, to consult any output they themselves may have produced in a previous execution.
This is braking only insofar as it reserves step aliases of the form `^step-\d+$` for system use.

feat(controller)!: assign a default alias to promotion steps that have none

---

internal/controller/stages/stages.go

Found while refactoring the Stage reconciler, and seems important enough to justify a patch for 1.0.x.

fix(stages): auto-promote Freight from other origins

---

netlify.toml

fixes: https://github.com/akuity/kargo/issues/2870
So, it is a quite strange distinction.
I looked into it more, but I could not find any notable differences between [Kargo](https://github.com/akuity/kargo/blob/main/docs/sidebars.js) and [Akuity](https://github.com/akuityio/docs.akuity.io/blob/main/sidebars.js) that could lead to a navigation failure in the live document.
Aside from that, I did observe that some versions of [Package.json](https://github.com/akuity/kargo/blob/main/docs/package.json) were not updated.
But since the navigation appear well locally, I am not sure how to test this change in the live document to see if updating the version was able to improve things.
cc: @Marvin9 ptal

fix: next/prev navigation in docs

---

docs/docs/15-concepts.md
docs/docs/30-how-to-guides/11-working-with-projects.md
docs/docs/30-how-to-guides/40-managing-projects.md

closes: https://github.com/akuity/kargo/issues/2528

docs: managing projects

---

internal/controller/git/work_tree.go
internal/controller/promotions/promotions.go
internal/directives/git_pr_opener.go
internal/directives/git_pr_opener_test.go
internal/directives/git_pr_waiter.go
internal/directives/git_pr_waiter_test.go
internal/gitprovider/github/github.go
internal/gitprovider/github/github_test.go
internal/gitprovider/gitlab/gitlab.go
internal/gitprovider/gitlab/gitlab_test.go
internal/gitprovider/gitprovider.go
internal/gitprovider/registry.go

Fixes #2845
Follows up on #2878 and #2881 
This makes the `git-open-pr` step's short-circuiting a little more resilient.
Prior to this trio of related fixes, if the controller restarted while a Promotion was still in-progress waiting for a PR to be merged, when the controller came back up and found the Promotion's state gone from the ephemeral disk, it would start the entire user-defined Promotion process over again from step 0, potentially getting into trouble when it came time to open a PR, since a PR identical to the one it would otherwise open already exists. (Same source branch, same commit at the head of that branch, same base branch.)
This PR, the final component of the fix, uses a two-phased approach for the `git-open-pr` step to determine if a PR actually needs to be opened or …

fix(controller): fix pr already open issue with git-open-pr step

---

ui/src/features/project/pipelines/utils/use-pipelines-infinite-canvas.ts

After merging [this PR](https://github.com/akuity/kargo/pull/2904), all links/buttons stopped working, so we can not open Stage details or do promotions.

fix(ui): Links/Buttons in the Pipeline are not working

---

ui/src/features/project/pipelines/utils/use-pipelines-infinite-canvas.ts

fixes
- replace unsupported `computedStyleMap` in firefox with widely supported method - https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
- unblock stage node click

fix(ui): pipeline view issues

---

docs/docs/30-how-to-guides/15-working-with-freight.md
docs/docs/30-how-to-guides/20-managing-credentials.md
docs/docs/30-how-to-guides/30-managing-user-permissions.md
docs/docs/30-how-to-guides/_category_.json
docs/docs/35-references/_category_.json
docs/docs/40-contributor-guide/20-signing-commits.md
docs/docs/40-contributor-guide/30-code-of-conduct.md
docs/docs/40-contributor-guide/index.md

closes #2902
The current state of the docs adopts the label for each item in the following order of precedence
1. From the `sidebar_label` field in the frontmatter of the `.md` file (if explicitly provided)
2. From the first `# heading` in the `.md` file (if `sidebar_label` is absent)
3. From the filename of the `.md` file (if neither `sidebar_label` nor a `# heading` is present)
Given this behavior I have tried to address the issue by updating the markdown files to explicitly include titlecase in the `sidebar_label` field where it was missing. 
Do we need to add further changes, like automating this process or handling additional edge cases?
Also, should we add monotype texts for kargo resources?

fix(docs): consistent title case

---

internal/directives/argocd_updater.go

Found this while trying to debug an issue with the `argocd-update` step.

fix(directives): log error to surface reason for ArgoCD update

---

docs/docs/35-references/10-promotion-steps.md
internal/directives/helm_image_updater.go
internal/directives/helm_image_updater_test.go
internal/directives/schemas/helm-update-image-config.json
internal/directives/schemas/yaml-update-config.json
internal/directives/yaml_updater.go
internal/directives/yaml_updater_test.go
internal/directives/zz_config_types.go
ui/src/gen/directives/helm-update-image-config.json
ui/src/gen/directives/yaml-update-config.json

Fixes #2939
This PR:
* Reverts most of what #2925 did to the `helm-update-image` step. _There is no sense improving that step and deprecating individual fields if the entire step is going to be deprecated and replaced. This would only have led to confusion._
* Deprecates `helm-update-image`.
* Adds a new, generic `yaml-update` step that is essentially an improved/stripped down version of the `helm-update-image` step.

refactor: replace helm-update-image with yaml-update

---

Dockerfile
charts/kargo/templates/controller/deployment.yaml
charts/kargo/templates/garbage-collector/cron-job.yaml
charts/kargo/templates/management-controller/deployment.yaml
charts/kargo/templates/webhooks-server/deployment.yaml
kargo-base.apko.yaml

fix(build): use `tini` to reap zombie processes

---

internal/controller/stages/regular_stages.go
internal/controller/stages/regular_stages_test.go

fix(stages): set healthy status for promotions w/o checks

---

.github/workflows/ci.yaml
Makefile
ui/src/features/common/code-editor/yaml-editor-lazy.tsx
ui/src/features/project/credentials/create-credentials-modal.tsx
ui/src/features/project/credentials/utils.tsx
ui/src/features/project/list/project-list-filter.tsx
ui/src/features/project/pipelines/nodes/freight-indicators.tsx
ui/src/features/project/pipelines/utils/useImages.ts
ui/tsconfig.json

After this PR the UI type issues won't go unnoticed and would give more confidence on UI stability if any schema is changed from backend.

ci: add typechecks for UI

---

charts/kargo/values.yaml

Making a simple change to the values.yaml to fix https://github.com/akuity/kargo/issues/2919

fix: update casing to Azure Example in values.yaml unknown connector type "Microsoft"

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

closes https://github.com/akuity/kargo/issues/2880
doc ref: https://github.com/akuity/kargo/pull/2963

fix: missing enumerated values in generated docs for warehouse

---

docs/docs/35-references/10-promotion-steps.md

closes https://github.com/akuity/kargo/issues/2440
https://github.com/akuity/kargo/pull/2921#discussion_r1844558574

docs: authorise kargo to argocd-update

---

ui/src/features/promotion-directives/registry/use-discover-registries.ts

fixes https://github.com/akuity/kargo/issues/2986

feat(ui): 'http' and 'yaml-update' promotion directives support

---

internal/directives/promotions.go

Follow-up to #2998
> ordering the signatures from longest and most complex to shortest and simplest might yield a better signature match
> I applied the same re-ordering to other similar functions
One such change was not saved and thus was not committed and included in the PR.
This small change makes the statement accurate and the tests still pass.

refactor(controller): fix order of imageFrom() func signatures

---

internal/controller/promotions/promotions.go
internal/controller/stages/control_flow_stages.go
internal/controller/stages/regular_stages.go
internal/controller/warehouses/warehouses.go
internal/predicate/ignore_delete.go

Streamlines the code, while adding back what got removed in #2905:
https://github.com/akuity/kargo/blob/v1.0.3/internal/controller/stages/stages.go#L274-L283

fix(controller): add `IgnoreDelete` predicate

---

internal/directives/git_cloner.go
internal/directives/git_cloner_test.go

The `git-clone` step's `checkout[].create` setting wasn't being checked before creating a new remote branch.
Thanks to @34fathombelow for finding this.
This is a breaking change only insofar as it changes (incorrect) behavior.
If it trips anyone up, the error message should be informative enough for them to fix the issue quickly.

fix(controller)!: check create setting when attempting to clone non-existent remote branch

---

docs/docs/35-references/10-promotion-steps.md
internal/directives/argocd_updater.go
internal/directives/git_cloner.go
internal/directives/helm_chart_updater.go
internal/directives/helm_common.go
internal/directives/helm_image_updater.go
internal/directives/kustomize_image_setter.go

We agreed at the weekly sync meeting that deprecated fields and steps will stick around for two minor releases before being removed. This adjusts docs and comments accordingly.

docs: adjusts deprecation notices

---

Makefile
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

Thank you @arober39 for finding.

chore: stop using deprecated setting for cert-manager chart

---

internal/directives/git_cloner.go
internal/directives/git_cloner_test.go

Manual backport of #3012
Merge conflicts prevented an automated backport.

fix(controller): manual backport of git-clone fix from #3012

---

Dockerfile
charts/kargo/templates/controller/deployment.yaml
charts/kargo/templates/garbage-collector/cron-job.yaml
charts/kargo/templates/management-controller/deployment.yaml
charts/kargo/templates/webhooks-server/deployment.yaml
kargo-base.apko.yaml

Manual backport of #2959 due to conflicts.

chore(backport release-1.0): fix(build): use `tini` to reap zombie processes

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/features/auth/oidc-login.tsx
ui/src/features/auth/token-renew.tsx
ui/src/features/auth/utils.ts

**NOTE: This could potentially be breaking change if API server does not have SSL and Dex is being used. HTTP requests will not be supported to IDPs**
Read all breaking changes here - https://github.com/panva/oauth4webapi/releases/tag/v3.0.0
Old dependabot PR https://github.com/akuity/kargo/pull/3025

chore(ui): bump `oauth4webapi` major version

---

internal/directives/argocd_updater.go

chore: clear app status op state

---

internal/controller/stages/regular_stages.go
internal/controller/stages/regular_stages_test.go

Primarily to be able to overwrite it in tests, as the previous approach caused an unnecessary delay for the unit tests.

chore(controller): make backoff configurable for tests

---

docs/docs/20-quickstart.md
docs/docs/30-how-to-guides/10-installing-kargo.md
hack/quickstart/install.sh
hack/quickstart/k3d.sh
hack/quickstart/kind.sh

This PR locks the docs in `release-1.0` (the current production docs) into v1.0.4 of the chart and quickstart scripts from the `release-1.0` branch.
This allows us to switch to the soon-to-be-published `release-1.1` production docs without breaking the documentation for 1.0.

chore: release chores 1.0

---

docs/docs/20-quickstart.md

While this is not part of the currently documented [release procedure](https://docs.kargo.io/contributor-guide/release-procedures), I believe this is the correct way to handle this.
The reason is that `main` may contain changes that are not relevant to the current production release range, which could then cause issues. Instead, the documentation should be locked to scripts from the release branch, and any changes relevant to this SemVer range should be backported instead.
Note that this does not include setting the version for the chart as is being done in e.g. #3078, as the "latest" published version is correctly detected by Helm itself.

chore: release chores 1.1

---

.github/workflows/ci.yaml

Deals with error that I had noticed a couple of times in CI:
```
level=warning msg="[config_reader] The output format `github-actions` is deprecated, please use `colored-line-number`"
```

chore(ci): handle deprecation of Go linter format

---

internal/directives/argocd_updater.go
internal/directives/argocd_updater_test.go

Fixes #3082 
@jessesuen, I built ghcr.io/akuity/kargo-unstable IMAGE_TAG=custom-20241207 if you want to test drive.

fix(controller): app sync fix

---

docs/docs/35-references/10-promotion-steps.md
internal/directives/git_pr_opener.go
internal/directives/git_pr_opener_test.go
internal/directives/schemas/git-open-pr-config.json
internal/directives/zz_config_types.go
ui/src/gen/directives/git-open-pr-config.json

feat: custom PR title (#3063)

---

internal/credentials/kubernetes/database.go
internal/credentials/kubernetes/database_test.go

Fixes #2928
We formerly applied git repo URL and chart repo URL normalization to _all_ repo URLs when searching for credentials because we believed it to be safe.
An edge case we'd not previously identified involved that fact that an image repo URL of the form `host:port/name` can be mistaken for an SCP-style Git URL and would thus be normalized as `host:port/name` 😬 and would prevent a successful match.
This PR causes us to selectively normalize based on the type of credential we're searching for.

fix(controller): do not normalize urls when searching for image creds

---

docs/docs/35-references/10-promotion-steps.md
internal/controller/freight/finder.go
internal/controller/freight/finder_test.go
internal/directives/kustomize_image_setter.go
internal/directives/kustomize_image_setter_test.go
internal/directives/schemas/kustomize-set-image-config.json
internal/directives/zz_config_types.go
ui/src/gen/directives/kustomize-set-image-config.json

With this pull request, setting `images` for the `kustomize-set-image` step is now optional.
When left unspecified, all images from the Freight collection are automatically set as long as there is no ambiguous target image found (due to e.g. two Warehouses having different selectors for the same image). In case of an ambiguous target image, an error is returned and manual configuration of `images` will still be required.
It is worth noting that the generated commit message describes what's being set in the `kustomization.yaml`, and will thus contain a reference to all images even if they do not appear in any of the Kubernetes manifests which are part of the Kustomization overlay. 
Fixes: #2788

feat(directives): optional `images` for `kustomize-set-image`

---

ui/src/features/auth/context/auth-context-provider.tsx
ui/src/features/auth/context/auth-context.tsx
ui/src/features/auth/jwt-utils.ts
ui/src/features/auth/oidc-login.tsx
ui/src/features/auth/oidc-utils.ts
ui/src/features/auth/token-renew.tsx
ui/src/features/common/layout/main-layout.tsx
ui/src/pages/user.tsx

fix(auth): auto attach `offline_access`  only if idp supports

---

ui/src/features/auth/token-renew.tsx

Not sure if this was issue previously or after recent library major version bump but token renew failures went unnoticed and causing page stuck on loading spinner

fix(auth): token renew failure

---

charts/kargo/templates/api/deployment.yaml

Related to #3038 
This starts to make use of the [builtin gRPC probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) in an attempt to eventually drop our dependency on `grpc_health_probe`.
Sadly, however, the builtin probe does not support TLS (https://github.com/kubernetes/kubernetes/issues/128365) (or disabling verification), and we can thus not drop the `grpc_health_probe` binary yet.

chore(chart): start using Kubernetes' builtin gRPC probe

---

docs/docs/30-how-to-guides/20-managing-credentials.md

closes https://github.com/akuity/kargo/issues/2834

docs: manual rolebindings for global namespaces

---

docs/docs/45-resources.md

closes https://github.com/akuity/kargo/issues/1089

docs: add a resources page for Kargo related talks

---

docs/docs/30-how-to-guides/30-managing-user-permissions.md

This PR introduces a 'Kargo Role Matrix` which outlines the maximum rules required for a ClusterRole/Role.

docs: Kargo role matrix

---

docs/docs/35-references/10-promotion-steps.md
internal/controller/git/errors.go
internal/controller/git/errors_test.go
internal/controller/git/work_tree.go
internal/directives/errors.go
internal/directives/errors_test.go
internal/directives/git_pr_waiter.go
internal/directives/git_pr_waiter_test.go
internal/directives/git_pusher.go
internal/directives/git_pusher_test.go
internal/directives/http_requester.go
internal/directives/http_requester_test.go
internal/directives/schemas/git-push-config.json
internal/directives/simple_engine_promote.go
internal/directives/simple_engine_promote_test.go
internal/directives/zz_config_types.go
ui/src/gen/directives/git-push-config.json

Fixes #3071 
Although this is WIP 👀 would still be helpful, @hiddeco. 🙏 
Apart from the git bits of this, this PR is the catalyst for the step execution engine to start distinguishing between errors/failures that are terminal and ones that can be retried. This seemed like the time, because once a merge conflict that requires manual resolution has been detected, there is no point in performing any retries, no matter what the retry policy says.
I tried to implement what we discussed offline, but I think you'll have some good constructive feedback on this.
r4r

fix(controller): git-push step: pull --rebase before push

---

docs/docs/35-references/10-promotion-steps.md

Fixes #2078 
Supersedes #3152 
This is the new, docs-only resolution of #2078.
Argo CD implemented enforcement of sync windows by the _App controller_ starting in v2.11.
All we need to do is advise users to use Argo CD v2.11+ if they care about sync windows and to set the timeout on the argocd-update step accordingly.
cc @jessesuen @blakepettersson

docs: update docs re: argocd sync windows

---

docs/docs/35-references/10-promotion-steps.md
internal/directives/helm_chart_updater.go
internal/directives/helm_chart_updater_test.go
internal/directives/helm_image_updater.go
internal/directives/helm_image_updater_test.go
internal/directives/yaml_updater.go
internal/directives/yaml_updater_test.go
internal/yaml/decode.go
internal/yaml/update.go
internal/yaml/update_test.go
internal/yaml/yaml.go
internal/yaml/yaml_test.go

This complements #3151.
#3151 uses tidwall/sjson for modifying JSON documents whilst preserving their existing formatting.
The keys/paths supported by that library use simple dot-separated notation. Dots can be escaped. Colons are used as a hint that a numeric-looking key part should be treated as a key in an object and not as an index in a sequence. Colons also can be escaped.
Examples:
* foo.bar --> [foo bar]
* foo\.bar --> [foo.bar]
* foo.2 --> [foo 2] (2 is an index in the sequence foo)
* foo.:2 --> [foo 2] (2 is a key in the object foo)
* foo\:bar --> [foo:bar]
-1 can be used as an index to indicate a desire to append to a sequence.
__This is slightly inconsistent with the syntax supported by our yaml-update step.__
* Indices are handled the way Helm does. e.g. foo.[2]
* Negative …

feat: make yaml-update syntax the same as json-update syntax

---

docs/docs/35-references/10-promotion-steps.md
go.mod
internal/directives/git_pr_opener.go
internal/directives/schemas/git-open-pr-config.json
internal/directives/zz_config_types.go
internal/gitprovider/azure/azure.go
internal/gitprovider/github/github.go
internal/gitprovider/github/github_test.go
internal/gitprovider/gitlab/gitlab.go
internal/gitprovider/gitprovider.go
ui/src/gen/directives/git-open-pr-config.json

feat: PR labels (#3002)

---

docs/docs/35-references/10-promotion-steps.md
internal/directives/file_deleter.go
internal/directives/file_deleter_test.go
internal/directives/schemas/delete-config.json
internal/directives/zz_config_types.go
ui/src/features/promotion-directives/registry/use-discover-registries.ts
ui/src/gen/directives/delete-config.json

Fixes https://github.com/akuity/kargo/issues/2860

feat: add promotion step to remove a file/directory

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

closes https://github.com/akuity/kargo/issues/2833
part of it was merged in https://github.com/akuity/kargo/pull/2963

chore: remove image updater info

---

docs/docs/30-how-to-guides/25-argo-cd-integration.md

closes https://github.com/akuity/kargo/issues/2440
I have made the documentation placement for the `kargo.akuity.io/authorized-stage` annotation in "Managing User Permissions" section because imo it is a key component in managing permissions between Kargo and Argo CD.
While I also considered options like a dedicated `annotation reference` guide or including it in `key concepts`, I believe current placement is most relevant. Please let me know if this location works or if there's an alternative section recommended.

docs: authorizing kargo stages to modify argo apps

---

internal/directives/argocd_updater.go
internal/directives/argocd_updater_test.go

fixes : #3163
1. Error Message Adjustment:
Changed the phrasing from "was not initiated by %q and not by %q" to "was initiated by %q and not by %q".
This directly states who initiated the operation (status.Operation.InitiatedBy.Username) and clarifies it wasn't initiated by the expected user (applicationOperationInitiator).

fix: incorrectly worded error message in argocd-update is corrected

---

ui/src/features/stage/verifications.tsx

fixes https://github.com/akuity/kargo/issues/3076
shows filter only if implicit verifications meta exist in recent verifications.
default not to show those.

fix(ui): implicit verification filter

---

ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx

Link was pointing relative to the current URL rather than to a repository. Reusing `urlForImage` function that was used for linking in the repo node already.
Before (See bottom of screenshot):
Now (See bottom of screenshot):

fix(ui): link to image repo correctly in Warehouse UI

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

in the warehouse when selecting git subscription the regex was:
`^\w+([-/]\w+)*$`
what didn't accept the branch name like: release-0.3
I have updated the warehouse branch regex to: `^\w+([-\/]\w+)*(-\d+\.\d+)?$`
so now it accept branch names:

fix: warehouse branch regex that was to limiting

---

charts/kargo/templates/controller/deployment.yaml

Addresses an issue introduced (by a review suggestion) in #3218. Without this, you will run into:
> spec.template.spec.volumes[0].name: Invalid value: "tmpData": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is `[a-z0-9]([-a-z0-9]*[a-z0-9])?`)

fix(chart): RFC 1132 compliant name for tmp mount

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Dockerfile

chore(deps): bump library/node from 22.8.0 to 22.13.0 (LTS)

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Dockerfile

chore(backport release-1.2): bump library/node from 22.8.0 to 22.13.0 (LTS)

---

.github/workflows/ci.yaml

This is so we don't waste time running the full battery of CI tests on a series of PRs we know will exclusively contain doc changes.
We can still gate PRs on Netlify successfully building a preview of the changes, as that is all configured independently of the Actions workflows.

chore: skip ci for prs opened against the newdocs branch

---

docs/docs/60-new-docs/80-release-notes/97-v1.2.0.md
docs/docs/60-new-docs/80-release-notes/98-v1.1.0.md
docs/docs/60-new-docs/80-release-notes/99-v1.0.0.md
docs/docs/60-new-docs/90-deprecations.md

Introduced a new deprecated items page in the documentation.

docs: deprecated notices for kargo

---

docs/docs/15-concepts.md

This PR fix the yaml indent typo in Warehouse's excludePaths example

fix: Indent typo in 15-concepts.md

---

internal/directives/helm_chart_updater.go
internal/directives/helm_chart_updater_test.go

Fixes: #3299
Fixes: #3298 
Fixes: #3290
---
The reason `/home/nonroot` is being touched, is that Helm has decided to do something odd within their download manager by not taking the configured value into account for the repository cache while trying to resolve a chart dependency for a repository that does not have a cache entry for the `index.yaml`.
Instead, it temporarily caches the index to an `index.yaml` with a random 20-byte name to the [environment variable-based cache path](https://github.com/helm/helm/blob/v3.17.0/pkg/helmpath/lazypath.go#L60), and then removes it as soon as it has resolved the chart URL for the version it is interested in.
Stack trace:
1. https://github.com/helm/helm/blob/v3.17.0/pkg/downloader/manager.go#L315
2. …

fix(directives): HTTP repo cache `helm-chart-update`

---

docs/docs/60-new-docs/50-user-guide/20-how-to-guides/25-argo-cd-integration.md
docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md

After chats with @krancour, we reached the conclusion that most Argo CD related things which we can properly document at this point (i.e. excluding sharding, for which we need the topology section) are already present.
Because of this, the changes here are minimal and limited to ensuring certain aspects of the `argocd-update` step (health checks) are brought more to the foreground when people are getting familiar with Kargo.

docs: improve Argo CD integration document

---

cmd/controlplane/api.go
cmd/controlplane/controller.go
cmd/controlplane/utils.go

This ensures that if the API server or controller is unable to determine if Argo CD or Argo Rollouts is installed (e.g. because of some transient Kubernetes API error), the respective service will fail to start instead of disabling the integration.
By doing this, the service will restart to get an accurate result once the API server is available again. Providing a more reliable result than the integrations not working for the lifetime of the Pod because of API server flakiness at boot time.

fix(cmd): improve Argo integration checks

---

docs/docs/60-new-docs/40-operator-guide/20-advanced-installation/30-common-configurations.md

@krancour: This had a bit more, but I discovered some overlap between your security documents and what I wrote. So, I am holding that part back until I have a clear view of what would still be required here. Besides this, I am absolutely open to any additional suggestions you have in mind.

docs: add common chart configuration options

---

ui/src/features/auth/oidc-login.tsx
ui/src/features/auth/token-renew.tsx

MS Entra ID (formerly Azure AD) implements OIDC and PKCE, but deviates from [RFC8414](https://datatracker.ietf.org/doc/html/rfc8414#section-2) (OAuth 2.0 Authorization Server Metadata) by failing to include the `code_challenge_method` in its metadata. This can create the impression that it does _not_ support PKCE.
Up to now, this has been the cause of a (previously unknown) incompatibility with our UI.
This PR adds an explicit exception to the expectation that `code_challenge_method` exists and includes the value `"S256"` for Entra ID only.
This is safe, as support for S256 is documented here: https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow

fix(ui): tolerate entra id RFC8414 deviation

---

internal/cli/cmd/update/update.go

Fixes outdated cli examples in the update command
- Need to use the `--name` flag when passing freight name
- Replaced `--alias` with `--new-alias` flag

chore(cli): fix update command example

---

internal/credentials/kubernetes/github/app.go
internal/credentials/kubernetes/github/app_test.go

Follows up on #3055 and #3059
cc @hiddeco
The issue was here:
```
if corruptInputErr := new(base64.CorruptInputError); !errors.As(err, &corruptInputErr) {
```
`&corruptInputErr` is a `**base64.CorruptInputError`, which `err` never is.
Rather than just delete the offending `&`, I've refactored this and added a test to be sure this is fixed, but I've also switched over to a different strategy for identifying whether we're dealing with a "raw" PEM-encoded PKCS1 or PKCS8 key (i.e. one not unnecessarily double-encoded). It seems this might actually be more reliable than guessing we have a PEM-encoded key whenever the input happens not to be a valid base64 encoding.
But please lmk if you see any problems with the new approach or if you have any ideas for making it more robust.

fix: fix faulty logic for handling possible double-encoding of github app private key

---

docs/docs/60-new-docs/40-operator-guide/20-advanced-installation/20-advanced-with-argocd.md

Added different ways to deploy Kargo using Argo CD. I stuck with the 3 main ways folks would do this using Argo CD. I stayed away from Umbrella Charts as I feel folks would manage `cert-manager` and `argo-rollouts` with their own Argo CD `Application`. (also I think having a "Kargo + Cert Manager + Argo Rollouts" Umbrella chart would be bad practice)

docs: Added Advanced installation with Argo CD doc

---

docs/docs/60-new-docs/40-operator-guide/10-basic-installation.md

Working on other docs today, I realized we ought not unwittingly invite readers to install Kargo with an admin password of `admin`.
The script that bootstraps the quick start still does use `admin` as a password, but here in the operator's guide, there's no reason not to have instructions for generating a password and signing key.

docs: add instructions for generating password and signing key to the basic install instructions

---

.gitattributes

Adding a .gitattributes file to normalize on LF for line endings in text files even if someone has their Git config set up to use CRLF.

chore: enforce LF line endings in git

---

docs/docs/60-new-docs/20-quickstart/index.md

We should have done this sooner... the wall of YAML in the quickstart is significantly reduced by leveraging `PromotionTask`s.

docs: update quickstart to use promo tasks

---

internal/api/list_credentials_v1alpha1.go
ui/src/features/project/credentials/credentials-list.tsx

fixes https://github.com/akuity/kargo/issues/3294 and API of credentials was previously returning generic secrets

fix: vertical view for secrets and filter credentials by label

---

ui/src/features/stage/stage-details.tsx

Previously it omits native fields, but now it queries raw yaml like warehouse live manifest

fix(ui): show raw stage manifest

---

charts/kargo/templates/NOTES.txt
charts/kargo/templates/_helpers.tpl

Fixes #3432 
This presents instructions for accessing Kargo that are based on the configuration options selected at install/upgrade time.
Some non-exhaustive examples:
```
helm install kargo charts/kargo \
--namespace kargo \
--create-namespace \
--set image.tag=v1.2.2 \
--set api.adminAccount.passwordHash='$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm' \
--set api.adminAccount.tokenSigningKey=iwishtowashmyirishwristwatch \
--wait
NAME: kargo
LAST DEPLOYED: Tue Feb  4 16:56:26 2025
NAMESPACE: kargo
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
.----------------------------------------------------------------------------------.
|     _                            _                    _          _ _             |
|    | | ____ _ _ __ __ _  ___    | |__  _   _     __ _| …
```

feat(chart): add NOTES.txt

---

charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/controller/deployment.yaml
charts/kargo/templates/dex-server/deployment.yaml
charts/kargo/templates/garbage-collector/cron-job.yaml
charts/kargo/templates/management-controller/deployment.yaml
charts/kargo/templates/webhooks-server/deployment.yaml

Fixes: #3444
They are all set to one, based on the Kubernetes documentation[1] that states:
> The `divisor` field is optional and has the default value of `1`.
> A divisor of `1` means cores for cpu resources, or bytes for memory
> resources.
[1]: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#store-container-fields

fix(chart): set `divisor` for `resourceFieldRef`s

---

internal/api/option/auth.go
internal/api/option/auth_test.go
internal/api/option/option.go

Fixes #3455
#3455 reports the API server crashing during startup if OIDC is misconfigured. tbh, this was the desired behavior. It's hard to tell the difference between misconfiguration (e.g. incorrect issuer URL) and transient errors (common if using Dex and the API server starts faster than Dex), so the k8s way is to let it die and try to start again with hopes of success, however...
1. OIDC misconfiguration is common.
1. If the API server is down, the UI is also inaccessible. If a user doesn't have access to the logs and cannot reach the UI, there is no insight at all into this common problem.
This change allows the only interaction between the API server and the IDP (retrieval of the keyset for token validation) to fail gracefully and be retried just-in-time on future attempts to …

feat: surface likely oidc misconfiguration through ui

---

docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md

While going through the docs and using an example, I noticed that I was getting an error for using
```yaml
spec:
subscriptions:
- helm:
repoURL: https://charts.example.com
name: my-chart
semverConstraint: ^1.0.0
```
After noticing that creating a Helm chart warehouse via the UI, it should be
```yaml
spec:
subscriptions:
- chart:
repoURL: https://charts.example.com
name: my-chart
semverConstraint: ^1.0.0
```
This simply fixes the example.

docs: Fix example for Helm warehouses

---

internal/directives/http_requester.go
internal/directives/http_requester_test.go

If any step adds an int to an output map, it will panic when we attempt a deep copy.
HTTP status codes are ints.
This is a short-term fix until we fix the deep copy routine so that it reliably works for ints.

fix: short term fix for deep copy failing on http status code

---

internal/credentials/kubernetes/ecr/managed_identity.go

Fixes #3482
when falling through the non-project-specific role, the AWS config has a different region set than when using the project-specific-role.
for the case where the region where kargo is running is different than the region for the ECR, this causes auth token errors.
fix this by setting the region for the non-project-specific role codepath.
Signed-off-by: Joel Diaz <jo.diaz@celonis.com>

fix: set region on default config for AWS creds

---

internal/directives/http_requester.go
internal/directives/http_requester_test.go

This adds the HTTP response code to the error message in case of failures, and provides a `trace` level log message with the HTTP response. Combined, this should make it easier to debug a variety of error scenarios a user may run into when trying to write a `http` directive.

fix: improve debug information `http` step

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/delete.md
internal/directives/file_deleter.go
internal/directives/file_deleter_test.go
internal/directives/schemas/delete-config.json
internal/directives/zz_config_types.go
ui/src/gen/directives/delete-config.json

Fixes: #3497
This makes a `delete` step succeed when a file or directory that is
attempted to be removed already does not exist, instead of failing.
In case this behavior is undesired, and the promotion has to fail
when the path does not exist, the `strict` configuration option can
be set to `true`.

feat!: make `delete` directive non-strict by default 

---

internal/expressions/json_templates.go

This PR fixes an issue where Kargo incorrectly interprets a PR number as a boolean if the PR number is "1". This causes the `gh-wait-for-pr` promotion step to fail with the error:
`invalid type, expected number, given boolean`
- If a PR number evaluates to "1", Kargo mistakenly treats it as a boolean (true).
- The PR itself is created successfully and can be merged in GitHub, but Kargo fails to detect it, preventing the promotion from proceeding.

fix: invalid type conversion for the `git-wait-for-pr` step

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Dockerfile
Dockerfile.dev
go.mod

Manual backport of dependency updates to `main` to ensure the patch release is cleared from CVEs.
```
ghcr.io/hiddeco/kargo:1.2.3-rc.721e0c1f (wolfi 20230201)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

chore(backport release-1.2): chore(deps): bump Go and Node versions

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/json-parse.md
internal/directives/json_parser.go
internal/directives/json_parser_test.go
internal/directives/schemas/json-parse-config.json
internal/directives/zz_config_types.go
ui/src/gen/directives/json-parse-config.json

closes https://github.com/akuity/kargo/issues/3240
`parse-file` step allows users to specify file paths and extract specific values using expressions. The `fromExpression` field accepts direct expressions without `${{}}` wrappers, as evaluation happens within the step logic itself.
eg.
```
steps:
- uses: json-parse
config:
path: "path/to/file1.json"
outputs:
- fromExpression: "object.version"
name: "version1"
- fromExpression: "object.name"
name: "name1"
```

feat: json-parse promotion step

---

internal/gitprovider/gitea/gitea.go
internal/gitprovider/gitea/gitea_test.go
internal/gitprovider/github/github.go
internal/gitprovider/github/github_test.go
internal/gitprovider/gitlab/gitlab.go
internal/gitprovider/gitlab/gitlab_test.go

Follow up on https://github.com/akuity/kargo/pull/3320#pullrequestreview-2587924812
This ensures that if explicitly defined, a connection over HTTP can still be made instead of silently enforcing HTTPS. This is particularly useful when e.g. running a self-hosted Gitea or GitLab instance in a homelab environment without a proper TLS configuration.

fix(gitprovider): use provided scheme for API calls

---

docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
docs/docs/50-user-guide/20-how-to-guides/60-verification.md
docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md

Adds documentation for:
- #3320
- #2673 
- #3257

docs: documentation for new features

---

api/v1alpha1/generated.proto
api/v1alpha1/stage_types.go
charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
ui/src/gen/v1alpha1/generated_pb.ts

Fixes: #3548 
This ensures that the newly introduced `availabilityStrategy` is not forcefully marked as `required` but instead allows it to be left unspecified, and then (code)automagically defaults to `OneOf`.
The issue also mentions a historical problem with the `semverConstraint` field being required (and arguably, being confusing as it defaults to `true` even if the field has no further impact on the configured selection strategy, i.e. it does not target SemVers) — I do not see an immediate path forward here to resolve this, as protobuf isn't familiar with e.g. nullable booleans.

fix(api): make `availabilityStrategy` optional 

---

internal/controller/stages/regular_stages.go
internal/controller/stages/regular_stages_test.go

closes https://github.com/akuity/kargo/issues/3191

fix: make stage health unknown when last promotion failed

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
internal/directives/schemas/git-commit-config.json
internal/directives/zz_config_types.go
ui/src/gen/directives/git-commit-config.json

:warning: **This marks `messageFromSteps` of the `git-commit` step as deprecated and schedules it for removal in `v1.5.0`.**
The field was overlooked when we deprecated the other `<thing>FromStep` fields. Likewise functionally can be achieved using expressions and a multiline message, refer to the [tip in this section](https://docs.kargo.io/user-guide/reference-docs/promotion-steps/git-commit#composed-commit-message) for more information.

chore(directives): deprecate `messageFromSteps`

---

internal/api/dex/proxy.go
internal/api/option/auth.go
internal/cli/client/client.go
internal/cli/cmd/login/login.go
internal/gitprovider/gitea/gitea.go
internal/gitprovider/github/github.go
internal/gitprovider/gitlab/gitlab.go

Fixes: #3569
This PR refactors our HTTP client and transport initialization across the codebase to leverage Hashicorp's `go-cleanhttp` library. Previously, we manually constructed HTTP transports with inconsistent configurations, which could lead to connection leaks and suboptimal performance.
We now apply `cleanhttp.DefaultPooledTransport()` for our reverse proxy use case where connection reuse is beneficial, while using `cleanhttp.DefaultTransport()` and `cleanhttp.DefaultClient()` for API clients and Git providers to maintain proper tenant isolation.
Additionally, expected default configurations like HTTP/S proxy configurations, etc. are now properly accounted for.

fix: improve construction of HTTP transports

---

internal/directives/kustomize_image_setter_test.go
internal/directives/schemas/kustomize-set-image-config.json

After `fromOrigin` fields were removed, not having either defined could result in the tag of the `image` unexpectedly being set to `latest`. To avoid this, explicitly require either `tag` or `digest` to be set.

fix: require tag or digest for kustomize-set-image

---

internal/credentials/kubernetes/ecr/access_key.go
internal/credentials/kubernetes/ecr/access_key_test.go
internal/credentials/kubernetes/ecr/managed_identity.go
internal/credentials/kubernetes/gar/service_account_key.go
internal/credentials/kubernetes/gar/service_account_key_test.go
internal/credentials/kubernetes/gar/workload_identity_federation.go
internal/credentials/kubernetes/github/app.go
internal/credentials/kubernetes/github/app_test.go

fix(credentials): comparable constructor return types

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
docs/old-docs/35-references/10-promotion-steps.md

https://github.com/akuity/kargo/pull/2628 made `releaseName` mandatory, but docs still say it is optional.

docs: releaseName is now required by `helm-template`

---

internal/server/list_warehouses_v1alpha1.go

This may or may not help with the DAG being rendered more consistently, but either way, these should have been sorted all along.

fix(api): sort warehouses when listing

---

internal/directives/simple_engine_promote.go
internal/directives/simple_engine_promote_test.go

Fixes: #3636 
Before this change, it was assumed that `compose-output` used within a PromotionTask would not be used within this task itself. Because of this, the output of a `compose-output` step was only made available under the task namespace but not under the step's own alias.
This caused an issue when trying to reference the output of a `compose-output` step from another step in the same task using expressions like `${{ task.outputs.boo.path }}`, resulting in a "cannot fetch path from <nil>" error.
This PR changes the behavior to always store the step output under the step's alias, and then additionally store it under the task namespace if it's part of a task. This ensures that the output is consistently available regardless of how it's referenced.

fix(directives): compose-output available to task

---

api/v1alpha1/generated.proto
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
ui/src/gen/api/v1alpha1/generated_pb.ts
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json

This updates the branch validation to simply ensure it:
1. Starts with an alphanumeric character
2. Contains only alphanumeric characters, dots, underscores, hyphens, and slashes
3. Doesn't end with a slash or dot (but hyphens and underscores _are_ allowed)
4. Doesn't exceed the maximum length of most Git providers (GitHub, etc.)
As the previous pattern continued to give problems. For example, when a name includes a double dash (`--`).

fix(api): update Git branch validation

---

docs/src/components/VersionDropdown.css
docs/src/components/VersionDropdown.js

added version width and title
---
fixed dropdown component
before:
after:

fix: responsive versioned dropdown

---

internal/cli/cmd/login/login.go
internal/cli/cmd/login/login_test.go
internal/cli/config/config.go

This brings two improvements:
- When providing the server address, the scheme is now optional when connecting to a HTTPS endpoint. (I.e. `kargo login localhost:8080` works as long as it serves an HTTPS endpoint).
- It remembers the last authentication method, and you can run `kargo login` to connect to the last used server with the last used method.

feat(cli): improve UX (re-)login

---

charts/kargo/templates/_helpers.tpl
charts/kargo/templates/api/deployment.yaml
charts/kargo/templates/controller/deployment.yaml
charts/kargo/templates/dex-server/deployment.yaml
charts/kargo/templates/garbage-collector/cron-job.yaml
charts/kargo/templates/management-controller/deployment.yaml
charts/kargo/templates/webhooks-server/deployment.yaml

This changes the chart to set `GOMAXPROCS` to `requests.cpu` when `limits.cpu` is not present, to prevent it from defaulting to all cores present on the node.
For in depth information about this change, see: https://kanishk.io/posts/cpu-throttling-in-containerized-go-apps/
> If you do not set CPU limits, I’d still recommend setting your GOMAXPROCS somewhere around 1x or 2x your CPU request to get predictable performance.

fix(chart): GOMAXPROCS set request if limit absent

---

internal/api/stage.go
internal/api/stage_test.go
internal/api/warehouse.go
internal/api/warehouse_test.go
internal/controller/stages/regular_stages_test.go

I stumbled upon this bug today and it seemed serious enough to fix immediately.
It's been around since #3100, when soak time was first introduced.
The original strategy for assessing whether soak time had elapsed involved ensuring verification time was in the sufficiently distant past, but that offered no guarantee of how long the Freight had actually _spent_ in the Stage in question, which was exposed during review. The PR was subsequently amended to track how long a piece of Freight actually spent in any given Stage...
Except, as it turns out, I only actually fixed it for `stage.IsFreightAvailable(...)`, which answers whether a single piece of Freight is available to a given Stage.
I _missed_ the `ListFreightFromWarehouse()` which lists all Freight from a given Warehouse, with optional …

fix: soak time bug

---

api/v1alpha1/stage_helpers.go
api/v1alpha1/stage_helpers_test.go
api/v1alpha1/warehouse_helpers.go
api/v1alpha1/warehouse_helpers_test.go
internal/controller/stages/regular_stages_test.go

Manual backport of #3731 to `release-1.3` due to merge conflicts.

chore(backport release-1.3): fix: soak time bug

---

api/v1alpha1/freight_types.go
api/v1alpha1/stage_types.go
api/v1alpha1/stage_types_test.go
internal/api/stage.go
internal/api/warehouse.go
internal/api/warehouse_test.go

#3257 introduced availability strategies (verified + soaked in any upstream vs all upstreams).
The change was properly implemented as new criterion when _listing_ available Freight, but was overlooked in the function that answers whether a single piece of Freight is available to a given Stage.
The effect is that Freight that was not verified and adequately soaked in _all_ upstream stages may sometimes have been deemed available to a Stage if it met availability criteria in _any_ upstream stage.
This PR fixes that.

fix: always honor availability strategy

---

.github/workflows/ci.yaml

Like #1616, but now accounting for the existence of multiple modules, each with their own `coverage.txt`.

chore(ci): remove generated code from coverage reports

---

internal/expressions/json_templates.go
internal/expressions/json_templates_test.go

Fixes #3743 
Without the `quote()` function we make available in expressions, many values that should be strings will be misinterpreted as other types.
Example:
```
config:
meaningOfLife: ${{ 42 }}
```
This becomes the following JSON: `{"meaningOfLife": "${{ 42 }}"}`
After evaluation of expressions, you're left with: `{"meaningOfLife": 42}`
(Strings that _can_ be interpreted as something else -- bool, number, object, etc. -- _are_, which is behavior familiar to anyone who works with YAML.)
If you really want that to be a string, you use `quote()`:
```
config:
meaningOfLife: ${{ quote(42) }}
```
This becomes the following JSON: `{"meaningOfLife": "${{ quote(42) }}"}`
After evaluation of expressions, you're left with: `{"meaningOfLife": "42"}`
Perfect.
A problem arises when the value passed …

fix: make quote() func in expressions not double-quote strings

---

docs/docs/50-user-guide/20-how-to-guides/10-logging-in/index.md

This pull request includes a small change to the `docs/docs/50-user-guide/20-how-to-guides/10-logging-in/index.md` file. The change corrects a grammatical error in the documentation.

chore(docs): fix typo in "Logging In"

---

docs/docs/50-user-guide/60-reference-docs/40-expressions.md
internal/controller/freight/finder.go
internal/controller/freight/finder_test.go

Resolves https://github.com/akuity/kargo/issues/3647
The `imageFrom`, `chartFrom`, `commitFrom` expr functions will now return `nil` instead of returning error if a Freight could not be found. This supports the use case where a PromoTask could be re-used for multiple types of artifact promotions (image/commit/chart) using a conditional like:
```yaml
- uses: yaml-update
if: ${{ imageFrom( vars.image ) != nil }}
```

fix!: freight from funcs return nil instead of error when freight not found

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
internal/promotion/runner/builtin/helm_template_runner.go
internal/promotion/runner/builtin/helm_template_runner_test.go
internal/promotion/runner/builtin/schemas/helm-template-config.json
pkg/x/promotion/runner/builtin/zz_config_types.go
ui/src/gen/directives/helm-template-config.json

implements #3753 
have it working locally, will update/add tests
first time hacking on kargo internals, hopefully in the right direction

feat: support passing dynamic key-value pairs in helm-template step

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/compose-output.md

Outputs from previous steps are available from `task` variable, see also [Expression Language](https://docs.kargo.io/user-guide/reference-docs/expressions)

fix(docs): correctly reference outputs

---

internal/controller/promotions/promotions.go
internal/controller/promotions/promotions_test.go
internal/promotion/mock_step_runner.go
internal/promotion/promotion_test.go
internal/promotion/registry.go

Closes https://github.com/akuity/kargo/issues/3663
Previously we were hard-coding the requeue interval to 5 minutes.
This sets a lower requeue interval if the target timeout is before 5 minutes from now.

feat:  improve step timeout accuracy

---

charts/kargo/templates/controller/cluster-roles.yaml

This was meant to be included in #3865
cc @gdsoumya for the permissions change.

fix(chart): give controller cluster-wide configmap reads

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/compose-output.md

The example provided for `compose-output` contains multiple syntax errors
- As with #3862, outputs are wrongly referenced throughout.
- Nesting evaluation in a `quote()` is not supported, thus using string concatenation instead.

fix(docs): Make compose-output example work

---

internal/server/refresh_stage_v1alpha1.go
internal/server/refresh_warehouse_v1alpha1.go
internal/server/refresh_warehouse_v1alpha1_test.go

Closes https://github.com/akuity/kargo/issues/3823
This PR implements implementation option 1 stated in the issue.
By passing the internal client to these refresh methods, the auth wrapper client hooks don't run.
Also, didn't see any coverage for `internal/server/refresh_warehouse_v1alpha1.go` for so added a test file for this as well.

feat: bypass patch perms for refresh of stages and warehouses

---

ui/src/features/project/list/project-list-filter.tsx
ui/src/features/project/list/projects-list.tsx

Two issues with project filter input are fixed. (You may also see it as one issue and a feature)
In the case that the filter result was returned empty, the search bar would disappear, blocking the user from resetting the search. The only fix in this situation was to remove the `projects-filter` cookie to get the search bar back.
The image below shows how it would like before, if you would search for a non-existing project name:
This one was more of an annoying thing because previously you had to manually click on the search button to change the search filter. Now just hitting enter will do that.
I've checked the other interactions with the search bar like selecting different items and all still work as expected.
P.S. I've uploaded a screen recording of how it looks with this PR in …

fix(ui): projects filter ui

---

api/v1alpha1/generated.proto
api/v1alpha1/stage_types.go
api/v1alpha1/warehouse_types.go
charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
docs/docs/50-user-guide/60-reference-docs/40-expressions.md
docs/old-docs/35-references/20-expression-language.md
internal/controller/warehouses/images.go
internal/controller/warehouses/warehouses.go
ui/src/features/assemble-freight/assemble-freight.tsx
ui/src/features/assemble-freight/image-table.tsx
ui/src/gen/api/v1alpha1/generated_pb.ts
ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json

closes https://github.com/akuity/kargo/issues/3850
This PR **only deprecates** `gitRepoURL` field.
I have [created this separate issue](https://github.com/akuity/kargo/issues/3901) for tracking the Removal of the same in `v1.7.0`

chore: deprecate gitRepoURL in API and UI

---

docs/docs/50-user-guide/50-security/20-access-controls/index.md

* Explains the existence and purpose of the `promote` verb
* Adds two examples for declarative RBAC:
1. How to create custom role that gives only promote privileges to a subset of Stages
2. How to declarative bind OIDC claims to built-in roles (e.g. `kargo-admin`) using a second ServiceAccount/RoleBinding

docs: explain `promote` verb and add RBAC examples

---

internal/controller/stages/regular_stages.go
internal/controller/stages/regular_stages_test.go

This fixes the issue reported in https://github.com/akuity/kargo/pull/3053#issuecomment-2823434333, which was introduced when we changed the health status from `HealthStateUnhealthy` to `HealthStateUnknown` for failed Promotions (in #3191).
The change created a deadlock in the Stage controller where stages with `Unknown` health (resulting from a failed Promotion) couldn't start a new Promotion due to the condition `stage.Status.Health == nil || stage.Status.Health.Status != kargoapi.HealthStateUnhealthy`.
By changing the latter bit to an explicit `stage.Status.Health.Status == kargoapi.HealthStateHealthy`, we only block a Promotion (and wait for verification to complete) in scenarios where we can still expect progress.
The rest of the controller logic maintains all other safety checks, …

fix(controller): allow promo when health is unknown

---

api/v1alpha1/labels.go
internal/promotion/simple_engine.go
internal/promotion/simple_engine_test.go
internal/server/delete_project_secret_v1alpha1.go
internal/server/delete_project_secret_v1alpha1_test.go
internal/server/list_project_secrets_v1alpha1.go
internal/server/list_project_secrets_v1alpha1_test.go
internal/server/update_project_secret_v1alpha1.go
internal/server/update_project_secret_v1alpha1_test.go

This was already scheduled for `v1.4.0`.

chore: remove deprecated `ProjectSecretLabelKey`

---

docs/docs/20-quickstart/index.md
docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
docs/docs/50-user-guide/60-reference-docs/40-expressions.md
docs/old-docs/20-quickstart.md
docs/old-docs/30-how-to-guides/14-working-with-stages.md
docs/old-docs/35-references/10-promotion-steps.md
docs/old-docs/35-references/20-expression-language.md
internal/promotion/runner/builtin/git_commiter.go
internal/promotion/runner/builtin/git_commiter_test.go
internal/promotion/runner/builtin/schemas/git-commit-config.json
pkg/x/promotion/runner/builtin/zz_config_types.go
ui/src/gen/directives/git-commit-config.json

Scheduled for removal in `v1.5.0`: https://docs.kargo.io/release-notes/deprecations#deprecations

chore: remove deprecated `messageFromSteps` field

---

internal/controller/git/bare_repo.go
internal/controller/git/bare_repo_test.go
internal/controller/git/base_repo.go
internal/controller/git/repo.go
internal/controller/git/repo_test.go
internal/controller/git/work_tree.go
internal/controller/git/work_tree_test.go
internal/promotion/runner/builtin/git_cloner_test.go
internal/promotion/runner/builtin/git_commiter_test.go
internal/promotion/runner/builtin/git_pusher_test.go

Related to #3813 / #3922
This updates our internal `git` package such that any signing key included in optional author information passed to a repo's `Commit()` method will actually be used / override any signing key specified at clone-time, or if applicable, override the system-level signing key.
Prior to this PR, we already allowed for override of author name and email at commit-time. This PR just extends the behavior to signing keys. It's essentially an oversight that it didn't already do this.
The way this works now is pretty simple.
Prior to this PR, a helper method called `setupAuthor()` was run just prior to cloning a repo and that helper "globally" configured git with name, email, and signing key -- "global" in quotes because all commands are run with the `HOME` env var set to a …

feat: allow gpg key override at commit-time

---

cmd/controlplane/controller.go
cmd/controlplane/garbage_collector.go
cmd/controlplane/management_controller.go
cmd/controlplane/webhooks.go

This allows the configuration of the `METRICS_BIND_ADDRESS` environment variable (e.g. `:8080`) to enable controller-runtime's Prometheus metrics endpoint, providing a range of standard metrics as documented here: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics#pkg-constants
This is the bare minimum required to facilitate #3701.

feat(cmd): support configuring metrics bind address

---

docs/docs/40-operator-guide/40-security/20-openid-connect.md

The doc mentions `api.oidc.viewers` everywhere, but the example snippet uses `api.oidc.viewers` (note the missing S).
The expected key being `viewers` is confirmed by the Helm Chart parameters doc: https://github.com/akuity/kargo/blob/f001566652b001b9c2fec628d2df130e145a5ddb/charts/kargo/README.md?plain=1#L116

docs(oidc-setup): fix wrong example (viewer→viewerS)

---

docs/docs/50-user-guide/20-how-to-guides/60-verification.md

Based on CRD https://github.com/akuity/kargo/blob/main/charts/kargo/resources/crds/kargo.akuity.io_stages.yaml#L298
requiredSoakTime is part of sources and not requestedFreight

docs: correctly document `requiredSoakTime` field

---

ui/src/features/project/pipelines/freight/filter-timerange-utils.ts
ui/src/features/project/pipelines/freight/freight-card.tsx
ui/src/features/project/pipelines/graph-filters.tsx
ui/src/features/project/pipelines/nodes/stage-node.tsx
ui/src/features/project/pipelines/nodes/warehouse-node.tsx

- Numbers in freight boxes should only be visible for > 2
- Stage details can be opened by click on node as well
- Stage stacking filter is only visible when it can be used (ie. not in small pipelines)
- Remove "1 Minute" timerange option

chore: pipeline view updates

---

ui/src/features/project/pipelines/graph/custom-node.tsx
ui/src/features/project/pipelines/nodes/stacked-nodes.tsx
ui/src/features/project/pipelines/nodes/stage-node.tsx

This is related to React Flow default behaviour. All nodes are in a draggable state. It caused button-click problems.

fix(ui): When moving a cursor, buttons in nodes don't work

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/governance.yml

Fixes #3916
Also adjusts some labels to align better with all of the Kargo's different areas of concern.
* `api` always _meant_ "api server," but was too easily confused with `crds` -- which are their own sort of API.
* `controller` has never adequately distinguished between the regular/distributed controller and the management controller that runs in the control plane only.
* After #3985, we deal with more than one kind of webhook, making it worthwhile to distinguish between "kubernetes webhooks" and "external webhooks."

chore: minor project governance updates

---

ui/src/features/settings/cluster-promotion-tasks/cluster-promotion-tasks.tsx
ui/src/pages/settings.tsx

Fixes a typo where we say `Verificaion` instead of `Verification`.
Also it mentions a "project" even though it is a system level configuration, not project

fix: typo on verifications and correct cluster promo tasks message

---

api/v1alpha1/promotion_types.go
internal/kargo/promotion_builder.go
internal/kargo/promotion_builder_test.go
internal/promotion/simple_engine.go
internal/promotion/simple_engine_test.go

Fixes #3402
This PR assigns generated step aliases as a `promotionTemplate` and tasks it references are expanded instead of doing so just-in-time.
This allows for slightly easier and easier-to-follow bookkeeping in terms of step execution metadata.
More significantly, it allows any error messages we build that involve steps to use aliases instead of indices. Indices, according to #3402, were confusing because the UI didn't display them and the question of being 0-based vs 1-based was possibly also the source of some confusion. This change alleviates all of that.

feat: improve step alias error messages

---

cmd/controlplane/external_webhooks.go

Fixes
```
time="2025-05-07T20:30:46Z" level=info msg="Starting Kargo External Webhooks Server" GOMAXPROCS=16 GOMEMLIMIT=32805588992 commit= version=devel+unknown.dirty
time="2025-05-07T20:30:46Z" level=error error="error registering warehouse by repo url indexer: no kind is registered for the type v1alpha1.Warehouse in scheme \"pkg/runtime/scheme.go:100\""
```
This is due to not adding custom types to the runtime scheme before registering indices

fix: runtime scheme error

---

docs/docs/50-user-guide/50-security/30-managing-credentials.md

The `awsRegion` field is necessary when using static, long-lived credentials to auth to ECR

docs: aws credentials Secret requires awsRegion field

---

internal/cli/cmd/delete/project_config.go
internal/cli/cmd/get/project_config.go

Fixes a mistake in #4067.
The new sub-commands mistakenly called `projectconfiguration`, although `projectconfig` is actually the official name for the new type.

fix(cli): fix get + delete projectconfig commands

---

internal/server/rbac/policy_rules.go

This fix is so that viewing and editing "roles" (Kargo managed SA/Role/RoleBinding trios) in the project settings page does not error out on previously unknown/invalid type ProjectConfig.

fix(api-server): add projectconfig to types understood by rbac policy normalization logic

---

internal/controller/git/repo_test.go
internal/controller/git/work_tree.go
internal/promotion/runner/builtin/git_commiter_test.go
internal/promotion/runner/builtin/git_pr_opener.go

This ensures that the full body of the commit message is available (for example, when creating a pull request) instead of just the title.

fix(git): get full commit message body

---

docs/docs/50-user-guide/30-patterns/index.md

Updating text to focus on why rendered branches *isn't* GitFlow

Update text about GitFlow

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
internal/promotion/runner/builtin/git_pr_opener.go
internal/promotion/runner/builtin/git_pr_opener_test.go
internal/promotion/runner/builtin/schemas/git-open-pr-config.json
pkg/x/promotion/runner/builtin/zz_config_types.go
ui/src/gen/directives/git-open-pr-config.json

This adds support for a custom `description` when opening a pull request using `git-open-pr`:
```yaml
steps:
- uses: git-open-pr
config:
title: Deploy to ${{ ctx.stage }}
description: |
My custom message
```

feat(runner): support custom PR description 

---

internal/promotion/runner/builtin/helm_chart_updater.go
internal/promotion/runner/builtin/schemas/yaml-update-config.json
internal/promotion/runner/builtin/yaml_updater.go
internal/promotion/runner/builtin/yaml_updater_test.go
internal/yaml/quote.go
internal/yaml/quote_test.go
internal/yaml/yaml.go
internal/yaml/yaml_test.go
pkg/x/promotion/runner/builtin/zz_config_types.go
ui/src/gen/directives/yaml-update-config.json

Fixes #4099
#4099 was probably introduced when a different bug was closed by #3794.
This fix does the following:
- Adds a utility function for quoting strings intended for use as values in YAML files as necessary.
i.e. If you have a string that looks like a number, you get back the original string enclosed in quotes. Anything else, including non-string values are returned as-is.
- Make the `internal/yaml` package able to set non-string values.
It only did strings before. If it was a string that looked like a number, you got it without any extra quotes that would hint to a YAML parser that the value should be treated as a string. Because it _only_ worked with strings there wasn't any way to _know_ whether the value should be treated as a string or other type. It _used_ to rely on extra …

fix(controller): make yaml-update quote numeric-looking strings as necessary

---

docs/docs/50-user-guide/60-reference-docs/40-expressions.md

Closes #4045
The docs for using secrets in expressions were specifying that all Kubernetes Secrets in the Promotion's Project are available in expressions. This is not true, as secrets need to be labeled a certain way by adding the label key `cred-type` and setting it to `generic`. I have reworded the docs to include a reference to the label key and added a link to learn more about managing generic secrets.
Furthermore I have made some small changes to the docs to comply with Markdown best-practices.
As the `Managing Other Secrets` docs are currently under construction and now linked to from multiple pages, I’d like to open an issue to track the creation of that page. Understanding what generic secrets are and how they can be used in expressions is crucial for effectively working with …

docs: clarify that secrets must be labeled a certain way to be available in expressions

---

internal/expressions/function/functions.go
internal/expressions/function/functions_test.go
internal/promotion/promotion.go

Fixes #4154
PromotionStepStatus needs to be cast as a string to be successfully compared to a string.
This PR also updates the status() func to be usable within the context of a task.

fix(controller): fix two bugs in evaluation of status() func in expressions

---

internal/indexer/indexer.go
internal/indexer/indexer_test.go

Fixes: #4187
The context used by the indexer to build up a (minimal) evaluated version of the step configuration did not have any information about Freight (references) set. Given variables are allowed to use expr-lang functions, which may make use of this information (e.g., `getImage()`), this could result in unexpected issues.
The quick fix is to enrich the context with this information. But this indexer continues to be a candidate to be revised in full...

fix(indexer): enrich context ArgoCD App indexer

---

api/testing/regexp.go
api/v1alpha1/generated.proto
api/v1alpha1/promotion_types.go
api/v1alpha1/regexp_test.go
api/v1alpha1/stage_types.go
api/v1alpha1/testhelper/regexp.go
api/v1alpha1/warehouse_types.go
internal/controller/git/work_tree_test.go
ui/src/gen/api/v1alpha1/generated_pb.ts

From [this comment](https://github.com/akuity/kargo/pull/4048#discussion_r2082458194):
> Anything you are willing to contribute to move the needle on making regexes more reliable and more thoroughly tested is welcome.
I had a go at this:
* It uses go's AST to pull in the source code of the types file
* The field in question gets a "// +akuity:IsGitRepoURL" comment
* The test reads the source code, looks for the comment
* Extracts the regexp
* Runs the regexp against a table test
I think it pointed out some interesting edge cases (see the table tests)
It also verifies that the two RepoURLs that point to git are identical.

fix(api): verify RepoURL validation

---

internal/controller/promotions/promotions_test.go
internal/promotion/simple_engine.go
internal/promotion/simple_engine_test.go
pkg/promotion/mock_step_runner.go

Branched off from another local branch that was getting out of hand with other engine-related refactoring.
This should address (at least a part of) #4072, and it works because we catch the panic within the engine. By doing this, we can still construct a `Result` to return to the reconciler, which will then propagate this into the actual status of the Promotion.
This detachment (or separation of concerns) is the primary reason why [the `recover()` within the reconciler itself](https://github.com/akuity/kargo/blob/e53abcca8a37c4d623400391c69359d154f8725e/internal/controller/promotions/promotions.go#L308-L318) did not have an effect. Arguably, this also means it is a potential candidate for removal, as I doubt it will be of much use after this has been merged.

fix(runner): step panic recovery within engine

---

internal/controller/promotions/promotions_test.go
internal/promotion/simple_engine.go
internal/promotion/simple_engine_test.go
pkg/promotion/mock_step_runner.go

Manual backport of #4169 due to merge conflicts.

chore(backport release-1.5): fix(runner): step panic recovery within engine

---

docs/docs/20-quickstart/index.md

closes https://github.com/akuity/kargo/issues/4173
depends on: https://github.com/akuity/kargo/pull/4213

docs: remove auto-refresh notice to show new freight

---

docs/package.json
docs/plugins/gtag/package.json
docs/plugins/gtag/pnpm-lock.yaml
docs/pnpm-lock.yaml

Dependabot has raised vulnerability alerts related to the current Docusaurus version, so we're upgrading it to address those issues.

chore: docusaurus version 3.7.0

---

cmd/controlplane/api.go
cmd/controlplane/external_webhooks.go

`HOST` was a poorly chosen env var name that I regret. I regard this as a non-breaking change because it's not now, and never was, configurable by the chart. (When running in k8s, the bind address, should really _always_ be `0.0.0.0`.) This only would have ever affected anyone attempting to run a server component as a native process and that's not really something we've ever officially supported.
cc @fuskovic

refactor: fix env var with a poorly chosen name

---

api/v1alpha1/generated.proto
api/v1alpha1/project_config_types.go
charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
internal/controller/management/projectconfigs/project_configs.go
internal/controller/management/projectconfigs/project_configs_test.go
internal/webhook/external/github_test.go
internal/webhook/external/path.go
internal/webhook/external/server_test.go
internal/webhook/kubernetes/projectconfig/webhook.go
internal/webhook/kubernetes/projectconfig/webhook_test.go
ui/src/gen/api/v1alpha1/generated_pb.ts
ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json

Closes https://github.com/akuity/kargo/issues/4227
Also Closes https://github.com/akuity/kargo/issues/4280

feat: validate webhook receiver name uniqueness + add webhook receiver name to hashed path

---

internal/controller/management/projectconfigs/project_configs.go

I noticed the webhook receiver URL rendering with a missing forward slash in the protocol scheme.
e.g.
`https:/...`
instead of:
`https://...`
I found `path.Join` was removing it and the URL rendered correctly after using `url.JoinPath` instead.

fix: missing forward slash

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
internal/promotion/runner/builtin/git_cloner.go
internal/promotion/runner/builtin/git_cloner_test.go
internal/promotion/runner/builtin/schemas/git-clone-config.json
pkg/x/promotion/runner/builtin/zz_config_types.go
ui/src/gen/directives/git-clone-config.json

closes https://github.com/akuity/kargo/issues/4112
as a part of this I will extend the `git-clone` step to output the commit hash for each checkout. since a single `git-clone` operation can have multiple `checkout` entries (each potentially pointing to a different HEAD), we need a way to reference each commit individually:
1. adding an optional `as` field to each `checkout` block to define a logical alias:
```yaml
checkout:
- branch: main
path: ./main
as: source
- branch: my-rendered-branch
path: ./rendered
create: true
as: target
```
2. the `git-clone` step will emit an output map `commits` containing the resolved HEAD commit hash for each checkout, keyed by `as` if set, otherwise by the `path`:
```json
"commits": {
"source": "sdfsdfs",
"target": "sdfsdfs"
}
```
or (fallback)
-> this …

feat: commits in git clone output

---

ui/src/features/project/pipelines/nodes/stage-node.tsx
ui/src/features/project/pipelines/nodes/use-get-upstream-freight.ts

fixes this https://github.com/akuity/kargo/issues/3224 but instead of downstream, it takes freight from upstream for the stage you want to be promoted at the moment
- Promote from upstream will give you promotion space to review
- Quick promote will just trigger promotion action instantly
- Multiple warehouses will get you option to select warehouse

feat(ui): quick promote from upstream

---

internal/indexer/indexer.go
internal/promotion/promotion.go
internal/promotion/promotion_test.go
internal/promotion/runner/builtin/init.go
internal/promotion/runner/builtin/output_composer.go
internal/promotion/simple_engine.go
internal/promotion/simple_engine_test.go
pkg/promotion/promotion.go

This refines the "simple" Promotion engine to address technical debt and improve maintainability. As the features in the engine have grown, several architectural weaknesses have emerged — particularly around state management, component coupling, and code structure. This doesn't completely redesign the system, but makes small improvements to reduce complexity and support future development.
- The `promotion.Context` now acts as the single source of truth for state, and methods no longer accept separate state parameters. Previously, I had avoided this and imagined the context to be read-only. However, with the introduction of `StepExecutionMetadata` we started making direct modifications to `promotion.Context` anyway, and maintaining separate state parameters created an inconsistent pattern …

refactor(runner): promotion engine improvements

---

cmd/controlplane/controller.go
internal/credentials/kubernetes/database.go
internal/credentials/kubernetes/database_test.go

@jessesuen @hiddeco this is a possible solution to the extremely outlying use case we discussed offline of wanting to fall back on searching for creds in the local cluster if none are discovered in the control plane's cluster.
The big, BIG caveat to this is that managing credential Secrets on each shard and the permissions that allow the controller on each shard to access those Secrets is completely left to the operator. There is no feature of Kargo's chart or Kargo itself to facilitate any of this.

feat: support fallback to local cluster when searching for cred secrets

---

internal/controller/stages/regular_stages.go

The indexer was using the rollout controller instance ID instead of the shardName, looking at the underlying function the parameter is called shardName and is used to be checked against the shard label.
This fixes https://github.com/akuity/kargo/issues/4312
I tested it on our live setup and we had no more waiting time after the verification was successful.

fix: sharded kargo setup analysisRun indexer

---

internal/webhook/external/bitbucket.go
internal/webhook/external/bitbucket_test.go
internal/webhook/external/dockerhub.go
internal/webhook/external/dockerhub_test.go
internal/webhook/external/github.go
internal/webhook/external/github_test.go
internal/webhook/external/gitlab.go
internal/webhook/external/gitlab_test.go
internal/webhook/external/quay.go
internal/webhook/external/quay_test.go
internal/webhook/external/receiver.go
internal/webhook/external/refresh.go
internal/webhook/external/refresh_test.go
internal/webhook/external/router.go

All receivers had identical logic for verifying the request body size didn't exceed some maximum and for returning the results of fully or partially successful Warehouse refreshes.
This PR resolves that.

refactor: DRY up webhook receivers

---

docs/docs/40-operator-guide/20-advanced-installation/30-common-configurations.md
docs/docs/40-operator-guide/35-cluster-configuration.md
docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/_category_.json
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/bitbucket.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/dockerhub.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/generic.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/ghcr.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/index.md
docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/quay.md

Part of #4150
Note: This documentation references a few features that are either not merged yet or will be implemented tomorrow -- namely, refresh of ProjectConfig and ClusterConfig resources (#4372) as well as configuring a system-wide Warehouse reconciliation interval via the chart.
cc @fuskovic @fykaa @nitishfy -- you can see where there are placeholders for the details of individual receivers.
@fuskovic' will document a receiver or two in a follow-up PR and then @fykaa and @nitishfy, could you please follow his format for documenting the receivers you each worked on?

docs: webhook receivers

---

docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/index.md

Temporal references (especially in reference documentation) make things harder to read and maintain. They force readers to follow a strict linear path through the documentation and break down when people jump between sections or return to the docs later.
"Earlier" and "previously" create cognitive overhead, as readers have to remember what was done before instead of having the context right there.
They also make the documentation more brittle when sections get reorganized or split across pages. What was "earlier" in one layout might not be earlier in another, and temporal references become meaningless when content gets moved around or referenced from different contexts.

docs: remove some temporal references

---

internal/helm/helm.go
internal/helm/helm_test.go
internal/webhook/external/dockerhub.go
internal/webhook/external/dockerhub_test.go
internal/webhook/external/github.go
internal/webhook/external/github_test.go
internal/webhook/external/quay.go
internal/webhook/external/quay_test.go
internal/webhook/external/receiver.go
internal/webhook/external/refresh.go

Warehouses subscribed to charts in Docker Hub could not successfully be refreshed.
For GitHub/GHCR and Quay, this _did_ work, but only coincidentally. We didn't design for it.
We now check the media type conveyed by payloads from GitHub/GHCR and Docker Hub to determine what kind of normalization logic to apply to the URL we extract from the payload before requesting a refresh of Warehouses subscribed to that URL.
Quay doesn't send media type information, so we normalize the URL _both_ as if it were an image URL and as if it were a chart URL, then refresh Warehouses subscribed to either. This currently results in two identical URLs, but I don't want to take it for granted that normalization logic will never change. To account for this, the refresh logic is also updated to de-dupe URLs.

feat: make image/oci webhook receivers also work for charts

---

charts/kargo/templates/_helpers.tpl

`include` always returns a string and all non-empty strings (including `"false"`) are truthy.
The result is that URLs were _always_ using HTTPS.

chart: fix bug in kargo.baseURL helper

---

charts/kargo/templates/users/cluster-roles.yaml

Missed in #4370 
This PR adds the appropriate level of ClusterConfig permissions for the existing kargo-admin and kargo-viewer ClusterRoles.

fix(chart): add clusterconfig permissions to clusterroles

---

ui/src/pages/user.tsx

In some cases, JWT has an object value in the payload. It caused UI errors.

fix(ui): object was being rendered directly on the User pagen User page

---

charts/kargo/templates/management-controller/cluster-roles.yaml

Prior to #4229, the management controller did not explicitly delete Project namespaces. Projects owned namespaces and deletion of a Project simply cascaded naturally to its namespace.
#4229 gave the management controller more control over whether a namespace is or isn't deleted when the Project that owns it has been deleted. This means that when namespace deletion _is_ required, the management controller now must handle that explicitly.
This PR adds a missing permission required to facilitate that.

fix(chart): grant mgmt controller permission to delete namespaces

---

docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/index.md

We listen to [`package` events](https://docs.github.com/en/webhooks/webhook-events-and-payloads#package) (and not [`registry_package`](https://docs.github.com/en/webhooks/webhook-events-and-payloads#registry_package) events).

docs: proper webhook event type for GitHub

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/http.md
internal/promotion/runner/builtin/http_requester.go
internal/promotion/runner/builtin/http_requester_test.go

This PR fixes a bug where `http` Promotion steps that failed due to failure criteria being met would never retry, even when configured with thresholds.
The issue was that these failures were incorrectly wrapped as `TerminalError`, causing the engine to treat them as unrecoverable errors rather than retryable failures. This meant that transient HTTP issues (like temporary server errors, network timeouts, or unexpected responses) would immediately fail instead of being retried according to the step's error threshold.

fix(runner)!: improve error handling `http` step

---

internal/promotion/promotion.go
internal/promotion/runner/builtin/kustomize_image_setter.go
internal/promotion/runner/builtin/kustomize_image_setter_test.go
internal/yaml/decode.go
internal/yaml/decode_test.go
internal/yaml/update.go
internal/yaml/update_test.go
internal/yaml/yaml.go
internal/yaml/yaml_test.go

This primarily removes aliases, as the `sigs.k8s.io/yaml/goyaml.v3` package has been aliased internally to `go.yaml.in/yaml/v3` without any further changes.

chore: deal with deprecation of `sigs.k8s.io/yaml/goyaml.v3`

---

charts/kargo/templates/management-controller/cluster-roles.yaml
internal/controller/management/projects/projects.go
internal/controller/management/projects/projects_test.go

This avoids requiring explicit delete permissions for namespaces for the management controller role by relying purely on the cascade delete for owner references, and the existence of the finalizer to still allow this reference to be dropped when the namespace has to be kept around.
Follow up to: #4229 #4499

feat(mgmt-controller): rely on GC of NS through owner ref and finalizer

---

Dockerfile

The version of grpc-health-probe we are currently using has some CVE's this updates us to the latest version.

chore: Bump grpc-health-probe to v0.4.39

---

internal/event/promotion.go
internal/event/promotion_test.go

Before the fix, the annotation may look something like this:
```
annotations:
event.kargo.akuity.io/actor: admin
event.kargo.akuity.io/applications: '[{"Namespace":"argocd","Name":"kargo-demo-${{
ctx.stage }}"}]'
```
which was directly recorded before the evaluation with defined variables.

fix: application recorded in promotion event's annotation may be incorrect

---

charts/kargo/templates/garbage-collector/cron-job.yaml

We noticed the Kargo garbage collector was failing with imagePullBackoff error.
The cause was that it's missing imagePullSecrets in the CronJob.

fix(chart): use .Values.image.pullSecrets in garbage collector CronJob

---

internal/webhook/external/azure.go
internal/webhook/external/azure_test.go
internal/webhook/external/dockerhub.go
internal/webhook/external/dockerhub_test.go
internal/webhook/external/github.go
internal/webhook/external/github_test.go
internal/webhook/external/media_types.go
internal/webhook/external/media_types_test.go

My initial pass at determining whether a URL should be normalized as if it is an image repo URL or a chart repo URL was flawed.
What complicates matters is that not all platforms that send us webhooks are consistent or clear about what any media type information they may give us is actually _for_.
Examples:
- GitHub separately gives us the media types for both the manifest and for the config blob!
- DockerHub gives us the media type for the config blob only.
- ACR gives us the media type for the manifest only.
- Quay tells us nothing at all about media types.
This PR is a comprehensive refactor and fix of the logic for determining correct normalization on the basis of media type. Note that when no inference can be drawn, we do what we've always done in the case of Quay and normalize both …

fix: take greater care when examining media types

---

internal/webhook/external/dockerhub.go
internal/webhook/external/dockerhub_test.go
internal/webhook/external/github.go
internal/webhook/external/github_test.go
internal/webhook/external/media_types.go
internal/webhook/external/media_types_test.go

#4704 contained changes to files that this branch does not have (Azure webhook receiver). Those were the only conflicts.

chore(manual backport release-1.6): fix: take greater care when examining media types (#4704)

---

internal/promotion/runner/builtin/http_requester.go
internal/promotion/runner/builtin/http_requester_test.go

Manual backport of #4717 due to conflicts.

chore(backport release-1.6): fix(runner): JSON response `http` without header

---

api/v1alpha1/generated.proto
api/v1alpha1/stage_types.go
charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
internal/webhook/kubernetes/stage/webhook.go
internal/webhook/kubernetes/stage/webhook_test.go
ui/src/gen/api/v1alpha1/generated_pb.ts
ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json

Follow up to #4732
As `if` is a reserved CEL keyword, the expression is not allowed to reference a field with that name in Kubernetes versions below 1.32.x. Because of this, we need to temporarily resort to validating it using a webhook, and reintroduce it once these versions have reached EOL.

fix(api/webhook): move part of Stage step validation to webhook

---

internal/webhook/external/artifactory_test.go
internal/webhook/external/azure_test.go
internal/webhook/external/bitbucket_test.go
internal/webhook/external/dockerhub_test.go
internal/webhook/external/gitea.go
internal/webhook/external/gitea_test.go
internal/webhook/external/github.go
internal/webhook/external/github_test.go
internal/webhook/external/gitlab.go
internal/webhook/external/gitlab_test.go
internal/webhook/external/quay_test.go
internal/webhook/external/refresh_test.go

This adds a substantial number of new test cases -- most of them aimed at testing that tags, versions, refs, etc. that any sort of Warehouse subscription is _not_ interested in do not trigger a refresh even if all other conditions for refresh are met.
i.e. This adds the "miss" cases for #4560.
I did quite a bit of miscellaneous cleanup as well. I improved how test cases are named, which became necessary due to the volume of specific, new permutations introduced by new cases.
Removed explicit setting of default selection strategies -- it ensures there are no gaps of something not working correctly when one _isn't_ specified. e.g. Wrong default strategy used or no default being applied at all.
Replaced many repeated string literals with constants, etc., etc.

refactor: misc. webhook receiver test cleanup

---

api/v1alpha1/annotations.go
internal/controller/stages/control_flow_stages.go
internal/controller/stages/regular_stages.go
internal/controller/stages/regular_stages_test.go
internal/kubernetes/naming.go
internal/server/get_analysisrun_logs_v1alpha1.go
internal/server/get_analysisrun_logs_v1alpha1_test.go

Fixes #4600
In a follow-up, the garbage collection logic will be factored out and/or owner references will be introduced to allow Kubernetes itself to handle the lifecycle.

fix: shorten Stage label value exceeding max length

---

charts/kargo/templates/users/service-accounts.yaml

Minor bug fix to ensure no user sa resources are created when api.enabled is false.

fix: ensure kargo viewer sa is not created if api is disabled

---

charts/kargo/templates/garbage-collector/cron-job.yaml

It seems the incorrect indentation level was used in #4682. In this change I have updated the indentation level for the templated values to match that of other blocks at the same level (e.g., `affinity`, directly above).
Before this change, running `helm template --debug` with `--set 'image.pullSecrets[0].name=secret-name'` results in the following output (irrelevant content stripped for brevity)
```yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
name: kargo-garbage-collector
namespace: kargo
spec:
jobTemplate:
spec:
template:
spec:
imagePullSecrets:
- name: secret-name   # <--- incorrect YAML
```
With this change:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
name: kargo-garbage-collector
namespace: external-dns
spec:
jobTemplate:
spec:
template:
spec:
imagePullSecrets:
- …
```

fix(chart): Fixup indentation level for imagePullSecrets in garbage-collector CronJob

---

docs/docs/50-user-guide/60-reference-docs/40-expressions.md
internal/expressions/function/functions.go
internal/promotion/promotion.go
internal/promotion/promotion_test.go

Closes: https://github.com/akuity/kargo/issues/4537
NOTE:
An alternative way of testing this is by reverting the change to `internal/promotion/promotion.go` without reverting `internal/promotion/promotion_test.go`.
Then, when you run the test, you will reproduce the error documented in https://github.com/akuity/kargo/issues/4537.
e.g.
```
=== RUN   TestStep_GetConfig/test_success_function
promotion_test.go:501: 
Error Trace:    /Users/faris/go/src/github.com/akuity/kargo/internal/promotion/promotion_test.go:501
Error:          Received unexpected error:
reflect: call of reflect.Value.Call on zero Value (1:2)
|  success() 
| .^
Test:           TestStep_GetConfig/test_success_function
```
Keeping the change applied results in passing tests
I will include the doc update in this PR as well

feat: support status operation expressions in config context

---

docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
docs/docs/50-user-guide/60-reference-docs/40-expressions.md

closes https://github.com/akuity/kargo/issues/4706
I believe this information will also be useful in the [Working with Stages](https://docs.kargo.io/user-guide/how-to-guides/working-with-stages#the-stage-resource-type) , as users engaging directly with stages can learn it on the spot. That’s why I added this commit cfd051d57c1183cd1fef30f08d8fbf01aa9cd434. (The commit can be reverted if it’s not needed)

docs: missing mention of variables at stage level

---

docs/docs/50-user-guide/60-reference-docs/40-expressions.md
internal/controller/stages/regular_stages.go
internal/expressions/function/functions.go
internal/expressions/function/functions_test.go
internal/promotion/promotion.go

Manual backport of #4723
The merge conflict centered around status-related functions not yet being available within the context of a promotion in 1.7.x. That is currently only in main.

chore: manual cherry pick #4723 -- Add semverDiff function for semantic version comparison in expressions

---

docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/http.md

closes https://github.com/akuity/kargo/issues/3989

docs: how to access `vars` & `outputs` in `http` step's success/failure expressions

---

docs/docs/50-user-guide/20-how-to-guides/70-argo-cd-integration.md

This removes the conflict understanding b/w argo proj and kargo proj.

docs: update the project naming convention

---

.github/ISSUE_TEMPLATE/config.yml
README.md

Fixes #4922
We were using the non-permalink Discord invite link in some places. This changes us to use the permalink, https://akuity.community, which will prevent us from having to update any future links going forward.

docs: fix discord invite link to the permalink

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Dockerfile
Dockerfile.dev
api/go.mod
go.mod
hack/tools/go.mod
pkg/go.mod

This would unblock #4966, #4967, and #4968.

chore(deps): bump golang from 1.24.6-bookworm to 1.25.0-trixie

---

ui/src/features/project/pipelines/url-params/use-freight-timeline-controller-store.ts

https://github.com/akuity/kargo/issues/4988
There were 2 source of truths for filters (query params and local storage) that, if one of not properly updated, will cause issues when that source of truth is prioritised (it is prio in sub-pages of project because it is ugly to inject params in each and every subpage) so we rely on local storage in those cases.
This PR will make sure that local storage is also being updated as filters are changed, and being prioritised more than query params
https://github.com/user-attachments/assets/620d9ca2-bc64-424a-8e44-ec2c66f4a03c

fix(ui): filter issues

---

pkg/event/freight.go
pkg/event/promotion.go

As I was revisiting some of this code again, I think it will be better to not embed some of these structs so that the data layout is clearer. For example, rather than something on a promotion event like this:
`.promotion.freightName` it becomes `.promotion.freight.name`

refactor(events): Rename encoding for event fields

---

ui/src/features/project/pipelines/nodes/stage-meta-utils.ts
ui/src/features/project/pipelines/nodes/stage-node.tsx
ui/src/utils/get-contrast-text-color.test.ts
ui/src/utils/get-contrast-text-color.ts

fixes #5017 
1.  Added light black text shadow
2. For very bright background colors, the font should be black now
Before:
After:

feat(ui): Increase Stage name visibility on bright bg colors

---

docs/package.json
docs/plugins/gtag/package.json
docs/plugins/gtag/pnpm-lock.yaml
docs/pnpm-lock.yaml

dependabot has flagged security vulnerabilities in the current Docusaurus version, so we are updating it to resolve these issues

chore: update docusaurus 3.8.1

---

internal/server/common.go
internal/server/common_test.go
internal/server/get_analysisrun_v1alpha1.go
internal/server/get_analysistemplate_v1alpha1.go
internal/server/get_cluster_config_v1alpha1.go
internal/server/get_cluster_promotion_task_v1alpha1.go
internal/server/get_clusteranalysistemplate_v1alpha1.go
internal/server/get_config_map_v1alpha1.go
internal/server/get_credentials_v1alpha1.go
internal/server/get_freight_v1alpha1.go
internal/server/get_project_config_v1alpha1.go
internal/server/get_project_v1alpha1.go
internal/server/get_promotion_task_v1alpha1.go
internal/server/get_promotion_v1alpha1.go
internal/server/get_stage_v1alpha1.go
internal/server/get_warehouse_v1alpha1.go

I was bugged non-DRYness of the API endpoints and redundant checks for desired format (endpoint checks and `objectOrRaw()` also does).
This also ensures GVK info is not lost when marshaling a structured object to JSON or YAML.

refactor(api-server): dry up api endpoints

---

pkg/event/custom.go
pkg/event/event.go
pkg/event/event_test.go
pkg/event/freight.go
pkg/event/freight_test.go
pkg/event/kubernetes/kubernetes.go
pkg/event/kubernetes/kubernetes_test.go
pkg/event/promotion.go
pkg/event/promotion_test.go

My initial rough draft had it, but I didn't add it back in when I refactored. This is useful for logging and debugging to more readily identify an event. I also improved some of my original tests while I was here

feat(events)!: Add an event ID to all events

---

README.md

@thomastaylor312 pointed out certain stale elements of the `README.md` yesterday. I took the opportunity to make some other small improvements while addressing them:
* Introductory line updated with simpler language that also more closely reflects how we _currently_ talk about Kargo. I've also:
* Dropped the use of the word "application" in favor of more general "software artifacts" because we've seen so many cases of Kargo being used to manage infrastructure, especially cluster "add-ons."
* Made the word Akuity a link.
* Removed the disclaimer that the docs are very new.
* Moved Support and Feedback section above the Contributing section. I also reworded this section to:
* Make the distinction that the issue queue is for bugs and feature requests while _questions_ should be posed by …

chore: small README.md updates

---

.github/workflows/ci.yaml

If permissions are set at the job level, the default permissions are no longer applied. Explicitly define `read` permissions for `contents` in these places to ensure the CI works in all scenarios (e.g., when the repository is not public).

fix(ci): set permissions for linters
